// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace ExampleAspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		private static class GetCustomers_Interceptor_State
		{
			internal static readonly SR.MemberInfo TargetMethod = MethodOf(() => TransactionAspect.Program.GetCustomers(default(LinqToDB.Data.DataConnection)));
			internal static readonly global::Aspects.TransactionAttribute Aspect0 = new global::Aspects.TransactionAttribute() { IsolationLevel = (System.Data.IsolationLevel)256 };

			static GetCustomers_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts TransactionAspect.Program.GetCustomers(LinqToDB.Data.DataConnection).
		/// </summary>
		//
		// Intercepts GetCustomers(db).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ZKlJ3/dLCHFyq3z8/hvMxngDAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static System.Collections.Generic.List<TransactionAspect.Program.Customer> GetCustomers_Interceptor(LinqToDB.Data.DataConnection db)
		{
			var __args__ = new object?[] { db };

			// Aspects.TransactionAttribute(IsolationLevel = System.Data.IsolationLevel.ReadUncommitted)
			//
			var __targetMethod__ = GetCustomers_Interceptor_State.TargetMethod;
			var __aspect__0 = GetCustomers_Interceptor_State.Aspect0;
			var __info__0 = new AspectGenerator.InterceptInfo<System.Collections.Generic.List<TransactionAspect.Program.Customer>>
			{
				MemberInfo      = __targetMethod__,
				AspectType      = typeof(Aspects.TransactionAttribute),
				Aspect          = __aspect__0,
				MethodArguments = __args__,
			};

			try
			{
				Aspects.TransactionAttribute.OnBeforeCall(__info__0);

				if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
				{
					__info__0.ReturnValue = TransactionAspect.Program.GetCustomers(db);
				}
			}
			catch (Exception __ex__)
			{
				__info__0.Exception = __ex__;
				throw;
			}
			finally
			{
				Aspects.TransactionAttribute.OnFinally(__info__0);
			}

			return __info__0.ReturnValue;
		}

		private static class GetCustomersAsync_Interceptor_State
		{
			internal static readonly SR.MemberInfo TargetMethod = MethodOf(() => TransactionAspect.Program.GetCustomersAsync(default(LinqToDB.Data.DataConnection)));
			internal static readonly global::Aspects.TransactionAttribute Aspect0 = new global::Aspects.TransactionAttribute();

			static GetCustomersAsync_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts TransactionAspect.Program.GetCustomersAsync(LinqToDB.Data.DataConnection).
		/// </summary>
		//
		// Intercepts GetCustomersAsync(db).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "ZKlJ3/dLCHFyq3z8/hvMxpkDAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static async System.Threading.Tasks.Task<System.Collections.Generic.List<TransactionAspect.Program.Customer>> GetCustomersAsync_Interceptor(LinqToDB.Data.DataConnection db)
		{
			var __args__ = new object?[] { db };

			// Aspects.TransactionAttribute
			//
			var __targetMethod__ = GetCustomersAsync_Interceptor_State.TargetMethod;
			var __aspect__0 = GetCustomersAsync_Interceptor_State.Aspect0;
			var __info__0 = new AspectGenerator.InterceptInfo<System.Collections.Generic.List<TransactionAspect.Program.Customer>>
			{
				MemberInfo      = __targetMethod__,
				AspectType      = typeof(Aspects.TransactionAttribute),
				Aspect          = __aspect__0,
				MethodArguments = __args__,
			};

			try
			{
				await Aspects.TransactionAttribute.OnBeforeCallAsync(__info__0);

				if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
				{
					__info__0.ReturnValue = await TransactionAspect.Program.GetCustomersAsync(db);
				}
			}
			catch (Exception __ex__)
			{
				__info__0.Exception = __ex__;
				throw;
			}
			finally
			{
				await Aspects.TransactionAttribute.OnFinallyAsync(__info__0);
			}

			return __info__0.ReturnValue;
		}
	}
}
