// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		static readonly Lazy<SR.MemberInfo> AsyncMethod_Interceptor_MemberInfo = new(() => MethodOf(() => OpenTelemetryAspect.Program.AsyncMethod()));
		static readonly Lazy<global::Aspects.MetricsAttribute> AsyncMethod_Interceptor_Aspect_0 = new(() => new global::Aspects.MetricsAttribute());
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.AsyncMethod().
		/// </summary>
		//
		// Intercepts AsyncMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKDIBAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static async System.Threading.Tasks.Task<string> AsyncMethod_Interceptor()
		{
			// Aspects.MetricsAttribute
			//
			var __aspect__0 = AsyncMethod_Interceptor_Aspect_0.Value;
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = AsyncMethod_Interceptor_MemberInfo.Value,
				AspectType      = typeof(Aspects.MetricsAttribute),
				Aspect          = __aspect__0,
			};

			await using (Aspects.MetricsAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					__info__0.ReturnValue = await OpenTelemetryAspect.Program.AsyncMethod();
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					throw;
				}
				finally
				{
					Aspects.MetricsAttribute.OnFinally(__info__0);
				}
			}

			return __info__0.ReturnValue;
		}

		static readonly Lazy<SR.MemberInfo> Method1_Interceptor_MemberInfo = new(() => MethodOf(() => OpenTelemetryAspect.Program.Method1()));
		static readonly Lazy<global::Aspects.MetricsAttribute> Method1_Interceptor_Aspect_0 = new(() => new global::Aspects.MetricsAttribute());
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.Method1().
		/// </summary>
		//
		// Intercepts Method1().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKOUAAABQcm9ncmFtLmNz")]
		//
		// Intercepts Method1().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKAUBAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void Method1_Interceptor()
		{
			// Aspects.MetricsAttribute
			//
			var __aspect__0 = Method1_Interceptor_Aspect_0.Value;
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = Method1_Interceptor_MemberInfo.Value,
				AspectType      = typeof(Aspects.MetricsAttribute),
				Aspect          = __aspect__0,
			};

			using (Aspects.MetricsAttribute.OnUsing(__info__0))
			{
				try
				{
					OpenTelemetryAspect.Program.Method1();
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					throw;
				}
				finally
				{
					Aspects.MetricsAttribute.OnFinally(__info__0);
				}
			}
		}

		static readonly Lazy<SR.MemberInfo> Method2_Interceptor_MemberInfo = new(() => MethodOf(() => OpenTelemetryAspect.Program.Method2()));
		static readonly Lazy<global::Aspects.MetricsAttribute> Method2_Interceptor_Aspect_0 = new(() => new global::Aspects.MetricsAttribute());
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.Method2().
		/// </summary>
		//
		// Intercepts Method2().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKPYAAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void Method2_Interceptor()
		{
			// Aspects.MetricsAttribute
			//
			var __aspect__0 = Method2_Interceptor_Aspect_0.Value;
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = Method2_Interceptor_MemberInfo.Value,
				AspectType      = typeof(Aspects.MetricsAttribute),
				Aspect          = __aspect__0,
			};

			using (Aspects.MetricsAttribute.OnUsing(__info__0))
			{
				try
				{
					OpenTelemetryAspect.Program.Method2();
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					throw;
				}
				finally
				{
					Aspects.MetricsAttribute.OnFinally(__info__0);
				}
			}
		}

		static readonly Lazy<SR.MemberInfo> MethodException_Interceptor_MemberInfo = new(() => MethodOf(() => OpenTelemetryAspect.Program.MethodException()));
		static readonly Lazy<global::Aspects.IgnoreCatchAttribute> MethodException_Interceptor_Aspect_0 = new(() => new global::Aspects.IgnoreCatchAttribute());
		static readonly Lazy<global::Aspects.MetricsAttribute> MethodException_Interceptor_Aspect_1 = new(() => new global::Aspects.MetricsAttribute());
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.MethodException().
		/// </summary>
		//
		// Intercepts MethodException().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKBQBAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void MethodException_Interceptor()
		{
			// Aspects.IgnoreCatchAttribute
			//
			var __aspect__0 = MethodException_Interceptor_Aspect_0.Value;
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = MethodException_Interceptor_MemberInfo.Value,
				AspectType      = typeof(Aspects.IgnoreCatchAttribute),
				Aspect          = __aspect__0,
			};

			try
			{
				{
					// Aspects.MetricsAttribute
					//
					var __aspect__1 = MethodException_Interceptor_Aspect_1.Value;
					var __info__1 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
					{
						MemberInfo      = MethodException_Interceptor_MemberInfo.Value,
						AspectType      = typeof(Aspects.MetricsAttribute),
						Aspect          = __aspect__1,
						PreviousInfo    = __info__0
					};

					using (Aspects.MetricsAttribute.OnUsing(__info__1))
					{
						try
						{
							OpenTelemetryAspect.Program.MethodException();
						}
						catch (Exception __ex__)
						{
							__info__1.Exception = __ex__;
							throw;
						}
						finally
						{
							Aspects.MetricsAttribute.OnFinally(__info__1);
						}
					}

					__info__0.ReturnValue = __info__1.ReturnValue;
				}
			}
			catch (Exception __ex__)
			{
				__info__0.Exception       = __ex__;
				__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

				Aspects.IgnoreCatchAttribute.OnCatch(__info__0);

				if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
					throw;
			}
		}
	}
}
