// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		private static class AsyncMethod_Interceptor_State
		{
			internal static readonly global::System.Reflection.MemberInfo TargetMethod = MethodOf(() => OpenTelemetryAspect.Program.AsyncMethod());

			internal static readonly global::Aspects.MetricsAttribute Aspect0 = new global::Aspects.MetricsAttribute();

			static AsyncMethod_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.AsyncMethod().
		/// </summary>
		//
		// Intercepts AsyncMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKDIBAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static async System.Threading.Tasks.Task<string> AsyncMethod_Interceptor()
		{
			// Aspects.MetricsAttribute
			//
			var __targetMethod__ = AsyncMethod_Interceptor_State.TargetMethod;

			var __aspect__0 = AsyncMethod_Interceptor_State.Aspect0;
			var __info__0   = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo = __targetMethod__,
				Aspect     = __aspect__0,
			};

			await using (Aspects.MetricsAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					__info__0.ReturnValue = await OpenTelemetryAspect.Program.AsyncMethod();
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					throw;
				}
				finally
				{
					Aspects.MetricsAttribute.OnFinally(__info__0);
				}
			}

			return __info__0.ReturnValue;
		}

		private static class Method1_Interceptor_State
		{
			internal static readonly global::System.Reflection.MemberInfo TargetMethod = MethodOf(() => OpenTelemetryAspect.Program.Method1());

			internal static readonly global::Aspects.MetricsAttribute Aspect0 = new global::Aspects.MetricsAttribute();

			static Method1_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.Method1().
		/// </summary>
		//
		// Intercepts Method1().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKOUAAABQcm9ncmFtLmNz")]
		//
		// Intercepts Method1().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKAUBAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void Method1_Interceptor()
		{
			// Aspects.MetricsAttribute
			//
			var __targetMethod__ = Method1_Interceptor_State.TargetMethod;

			var __aspect__0 = Method1_Interceptor_State.Aspect0;
			var __info__0   = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo = __targetMethod__,
				Aspect     = __aspect__0,
			};

			using (Aspects.MetricsAttribute.OnUsing(__info__0))
			{
				try
				{
					OpenTelemetryAspect.Program.Method1();
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					throw;
				}
				finally
				{
					Aspects.MetricsAttribute.OnFinally(__info__0);
				}
			}
		}

		private static class Method2_Interceptor_State
		{
			internal static readonly global::System.Reflection.MemberInfo TargetMethod = MethodOf(() => OpenTelemetryAspect.Program.Method2());

			internal static readonly global::Aspects.MetricsAttribute Aspect0 = new global::Aspects.MetricsAttribute();

			static Method2_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.Method2().
		/// </summary>
		//
		// Intercepts Method2().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKPYAAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void Method2_Interceptor()
		{
			// Aspects.MetricsAttribute
			//
			var __targetMethod__ = Method2_Interceptor_State.TargetMethod;

			var __aspect__0 = Method2_Interceptor_State.Aspect0;
			var __info__0   = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo = __targetMethod__,
				Aspect     = __aspect__0,
			};

			using (Aspects.MetricsAttribute.OnUsing(__info__0))
			{
				try
				{
					OpenTelemetryAspect.Program.Method2();
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					throw;
				}
				finally
				{
					Aspects.MetricsAttribute.OnFinally(__info__0);
				}
			}
		}

		private static class MethodException_Interceptor_State
		{
			internal static readonly global::System.Reflection.MemberInfo TargetMethod = MethodOf(() => OpenTelemetryAspect.Program.MethodException());

			internal static readonly global::Aspects.IgnoreCatchAttribute Aspect0 = new global::Aspects.IgnoreCatchAttribute();
			internal static readonly global::Aspects.MetricsAttribute Aspect1 = new global::Aspects.MetricsAttribute();

			static MethodException_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts OpenTelemetryAspect.Program.MethodException().
		/// </summary>
		//
		// Intercepts MethodException().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "FeZlU2OG8Ygf85iSYjbQKBQBAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void MethodException_Interceptor()
		{
			// Aspects.IgnoreCatchAttribute
			//
			var __targetMethod__ = MethodException_Interceptor_State.TargetMethod;

			var __aspect__0 = MethodException_Interceptor_State.Aspect0;
			var __info__0   = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo = __targetMethod__,
				Aspect     = __aspect__0,
			};

			try
			{
				{
					// Aspects.MetricsAttribute
					//
					var __aspect__1 = MethodException_Interceptor_State.Aspect1;
					var __info__1   = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
					{
						MemberInfo = __targetMethod__,
						Aspect     = __aspect__1,
						PreviousInfo = __info__0
					};

					using (Aspects.MetricsAttribute.OnUsing(__info__1))
					{
						try
						{
							OpenTelemetryAspect.Program.MethodException();
						}
						catch (Exception __ex__)
						{
							__info__1.Exception = __ex__;
							throw;
						}
						finally
						{
							Aspects.MetricsAttribute.OnFinally(__info__1);
						}
					}

					__info__0.ReturnValue = __info__1.ReturnValue;
				}
			}
			catch (Exception __ex__)
			{
				__info__0.Exception       = __ex__;
				__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

				Aspects.IgnoreCatchAttribute.OnCatch(__info__0);

				if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
					throw;
			}
		}
	}
}
