// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;
using SCG = System.Collections.Generic;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace MyAspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		static SR. MemberInfo                 AllEventsMethod_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).AllEventsMethod());
		static SCG.Dictionary<string,object?> AllEventsMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.AllEventsMethod().
		/// </summary>
		//
		// Intercepts AllEventsMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/ztUhAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static void AllEventsMethod_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.AllEventsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = AllEventsMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.AllEventsAttribute),
				AspectArguments = AllEventsMethod_Interceptor_AspectArguments_0,
			};

			__info__0 = Aspects.AllEventsAttribute.OnInit(__info__0);

			using (Aspects.AllEventsAttribute.OnUsing(__info__0))
			{
				try
				{
					Aspects.AllEventsAttribute.OnBeforeCall(__info__0);

					if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
					{
						__this__.AllEventsMethod();

						Aspects.AllEventsAttribute.OnAfterCall(__info__0);
					}
				}
				catch (Exception __ex__)
				{
					__info__0.Exception       = __ex__;
					__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

					Aspects.AllEventsAttribute.OnCatch(__info__0);

					if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
						throw;
				}
				finally
				{
					Aspects.AllEventsAttribute.OnFinally(__info__0);
				}
			}
		}

		static SR. MemberInfo                 AllEventsMethodAsync_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).AllEventsMethodAsync());
		static SCG.Dictionary<string,object?> AllEventsMethodAsync_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.AllEventsMethodAsync().
		/// </summary>
		//
		// Intercepts AllEventsMethodAsync().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zu8lAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static async System.Threading.Tasks.Task AllEventsMethodAsync_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.AllEventsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = AllEventsMethodAsync_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.AllEventsAttribute),
				AspectArguments = AllEventsMethodAsync_Interceptor_AspectArguments_0,
			};

			__info__0 = Aspects.AllEventsAttribute.OnInit(__info__0);

			await using (Aspects.AllEventsAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					await Aspects.AllEventsAttribute.OnBeforeCallAsync(__info__0);

					if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
					{
						__this__.AllEventsMethodAsync();

						await Aspects.AllEventsAttribute.OnAfterCallAsync(__info__0);
					}
				}
				catch (Exception __ex__)
				{
					__info__0.Exception       = __ex__;
					__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

					await Aspects.AllEventsAttribute.OnCatchAsync(__info__0);

					if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
						throw;
				}
				finally
				{
					await Aspects.AllEventsAttribute.OnFinallyAsync(__info__0);
				}
			}
		}

		static SR. MemberInfo                 AllEventsMethodAsync2_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).AllEventsMethodAsync2());
		static SCG.Dictionary<string,object?> AllEventsMethodAsync2_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.AllEventsMethodAsync2().
		/// </summary>
		//
		// Intercepts AllEventsMethodAsync2().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zh8qAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static async System.Threading.Tasks.Task<int> AllEventsMethodAsync2_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.AllEventsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = AllEventsMethodAsync2_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.AllEventsAttribute),
				AspectArguments = AllEventsMethodAsync2_Interceptor_AspectArguments_0,
			};

			__info__0 = Aspects.AllEventsAttribute.OnInit(__info__0);

			await using (Aspects.AllEventsAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					await Aspects.AllEventsAttribute.OnBeforeCallAsync(__info__0);

					if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
					{
						__info__0.ReturnValue = await __this__.AllEventsMethodAsync2();

						await Aspects.AllEventsAttribute.OnAfterCallAsync(__info__0);
					}
				}
				catch (Exception __ex__)
				{
					__info__0.Exception       = __ex__;
					__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

					await Aspects.AllEventsAttribute.OnCatchAsync(__info__0);

					if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
						throw;
				}
				finally
				{
					await Aspects.AllEventsAttribute.OnFinallyAsync(__info__0);
				}
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ArgsMethod_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).ArgsMethod());
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_0 = new()
		{
			["Arg1"] = "1",
			["Arg2"] = 2,
			["Arg3"] = new int[] { 1, 2, 3 },
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_1 = new()
		{
			["Arg3"] = new int[] { 2 },
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_2 = new()
		{
			["Arg3"] = new int[0],
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_3 = new()
		{
			["Arg1"] = "xyz",
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_4 = new()
		{
			["Arg4"] = 'w',
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_5 = new()
		{
			["Arg5"] = null,
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_6 = new()
		{
			["Arg5"] = typeof(int),
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_7 = new()
		{
			["Arg5"] = typeof(global::System.Collections.Generic.List<>),
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_8 = new()
		{
			["Arg5"] = typeof(global::System.Collections.Generic.List<global::System.DateTime>),
		};
		static SCG.Dictionary<string,object?> ArgsMethod_Interceptor_AspectArguments_9 = new()
		{
			["Arg5"] = 1.1d,
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgsMethod().
		/// </summary>
		//
		// Intercepts ArgsMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/ztk4AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgsMethod_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.ArgsAttribute(Arg1 = "1", Arg2 = 2, Arg3 = {1, 2, 3})
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ArgsAttribute),
				AspectArguments = ArgsMethod_Interceptor_AspectArguments_0,
			};

			{
				// Aspects.ArgsAttribute(Arg3 = {2})
				//
				var __info__1 = new AspectGenerator.InterceptInfo<string>
				{
					MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
					AspectType      = typeof(Aspects.ArgsAttribute),
					AspectArguments = ArgsMethod_Interceptor_AspectArguments_1,
					PreviousInfo    = __info__0
				};

				{
					// Aspects.ArgsAttribute(Arg3 = {})
					//
					var __info__2 = new AspectGenerator.InterceptInfo<string>
					{
						MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
						AspectType      = typeof(Aspects.ArgsAttribute),
						AspectArguments = ArgsMethod_Interceptor_AspectArguments_2,
						PreviousInfo    = __info__1
					};

					{
						// Aspects.ArgsAttribute(Arg1 = "xyz")
						//
						var __info__3 = new AspectGenerator.InterceptInfo<string>
						{
							MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
							AspectType      = typeof(Aspects.ArgsAttribute),
							AspectArguments = ArgsMethod_Interceptor_AspectArguments_3,
							PreviousInfo    = __info__2
						};

						{
							// Aspects.ArgsAttribute(Arg4 = 'w')
							//
							var __info__4 = new AspectGenerator.InterceptInfo<string>
							{
								MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
								AspectType      = typeof(Aspects.ArgsAttribute),
								AspectArguments = ArgsMethod_Interceptor_AspectArguments_4,
								PreviousInfo    = __info__3
							};

							{
								// Aspects.ArgsAttribute(Arg5 = null)
								//
								var __info__5 = new AspectGenerator.InterceptInfo<string>
								{
									MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
									AspectType      = typeof(Aspects.ArgsAttribute),
									AspectArguments = ArgsMethod_Interceptor_AspectArguments_5,
									PreviousInfo    = __info__4
								};

								{
									// Aspects.ArgsAttribute(Arg5 = typeof(int))
									//
									var __info__6 = new AspectGenerator.InterceptInfo<string>
									{
										MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
										AspectType      = typeof(Aspects.ArgsAttribute),
										AspectArguments = ArgsMethod_Interceptor_AspectArguments_6,
										PreviousInfo    = __info__5
									};

									{
										// Aspects.ArgsAttribute(Arg5 = typeof(System.Collections.Generic.List<>))
										//
										var __info__7 = new AspectGenerator.InterceptInfo<string>
										{
											MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
											AspectType      = typeof(Aspects.ArgsAttribute),
											AspectArguments = ArgsMethod_Interceptor_AspectArguments_7,
											PreviousInfo    = __info__6
										};

										{
											// Aspects.ArgsAttribute(Arg5 = typeof(System.Collections.Generic.List<System.DateTime>))
											//
											var __info__8 = new AspectGenerator.InterceptInfo<string>
											{
												MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
												AspectType      = typeof(Aspects.ArgsAttribute),
												AspectArguments = ArgsMethod_Interceptor_AspectArguments_8,
												PreviousInfo    = __info__7
											};

											{
												// Aspects.ArgsAttribute(Arg5 = 1.1)
												//
												var __info__9 = new AspectGenerator.InterceptInfo<string>
												{
													MemberInfo      = ArgsMethod_Interceptor_MemberInfo,
													AspectType      = typeof(Aspects.ArgsAttribute),
													AspectArguments = ArgsMethod_Interceptor_AspectArguments_9,
													PreviousInfo    = __info__8
												};

												__info__9.ReturnValue = __this__.ArgsMethod();

												Aspects.ArgsAttribute.OnAfterCall(__info__9);

												__info__8.ReturnValue = __info__9.ReturnValue;
											}

											Aspects.ArgsAttribute.OnAfterCall(__info__8);

											__info__7.ReturnValue = __info__8.ReturnValue;
										}

										Aspects.ArgsAttribute.OnAfterCall(__info__7);

										__info__6.ReturnValue = __info__7.ReturnValue;
									}

									Aspects.ArgsAttribute.OnAfterCall(__info__6);

									__info__5.ReturnValue = __info__6.ReturnValue;
								}

								Aspects.ArgsAttribute.OnAfterCall(__info__5);

								__info__4.ReturnValue = __info__5.ReturnValue;
							}

							Aspects.ArgsAttribute.OnAfterCall(__info__4);

							__info__3.ReturnValue = __info__4.ReturnValue;
						}

						Aspects.ArgsAttribute.OnAfterCall(__info__3);

						__info__2.ReturnValue = __info__3.ReturnValue;
					}

					Aspects.ArgsAttribute.OnAfterCall(__info__2);

					__info__1.ReturnValue = __info__2.ReturnValue;
				}

				Aspects.ArgsAttribute.OnAfterCall(__info__1);

				__info__0.ReturnValue = __info__1.ReturnValue;
			}

			Aspects.ArgsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static bool                           ArgumentsInMethod_Interceptor_Arg_b             = default(bool);
		static int?                           ArgumentsInMethod_Interceptor_Arg__             = default(int?);
		static SR. MemberInfo                 ArgumentsInMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ArgumentsInMethod(default(string), default(int), in ArgumentsInMethod_Interceptor_Arg_b, ref ArgumentsInMethod_Interceptor_Arg__));
		static SCG.Dictionary<string,object?> ArgumentsInMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgumentsInMethod(string, int, in bool, ref int?).
		/// </summary>
		//
		// Intercepts ArgumentsInMethod("_", 1, in b, ref n).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zjBCAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgumentsInMethod_Interceptor(string s, int i, in bool b, ref int? _)
		{
			var __args__ = new object?[] { s, i, b, _ };

			// Aspects.ArgumentsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgumentsInMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ArgumentsAttribute),
				AspectArguments = ArgumentsInMethod_Interceptor_AspectArguments_0,
				MethodArguments = __args__,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.ArgumentsInMethod(s, i, in b, ref _);

			Aspects.ArgumentsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static int?                           ArgumentsInMethod_Interceptor_1_Arg__             = default(int?);
		static SR. MemberInfo                 ArgumentsInMethod_Interceptor_1_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ArgumentsInMethod(default(string), default(int), default(bool), ref ArgumentsInMethod_Interceptor_1_Arg__));
		static SCG.Dictionary<string,object?> ArgumentsInMethod_Interceptor_1_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgumentsInMethod(string, int, bool, ref int?).
		/// </summary>
		//
		// Intercepts ArgumentsInMethod("_", 1, b, ref n).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/znVDAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgumentsInMethod_Interceptor_1(string s, int i, bool b, ref int? _)
		{
			var __args__ = new object?[] { s, i, b, _ };

			// Aspects.ArgumentsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgumentsInMethod_Interceptor_1_MemberInfo,
				AspectType      = typeof(Aspects.ArgumentsAttribute),
				AspectArguments = ArgumentsInMethod_Interceptor_1_AspectArguments_0,
				MethodArguments = __args__,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.ArgumentsInMethod(s, i, b, ref _);

			Aspects.ArgumentsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ArgumentsMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ArgumentsMethod());
		static SCG.Dictionary<string,object?> ArgumentsMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgumentsMethod().
		/// </summary>
		//
		// Intercepts ArgumentsMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zu4+AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgumentsMethod_Interceptor()
		{
			var __args__ = new object?[] { };

			// Aspects.ArgumentsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgumentsMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ArgumentsAttribute),
				AspectArguments = ArgumentsMethod_Interceptor_AspectArguments_0,
				MethodArguments = __args__,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.ArgumentsMethod();

			Aspects.ArgumentsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ArgumentsMethod_Interceptor_2_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ArgumentsMethod(default(string), default(int)));
		static SCG.Dictionary<string,object?> ArgumentsMethod_Interceptor_2_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgumentsMethod(string, int).
		/// </summary>
		//
		// Intercepts ArgumentsMethod("_", 1).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/ztc/AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgumentsMethod_Interceptor_2(string s, int i)
		{
			var __args__ = new object?[] { s, i };

			// Aspects.ArgumentsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgumentsMethod_Interceptor_2_MemberInfo,
				AspectType      = typeof(Aspects.ArgumentsAttribute),
				AspectArguments = ArgumentsMethod_Interceptor_2_AspectArguments_0,
				MethodArguments = __args__,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.ArgumentsMethod(s, i);

			Aspects.ArgumentsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static string                         ArgumentsOutMethod_Interceptor_Arg_s             = default(string);
		static SR. MemberInfo                 ArgumentsOutMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ArgumentsOutMethod(out ArgumentsOutMethod_Interceptor_Arg_s));
		static SCG.Dictionary<string,object?> ArgumentsOutMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgumentsOutMethod(out string).
		/// </summary>
		//
		// Intercepts ArgumentsOutMethod(out _).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zolEAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgumentsOutMethod_Interceptor(out string s)
		{
			var __args__ = new object?[] { s = default };

			// Aspects.ArgumentsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgumentsOutMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ArgumentsAttribute),
				AspectArguments = ArgumentsOutMethod_Interceptor_AspectArguments_0,
				MethodArguments = __args__,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.ArgumentsOutMethod(out s);

			Aspects.ArgumentsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static bool                           ArgumentsRefMethod_Interceptor_Arg_b             = default(bool);
		static SR. MemberInfo                 ArgumentsRefMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ArgumentsRefMethod(default(string), default(int), ref ArgumentsRefMethod_Interceptor_Arg_b));
		static SCG.Dictionary<string,object?> ArgumentsRefMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ArgumentsRefMethod(string, int, ref bool).
		/// </summary>
		//
		// Intercepts ArgumentsRefMethod("_", 1, ref b).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zu5AAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ArgumentsRefMethod_Interceptor(string s, int i, ref bool b)
		{
			var __args__ = new object?[] { s, i, b };

			// Aspects.ArgumentsAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = ArgumentsRefMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ArgumentsAttribute),
				AspectArguments = ArgumentsRefMethod_Interceptor_AspectArguments_0,
				MethodArguments = __args__,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.ArgumentsRefMethod(s, i, ref b);

			Aspects.ArgumentsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 AssemblyFilterTarget_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.AssemblyFilterTarget());
		static SCG.Dictionary<string,object?> AssemblyFilterTarget_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.AssemblyFilterTarget().
		/// </summary>
		//
		// Intercepts AssemblyFilterTarget().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zroXAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string AssemblyFilterTarget_Interceptor()
		{
			// Aspects.LogAttribute(TargetFilter = {"regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.AssemblyFilterTarget\\(\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedMethod\\(System.String\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedGenericMethod<System.String>\\(System.String\\)$", "regex: ^public System.String System.String.Substring\\(System.Int32\\)$"})
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = AssemblyFilterTarget_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.LogAttribute),
				AspectArguments = AssemblyFilterTarget_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.AssemblyFilterTarget();

			Aspects.LogAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 EmptyMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.EmptyMethod());
		static SCG.Dictionary<string,object?> EmptyMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.EmptyMethod().
		/// </summary>
		//
		// Intercepts EmptyMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zosbAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int EmptyMethod_Interceptor()
		{
			var __return__ = AspectGenerator.Tests.UnitTests.EmptyMethod();

			return __return__;
		}

		static SR. MemberInfo                 ExtensionMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.TestCodeExtensions.ExtensionMethod(default(AspectGenerator.Tests.UnitTests), default(int)));
		static SCG.Dictionary<string,object?> ExtensionMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ExtensionMethod<int>(int).
		/// </summary>
		//
		// Intercepts this.ExtensionMethod(1).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zksfAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ExtensionMethod_Interceptor(this AspectGenerator.Tests.UnitTests __this__, int value)
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = ExtensionMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = ExtensionMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.TestCodeExtensions.ExtensionMethod(__this__, value);

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ExtensionMethod_Interceptor_3_MemberInfo        = MethodOf(() => AspectGenerator.Tests.TestCodeExtensions.ExtensionMethod(default(AspectGenerator.Tests.TestClassExtension), default(int)));
		static SCG.Dictionary<string,object?> ExtensionMethod_Interceptor_3_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.TestClassExtension.ExtensionMethod<int>(int).
		/// </summary>
		//
		// Intercepts new TestClassExtension().ExtensionMethod(1).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zgogAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ExtensionMethod_Interceptor_3(this AspectGenerator.Tests.TestClassExtension __this__, int value)
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = ExtensionMethod_Interceptor_3_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = ExtensionMethod_Interceptor_3_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.TestCodeExtensions.ExtensionMethod(__this__, value);

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ExtensionMethod_Interceptor_4_MemberInfo        = MethodOf(() => AspectGenerator.Tests.TestCodeExtensions.ExtensionMethod(default(AspectGenerator.Tests.TestStructExtension), default(int)));
		static SCG.Dictionary<string,object?> ExtensionMethod_Interceptor_4_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.TestStructExtension.ExtensionMethod<int>(int).
		/// </summary>
		//
		// Intercepts new TestStructExtension().ExtensionMethod(2).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zssgAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string ExtensionMethod_Interceptor_4(this AspectGenerator.Tests.TestStructExtension __this__, int value)
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = ExtensionMethod_Interceptor_4_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = ExtensionMethod_Interceptor_4_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.TestCodeExtensions.ExtensionMethod(__this__, value);

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 FinallyMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.FinallyMethod());
		static SCG.Dictionary<string,object?> FinallyMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.FinallyMethod().
		/// </summary>
		//
		// Intercepts FinallyMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zgYeAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int FinallyMethod_Interceptor()
		{
			// Aspects.FinallyAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = FinallyMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.FinallyAttribute),
				AspectArguments = FinallyMethod_Interceptor_AspectArguments_0,
			};

			try
			{
				__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.FinallyMethod();
			}
			catch (Exception __ex__)
			{
				__info__0.Exception = __ex__;
				throw;
			}
			finally
			{
				Aspects.FinallyAttribute.OnFinally(__info__0);
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 GenericMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.TestCode.GenericMethod(default(int)));
		static SCG.Dictionary<string,object?> GenericMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		static SCG.Dictionary<string,object?> GenericMethod_Interceptor_AspectArguments_1 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.TestCode.GenericMethod<int>(int).
		/// </summary>
		//
		// Intercepts TestCode.GenericMethod(1).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zk4ZAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string GenericMethod_Interceptor(int value)
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = GenericMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = GenericMethod_Interceptor_AspectArguments_0,
			};

			{
				// Aspects.TestAspect2Attribute
				//
				var __info__1 = new AspectGenerator.InterceptInfo<string>
				{
					MemberInfo      = GenericMethod_Interceptor_MemberInfo,
					AspectType      = typeof(Aspects.TestAspect2Attribute),
					AspectArguments = GenericMethod_Interceptor_AspectArguments_1,
				};

				__info__1.InterceptType = AspectGenerator.InterceptType.OnBeforeCall;
				Aspects.TestAspect2Attribute.OnBeforeCall(__info__1);

				if (__info__1.InterceptResult != AspectGenerator.InterceptResult.Return)
				{
					__info__1.ReturnValue = AspectGenerator.Tests.TestCode.GenericMethod(value);

					__info__1.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
					Aspects.TestAspect2Attribute.OnCall(__info__1);
				}

				__info__0.ReturnValue = __info__1.ReturnValue;
			}

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 GenericMethod_Interceptor_5_MemberInfo        = MethodOf(() => AspectGenerator.Tests.TestCode.GenericMethod(default(System.DateTime)));
		static SCG.Dictionary<string,object?> GenericMethod_Interceptor_5_AspectArguments_0 = new()
		{
		};
		static SCG.Dictionary<string,object?> GenericMethod_Interceptor_5_AspectArguments_1 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.TestCode.GenericMethod<System.DateTime>(System.DateTime).
		/// </summary>
		//
		// Intercepts TestCode.GenericMethod(DateTime.Today).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zmoZAABVbml0VGVzdHMuY3M=")]
		//
		// Intercepts TestCode.GenericMethod(now).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zpMZAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string GenericMethod_Interceptor_5(System.DateTime value)
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = GenericMethod_Interceptor_5_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = GenericMethod_Interceptor_5_AspectArguments_0,
			};

			{
				// Aspects.TestAspect2Attribute
				//
				var __info__1 = new AspectGenerator.InterceptInfo<string>
				{
					MemberInfo      = GenericMethod_Interceptor_5_MemberInfo,
					AspectType      = typeof(Aspects.TestAspect2Attribute),
					AspectArguments = GenericMethod_Interceptor_5_AspectArguments_1,
				};

				__info__1.InterceptType = AspectGenerator.InterceptType.OnBeforeCall;
				Aspects.TestAspect2Attribute.OnBeforeCall(__info__1);

				if (__info__1.InterceptResult != AspectGenerator.InterceptResult.Return)
				{
					__info__1.ReturnValue = AspectGenerator.Tests.TestCode.GenericMethod(value);

					__info__1.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
					Aspects.TestAspect2Attribute.OnCall(__info__1);
				}

				__info__0.ReturnValue = __info__1.ReturnValue;
			}

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 IgnoreCatchMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.IgnoreCatchMethod());
		static SCG.Dictionary<string,object?> IgnoreCatchMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.IgnoreCatchMethod().
		/// </summary>
		//
		// Intercepts IgnoreCatchMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zlUdAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int IgnoreCatchMethod_Interceptor()
		{
			// Aspects.IgnoreCatchAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = IgnoreCatchMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.IgnoreCatchAttribute),
				AspectArguments = IgnoreCatchMethod_Interceptor_AspectArguments_0,
			};

			try
			{
				__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.IgnoreCatchMethod();
			}
			catch (Exception __ex__)
			{
				__info__0.Exception       = __ex__;
				__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

				Aspects.IgnoreCatchAttribute.OnCatch(__info__0);

				if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
					throw;
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 InitMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.InitMethod());
		static SCG.Dictionary<string,object?> InitMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.InitMethod().
		/// </summary>
		//
		// Intercepts InitMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zmMcAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int InitMethod_Interceptor()
		{
			// Aspects.InitAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = InitMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.InitAspectAttribute),
				AspectArguments = InitMethod_Interceptor_AspectArguments_0,
			};

			__info__0 = Aspects.InitAspectAttribute.OnInit(__info__0);

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.InitMethod();

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 InterceptedGenericMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.InterceptedGenericMethod(default(string)));
		static SCG.Dictionary<string,object?> InterceptedGenericMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.InterceptedGenericMethod<string>(string).
		/// </summary>
		//
		// Intercepts InterceptedGenericMethod("Intercepted").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zllIAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string InterceptedGenericMethod_Interceptor(string p)
		{
			// Aspects.LogAttribute(TargetFilter = {"regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.AssemblyFilterTarget\\(\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedMethod\\(System.String\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedGenericMethod<System.String>\\(System.String\\)$", "regex: ^public System.String System.String.Substring\\(System.Int32\\)$"})
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = InterceptedGenericMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.LogAttribute),
				AspectArguments = InterceptedGenericMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.InterceptedGenericMethod(p);

			Aspects.LogAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 InterceptedMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.InterceptedMethod(default(string)));
		static SCG.Dictionary<string,object?> InterceptedMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.InterceptedMethod(string).
		/// </summary>
		//
		// Intercepts InterceptedMethod("Intercepted").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zjdHAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string InterceptedMethod_Interceptor(string str)
		{
			// Aspects.LogAttribute(TargetFilter = {"regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.AssemblyFilterTarget\\(\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedMethod\\(System.String\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedGenericMethod<System.String>\\(System.String\\)$", "regex: ^public System.String System.String.Substring\\(System.Int32\\)$"})
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = InterceptedMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.LogAttribute),
				AspectArguments = InterceptedMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.InterceptedMethod(str);

			Aspects.LogAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 LiteralArgsMethod_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).LiteralArgsMethod());
		static SCG.Dictionary<string,object?> LiteralArgsMethod_Interceptor_AspectArguments_0 = new()
		{
			["Text"] = "quote\" slash\\ newline\n",
			["Character"] = '\'',
			["Number"] = 1.25d,
			["Single"] = 3.5f,
			["Kind"] = (Aspects.LiteralKind)1,
			["Values"] = new string[] { "a\"b", "c\\d", "e\nf" },
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.LiteralArgsMethod().
		/// </summary>
		//
		// Intercepts LiteralArgsMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zpQ6AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string LiteralArgsMethod_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.LiteralArgsAttribute(Text = "quote\" slash\\ newline\n", Character = '\'', Number = 1.25, Single = 3.5, Kind = Aspects.LiteralKind.Second, Values = {"a\"b", "c\\d", "e\nf"})
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = LiteralArgsMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.LiteralArgsAttribute),
				AspectArguments = LiteralArgsMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = __this__.LiteralArgsMethod();

			Aspects.LiteralArgsAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 MemberMethod_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).MemberMethod(default(int)));
		static SCG.Dictionary<string,object?> MemberMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.MemberMethod(int).
		/// </summary>
		//
		// Intercepts MemberMethod(1).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zs8eAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int MemberMethod_Interceptor(this AspectGenerator.Tests.UnitTests __this__, int n)
		{
			// Aspects.FinallyAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = MemberMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.FinallyAttribute),
				AspectArguments = MemberMethod_Interceptor_AspectArguments_0,
			};

			try
			{
				__info__0.ReturnValue = __this__.MemberMethod(n);
			}
			catch (Exception __ex__)
			{
				__info__0.Exception = __ex__;
				throw;
			}
			finally
			{
				Aspects.FinallyAttribute.OnFinally(__info__0);
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 OnCall_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.OnCallObject).OnCall(default(int)));
		static SCG.Dictionary<string,object?> OnCall_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.OnCallObject.OnCall(int).
		/// </summary>
		//
		// Intercepts obj.OnCall(2).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zjhLAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int OnCall_Interceptor(this AspectGenerator.Tests.OnCallObject __this__, int n)
		{
			var __return__ = AspectGenerator.Tests.OnCallAttribute.OnCall(__this__, n);

			return __return__;
		}

		static SR. MemberInfo                 OnCallTestMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.OnCallTestMethod(default(int)));
		static SCG.Dictionary<string,object?> OnCallTestMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.OnCallTestMethod(int).
		/// </summary>
		//
		// Intercepts OnCallTestMethod(2).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/znpKAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int OnCallTestMethod_Interceptor(int n)
		{
			var __return__ = AspectGenerator.Tests.OnCallAttribute.OnCall(n);

			return __return__;
		}

		static SR. MemberInfo                 OrderedMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.OrderedMethod());
		static SCG.Dictionary<string,object?> OrderedMethod_Interceptor_AspectArguments_0 = new()
		{
			["Order"] = 1,
			["Value"] = "2",
		};
		static SCG.Dictionary<string,object?> OrderedMethod_Interceptor_AspectArguments_1 = new()
		{
			["Order"] = 2,
			["Value"] = "1",
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.OrderedMethod().
		/// </summary>
		//
		// Intercepts OrderedMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/ztI9AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string OrderedMethod_Interceptor()
		{
			// Aspects.OrderedAttribute(Order = 1, Value = "2")
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = OrderedMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.OrderedAttribute),
				AspectArguments = OrderedMethod_Interceptor_AspectArguments_0,
			};

			{
				// Aspects.OrderedAttribute(Order = 2, Value = "1")
				//
				var __info__1 = new AspectGenerator.InterceptInfo<string>
				{
					MemberInfo      = OrderedMethod_Interceptor_MemberInfo,
					AspectType      = typeof(Aspects.OrderedAttribute),
					AspectArguments = OrderedMethod_Interceptor_AspectArguments_1,
					PreviousInfo    = __info__0
				};

				__info__1.ReturnValue = AspectGenerator.Tests.UnitTests.OrderedMethod();

				Aspects.OrderedAttribute.OnAfterCall(__info__1);

				__info__0.ReturnValue = __info__1.ReturnValue;
			}

			Aspects.OrderedAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 OrderedMethod2_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.OrderedMethod2());
		static SCG.Dictionary<string,object?> OrderedMethod2_Interceptor_AspectArguments_0 = new()
		{
			["Order"] = 2,
			["Value"] = "2",
		};
		static SCG.Dictionary<string,object?> OrderedMethod2_Interceptor_AspectArguments_1 = new()
		{
			["Order"] = 3,
			["Value"] = "3",
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.OrderedMethod2().
		/// </summary>
		//
		// Intercepts OrderedMethod2().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zhQ+AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static int OrderedMethod2_Interceptor()
		{
			// Aspects.OrderedAttribute(Order = 2, Value = "2")
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = OrderedMethod2_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.OrderedAttribute),
				AspectArguments = OrderedMethod2_Interceptor_AspectArguments_0,
			};

			{
				// Aspects.OrderedAttribute(Order = 3, Value = "3")
				//
				var __info__1 = new AspectGenerator.InterceptInfo<int>
				{
					MemberInfo      = OrderedMethod2_Interceptor_MemberInfo,
					AspectType      = typeof(Aspects.OrderedAttribute),
					AspectArguments = OrderedMethod2_Interceptor_AspectArguments_1,
					PreviousInfo    = __info__0
				};

				__info__1.ReturnValue = AspectGenerator.Tests.UnitTests.OrderedMethod2();

				Aspects.OrderedAttribute.OnAfterCall(__info__1);

				__info__0.ReturnValue = __info__1.ReturnValue;
			}

			Aspects.OrderedAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ReturnVoidMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.ReturnVoidMethod());
		static SCG.Dictionary<string,object?> ReturnVoidMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		static SCG.Dictionary<string,object?> ReturnVoidMethod_Interceptor_AspectArguments_1 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ReturnVoidMethod().
		/// </summary>
		//
		// Intercepts ReturnVoidMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/ztoaAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static void ReturnVoidMethod_Interceptor()
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<AspectGenerator.Void>
			{
				MemberInfo      = ReturnVoidMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = ReturnVoidMethod_Interceptor_AspectArguments_0,
			};

			{
				// Aspects.TestAspect2Attribute
				//
				var __info__1 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
				{
					MemberInfo      = ReturnVoidMethod_Interceptor_MemberInfo,
					AspectType      = typeof(Aspects.TestAspect2Attribute),
					AspectArguments = ReturnVoidMethod_Interceptor_AspectArguments_1,
				};

				__info__1.InterceptType = AspectGenerator.InterceptType.OnBeforeCall;
				Aspects.TestAspect2Attribute.OnBeforeCall(__info__1);

				if (__info__1.InterceptResult != AspectGenerator.InterceptResult.Return)
				{
					AspectGenerator.Tests.UnitTests.ReturnVoidMethod();

					__info__1.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
					Aspects.TestAspect2Attribute.OnCall(__info__1);
				}

				__info__0.ReturnValue = __info__1.ReturnValue;
			}

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);
		}

		static SR. MemberInfo                 StaticMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.StaticMethod());
		static SCG.Dictionary<string,object?> StaticMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.StaticMethod().
		/// </summary>
		//
		// Intercepts StaticMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zmUWAABVbml0VGVzdHMuY3M=")]
		//
		// Intercepts StaticMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zn0WAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string StaticMethod_Interceptor()
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = StaticMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = StaticMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.StaticMethod();

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 StaticMethod_Interceptor_6_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.StaticMethod(default(string)));
		static SCG.Dictionary<string,object?> StaticMethod_Interceptor_6_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.StaticMethod(string).
		/// </summary>
		//
		// Intercepts StaticMethod("John").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zpYWAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string StaticMethod_Interceptor_6(string name)
		{
			// Aspects.TestAspectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = StaticMethod_Interceptor_6_MemberInfo,
				AspectType      = typeof(Aspects.TestAspectAttribute),
				AspectArguments = StaticMethod_Interceptor_6_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.StaticMethod(name);

			__info__0.InterceptType = AspectGenerator.InterceptType.OnAfterCall;
			Aspects.TestAspectAttribute.OnAfterCall(ref __info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 Substring_Interceptor_MemberInfo        = MethodOf(() => default(string).Substring(default(int)));
		static SCG.Dictionary<string,object?> Substring_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts string.Substring(int).
		/// </summary>
		//
		// Intercepts "test string".Substring(5).
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zpBJAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string Substring_Interceptor(this string __this__, int startIndex)
		{
			// Aspects.LogAttribute(TargetFilter = {"regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.AssemblyFilterTarget\\(\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedMethod\\(System.String\\)$", "regex: ^public static System.String AspectGenerator\\.Tests\\.UnitTests\\.InterceptedGenericMethod<System.String>\\(System.String\\)$", "regex: ^public System.String System.String.Substring\\(System.Int32\\)$"})
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = Substring_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.LogAttribute),
				AspectArguments = Substring_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = __this__.Substring(startIndex);

			Aspects.LogAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 TestMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.ClassLibrary.TestClass.TestMethod(default(string)));
		static SCG.Dictionary<string,object?> TestMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.ClassLibrary.TestClass.TestMethod(string).
		/// </summary>
		//
		// Intercepts ClassLibrary.TestClass.TestMethod("Test").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zg1GAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string TestMethod_Interceptor(string str)
		{
			// Aspects.CrossProjectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = TestMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.CrossProjectAttribute),
				AspectArguments = TestMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.ClassLibrary.TestClass.TestMethod(str);

			Aspects.CrossProjectAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 TypeFilterTarget_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.Tests.UnitTests.TypeFilterTarget());
		static SCG.Dictionary<string,object?> TypeFilterTarget_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.TypeFilterTarget().
		/// </summary>
		//
		// Intercepts TypeFilterTarget().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zpsYAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string TypeFilterTarget_Interceptor()
		{
			// Aspects.LogAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = TypeFilterTarget_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.LogAttribute),
				AspectArguments = TypeFilterTarget_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.Tests.UnitTests.TypeFilterTarget();

			Aspects.LogAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 UsingMethod_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).UsingMethod());
		static SCG.Dictionary<string,object?> UsingMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.UsingMethod().
		/// </summary>
		//
		// Intercepts UsingMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zmo7AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static string UsingMethod_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.UsingAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = UsingMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.UsingAttribute),
				AspectArguments = UsingMethod_Interceptor_AspectArguments_0,
			};

			using (Aspects.UsingAttribute.OnUsing(ref __info__0))
			{
				__info__0.ReturnValue = __this__.UsingMethod();
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 UsingMethodAsync_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).UsingMethodAsync());
		static SCG.Dictionary<string,object?> UsingMethodAsync_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.UsingMethodAsync().
		/// </summary>
		//
		// Intercepts UsingMethodAsync().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zjw8AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static async System.Threading.Tasks.Task<string> UsingMethodAsync_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.UsingAttribute
			//
			var __info__0 = new AspectGenerator.InterceptData<string>
			{
				MemberInfo      = UsingMethodAsync_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.UsingAttribute),
				AspectArguments = UsingMethodAsync_Interceptor_AspectArguments_0,
			};

			await using (Aspects.UsingAttribute.OnUsingAsync(ref __info__0))
			{
				__info__0.ReturnValue = await __this__.UsingMethodAsync();
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ValueTaskMethodAsync_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).ValueTaskMethodAsync());
		static SCG.Dictionary<string,object?> ValueTaskMethodAsync_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ValueTaskMethodAsync().
		/// </summary>
		//
		// Intercepts ValueTaskMethodAsync().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zmcuAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static async System.Threading.Tasks.ValueTask ValueTaskMethodAsync_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.ValueTaskFlowAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = ValueTaskMethodAsync_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ValueTaskFlowAttribute),
				AspectArguments = ValueTaskMethodAsync_Interceptor_AspectArguments_0,
			};

			await using (Aspects.ValueTaskFlowAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					await Aspects.ValueTaskFlowAttribute.OnBeforeCallAsync(__info__0);

					if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
					{
						__this__.ValueTaskMethodAsync();

						await Aspects.ValueTaskFlowAttribute.OnAfterCallAsync(__info__0);
					}
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

					await Aspects.ValueTaskFlowAttribute.OnCatchAsync(__info__0);

					if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
						throw;
				}
				finally
				{
					await Aspects.ValueTaskFlowAttribute.OnFinallyAsync(__info__0);
				}
			}
		}

		static SR. MemberInfo                 ValueTaskMethodAsync2_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).ValueTaskMethodAsync2());
		static SCG.Dictionary<string,object?> ValueTaskMethodAsync2_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ValueTaskMethodAsync2().
		/// </summary>
		//
		// Intercepts ValueTaskMethodAsync2().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/zn8xAABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static async System.Threading.Tasks.ValueTask<int> ValueTaskMethodAsync2_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.ValueTaskFlowAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = ValueTaskMethodAsync2_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ValueTaskFlowAttribute),
				AspectArguments = ValueTaskMethodAsync2_Interceptor_AspectArguments_0,
			};

			await using (Aspects.ValueTaskFlowAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					await Aspects.ValueTaskFlowAttribute.OnBeforeCallAsync(__info__0);

					if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
					{
						__info__0.ReturnValue = await __this__.ValueTaskMethodAsync2();

						await Aspects.ValueTaskFlowAttribute.OnAfterCallAsync(__info__0);
					}
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

					await Aspects.ValueTaskFlowAttribute.OnCatchAsync(__info__0);

					if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
						throw;
				}
				finally
				{
					await Aspects.ValueTaskFlowAttribute.OnFinallyAsync(__info__0);
				}
			}

			return __info__0.ReturnValue;
		}

		static SR. MemberInfo                 ValueTaskThrowMethodAsync_Interceptor_MemberInfo        = MethodOf(() => default(AspectGenerator.Tests.UnitTests).ValueTaskThrowMethodAsync());
		static SCG.Dictionary<string,object?> ValueTaskThrowMethodAsync_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.Tests.UnitTests.ValueTaskThrowMethodAsync().
		/// </summary>
		//
		// Intercepts ValueTaskThrowMethodAsync().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GXCQ5HXiIYk65dq674q/ztY0AABVbml0VGVzdHMuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		[System.Diagnostics.DebuggerStepThrough]
		public static async System.Threading.Tasks.ValueTask<int> ValueTaskThrowMethodAsync_Interceptor(this AspectGenerator.Tests.UnitTests __this__)
		{
			// Aspects.ValueTaskFlowAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<int>
			{
				MemberInfo      = ValueTaskThrowMethodAsync_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.ValueTaskFlowAttribute),
				AspectArguments = ValueTaskThrowMethodAsync_Interceptor_AspectArguments_0,
			};

			await using (Aspects.ValueTaskFlowAttribute.OnUsingAsync(__info__0))
			{
				try
				{
					await Aspects.ValueTaskFlowAttribute.OnBeforeCallAsync(__info__0);

					if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
					{
						__info__0.ReturnValue = await __this__.ValueTaskThrowMethodAsync();

						await Aspects.ValueTaskFlowAttribute.OnAfterCallAsync(__info__0);
					}
				}
				catch (Exception __ex__)
				{
					__info__0.Exception = __ex__;
					__info__0.InterceptResult = AspectGenerator.InterceptResult.ReThrow;

					await Aspects.ValueTaskFlowAttribute.OnCatchAsync(__info__0);

					if (__info__0.InterceptResult == AspectGenerator.InterceptResult.ReThrow)
						throw;
				}
				finally
				{
					await Aspects.ValueTaskFlowAttribute.OnFinallyAsync(__info__0);
				}
			}

			return __info__0.ReturnValue;
		}
	}
}
