// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace AspectGenerator
{
	/// <summary>
	/// Configures AspectGenerator for the current assembly.
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
	sealed class AspectGeneratorOptionsAttribute : Attribute
	{
		public bool    GenerateApi                   { get; set; } = true;
		public bool    GenerateInterceptors          { get; set; }
		public bool    PublicApi                     { get; set; }
		public bool    DebuggerStepThrough           { get; set; }
		public string? InterceptorsNamespace         { get; set; }
	}
}
