// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		static readonly Lazy<SR.MemberInfo> StaticMethod_Interceptor_MemberInfo = new(() => MethodOf(() => ClassLibrary.Class1.StaticMethod()));
		static readonly Lazy<global::AspectLibrary.ConsoleLogAttribute> StaticMethod_Interceptor_Aspect_0 = new(() => new global::AspectLibrary.ConsoleLogAttribute());
		//
		/// <summary>
		/// Intercepts ClassLibrary.Class1.StaticMethod().
		/// </summary>
		//
		// Intercepts StaticMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "AncmHYx311mIhEhZRSZqHJMAAABDbGFzczEuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void StaticMethod_Interceptor()
		{
			// AspectLibrary.ConsoleLogAttribute
			//
			var __aspect__0 = StaticMethod_Interceptor_Aspect_0.Value;
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = StaticMethod_Interceptor_MemberInfo.Value,
				AspectType      = typeof(AspectLibrary.ConsoleLogAttribute),
				Aspect          = __aspect__0,
			};

			AspectLibrary.ConsoleLogAttribute.OnBeforeCall(__info__0);

			if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
			{
				ClassLibrary.Class1.StaticMethod();

				AspectLibrary.ConsoleLogAttribute.OnAfterCall(__info__0);
			}
		}
	}
}
