// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		private static class StaticMethod_Interceptor_State
		{
			internal static readonly global::System.Reflection.MemberInfo TargetMethod = MethodOf(() => ClassLibrary.Class1.StaticMethod());

			internal static readonly global::AspectLibrary.ConsoleLogAttribute Aspect0 = new global::AspectLibrary.ConsoleLogAttribute();

			static StaticMethod_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts ClassLibrary.Class1.StaticMethod().
		/// </summary>
		//
		// Intercepts StaticMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "AncmHYx311mIhEhZRSZqHJMAAABDbGFzczEuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void StaticMethod_Interceptor()
		{
			// AspectLibrary.ConsoleLogAttribute
			//
			var __targetMethod__ = StaticMethod_Interceptor_State.TargetMethod;

			var __aspect__0 = StaticMethod_Interceptor_State.Aspect0;
			var __info__0   = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo = __targetMethod__,
				Aspect     = __aspect__0,
			};

			AspectLibrary.ConsoleLogAttribute.OnBeforeCall(__info__0);

			if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
			{
				ClassLibrary.Class1.StaticMethod();

				AspectLibrary.ConsoleLogAttribute.OnAfterCall(__info__0);
			}
		}
	}
}
