// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace MultiProjectAspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		static readonly Lazy<SR.MemberInfo> TestMethod_Interceptor_MemberInfo = new(() => MethodOf(() => ClassLibrary.TestClass.TestMethod(default(string))));
		static readonly Lazy<global::Aspects.CrossProjectAttribute> TestMethod_Interceptor_Aspect_0 = new(() => new global::Aspects.CrossProjectAttribute());
		//
		/// <summary>
		/// Intercepts ClassLibrary.TestClass.TestMethod(string).
		/// </summary>
		//
		// Intercepts ClassLibrary.TestClass.TestMethod("Test").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "GiHAiXc0FWJy325lBXAFteQAAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static string TestMethod_Interceptor(string str)
		{
			// Aspects.CrossProjectAttribute
			//
			var __aspect__0 = TestMethod_Interceptor_Aspect_0.Value;
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = TestMethod_Interceptor_MemberInfo.Value,
				AspectType      = typeof(Aspects.CrossProjectAttribute),
				Aspect          = __aspect__0,
			};

			__info__0.ReturnValue = ClassLibrary.TestClass.TestMethod(str);

			Aspects.CrossProjectAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}
	}
}
