using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace AspectGenerator
{
	[Generator(LanguageNames.CSharp)]
	public class AspectSourceGenerator : IIncrementalGenerator
	{
		const string AspectGeneratorOptionsAttributeText =
			"""
			// <auto-generated/>
			#pragma warning disable
			#nullable enable

			using System;

			namespace AspectGenerator
			{
				/// <summary>
				/// Configures AspectGenerator for the current assembly.
				/// </summary>
				[AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
				sealed class AspectGeneratorOptionsAttribute : Attribute
				{
					public bool    GenerateApi           { get; set; } = true;
					public bool    PublicApi             { get; set; }
					public bool    DebuggerStepThrough   { get; set; }
					public string? InterceptorsNamespace { get; set; }
				}
			}

			""";

		static string GenerateAspectApiText(bool publicApi)
		{
			var visibility = publicApi ? "public " : "";

			return
				$$"""
				// <auto-generated/>
				#pragma warning disable
				#nullable enable

				using System;

				namespace AspectGenerator
				{
				/// <summary>
				/// <para>Defines an aspect.</para>
				/// <para>Create a new attribute decorated with this attribute to define an aspect.</para>
				/// </summary>
				[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
				{{visibility}}sealed class AspectAttribute : Attribute
				{
					public string?   OnInit            { get; set; }
					public string?   OnUsing           { get; set; }
					public string?   OnUsingAsync      { get; set; }
					public string?   OnBeforeCall      { get; set; }
					public string?   OnBeforeCallAsync { get; set; }
					public string?   OnCall            { get; set; }
					public string?   OnAfterCall       { get; set; }
					public string?   OnAfterCallAsync  { get; set; }
					public string?   OnCatch           { get; set; }
					public string?   OnCatchAsync      { get; set; }
					public string?   OnFinally         { get; set; }
					public string?   OnFinallyAsync    { get; set; }
					public string[]? InterceptMethods  { get; set; }
					public bool      UseInterceptType  { get; set; }
					public bool      PassArguments     { get; set; }
					public bool      UseInterceptData  { get; set; }
				}

				{{visibility}}enum InterceptType
				{
					OnInit,
					OnUsing,
					OnBeforeCall,
					OnAfterCall,
					OnCatch,
					OnFinally
				}

				{{visibility}}enum InterceptResult
				{
					Continue,
					Return,
					ReThrow     = Continue,
					IgnoreThrow = Return
				}

				{{visibility}}struct Void
				{
				}

				{{visibility}}partial class InterceptInfo
				{
					public object?         Tag;
					public InterceptType   InterceptType;
					public InterceptResult InterceptResult;
					public Exception?      Exception;

					public InterceptInfo?                                        PreviousInfo;
					public System.Reflection.MemberInfo                          MemberInfo;
					public object?[]?                                            MethodArguments;
					public Type                                                  AspectType;
					public System.Collections.Generic.Dictionary<string,object?> AspectArguments;
				}

				{{visibility}}partial class InterceptInfo<T> : InterceptInfo
				{
					public T ReturnValue;
				}

				{{visibility}}partial struct InterceptData<T>
				{
					public object?         Tag;
					public InterceptType   InterceptType;
					public InterceptResult InterceptResult;
					public Exception?      Exception;

					public InterceptInfo<T>?                                     PreviousInfo;
					public System.Reflection.MemberInfo                          MemberInfo;
					public object?[]?                                            MethodArguments;
					public Type                                                  AspectType;
					public System.Collections.Generic.Dictionary<string,object?> AspectArguments;

					public T ReturnValue;
				}
			}

			""";
		}

		class Options
		{
			public bool?   GenerateApi;
			public bool?   PublicApi;
			public bool?   DebuggerStepThrough;
			public string? InterceptorsNamespace;
			public string? AllowedInterceptorsNamespaces;
		}

		record AttributeInfo(
			AttributeData?    AttributeData,
			INamedTypeSymbol  AttributeClass,
			AttributeData?    AspectAttributeData,
			AttributeSyntax?  AspectAttributeSyntax,
			SemanticModel?    AspectSemanticModel)
		{
		}

		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
#if DEBUG && TRUE1
			if (!System.Diagnostics.Debugger.IsAttached)
			{
				System.Diagnostics.Debugger.Launch();
			}
#endif

			context.RegisterPostInitializationOutput(ctx => ctx.AddSource("AspectGeneratorOptionsAttribute.g.cs", SourceText.From(AspectGeneratorOptionsAttributeText, Encoding.UTF8)));

			var attributes = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } c && c.AttributeLists
						.SelectMany(static l => l.Attributes)
						.Any(static a => IsAspectAttributeName(a.Name.ToString())),
					transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
				.Collect();

			var options = context.AnalyzerConfigOptionsProvider.Select((c, _) =>
				new Options
				{
					GenerateApi                   = GetBoolProperty(c.GlobalOptions, "build_property.AspectGeneratorGenerateApi"),
					PublicApi                     = GetBoolProperty(c.GlobalOptions, "build_property.AspectGeneratorPublicApi"),
					DebuggerStepThrough           = GetBoolProperty(c.GlobalOptions, "build_property.AspectGeneratorDebuggerStepThrough"),
					InterceptorsNamespace         = c.GlobalOptions.TryGetValue("build_property.AspectGeneratorInterceptorsNamespace", out var ns) ? ns : null,
					AllowedInterceptorsNamespaces = c.GlobalOptions.TryGetValue("build_property.InterceptorsNamespaces", out var namespaces) ? namespaces : null,
				});

			context.RegisterImplementationSourceOutput(context.CompilationProvider.Combine(options.Combine(attributes)), Implement);
		}

		static void Implement(SourceProductionContext spc, (Compilation Left, (Options Left, ImmutableArray<ClassDeclarationSyntax> Right) Right) data)
		{
			var compilation = data.Left;
			var options     = ResolveOptions(compilation, data.Right.Left);
			var attrs       = data.Right.Right;

			if (options.GenerateApi is not false)
				spc.AddSource("AspectAttribute.g.cs", SourceText.From(GenerateAspectApiText(options.PublicApi is true), Encoding.UTF8));

			ReportMissingInterceptorsNamespace(spc, options);

			var aspectAttributes = new Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)>(SymbolEqualityComparer.Default);

			foreach (var a in attrs)
			{
				var semanticModel = compilation.GetSemanticModel(a.SyntaxTree);

				if (semanticModel.GetDeclaredSymbol(a, spc.CancellationToken) is not {} symbol)
					continue;

				foreach (var attribute in a.AttributeLists.SelectMany(static l => l.Attributes))
				{
					if (!IsAspectAttributeName(attribute.Name.ToString()))
						continue;

					aspectAttributes[symbol] = (attribute, semanticModel);
					break;
				}
			}

			ValidateAspectHooks(spc, aspectAttributes);

			var aspectedMethods  = new List<(InvocationExpressionSyntax inv,IMethodSymbol method,List<AttributeInfo> attributes)>();
			var methodDic        = new Dictionary<IMethodSymbol,List<AttributeInfo>>(SymbolEqualityComparer.Default);
			var interceptedDic   = new Dictionary<string,List<AttributeInfo>>();

			foreach (var a in aspectAttributes)
			{
				foreach (var arg in GetAspectArguments(a.Value.Syntax, a.Value.SemanticModel))
				{
					if (arg is { Key: "InterceptMethods", Value: object?[] methods })
					{
						foreach (var m in methods)
						{
							if (m is string s)
							{
								var ai = new AttributeInfo(null, (INamedTypeSymbol)a.Key, null, a.Value.Syntax, a.Value.SemanticModel);

								if (interceptedDic.ContainsKey(s))
									interceptedDic[s].Add(ai);
								else
									interceptedDic[s] = [ai];
							}
						}
					}
				}
			}

			foreach (var tree in compilation.SyntaxTrees)
			{
				var semantic = compilation.GetSemanticModel(tree);

				// Scan the semantic tree...
				//
				foreach (var node in tree.GetRoot(spc.CancellationToken).DescendantNodes())
				{
					// .. to find an invocation...
					//
					if (node.IsKind(SyntaxKind.InvocationExpression))
					{
						var info = semantic.GetSymbolInfo(node, spc.CancellationToken);

						// .. of a method...
						//
						if (info.Symbol is IMethodSymbol method)
						{
							if (!methodDic.TryGetValue(method, out var attributes))
							{
								attributes = new();

								var methodAttributes = method.GetAttributes();

								// .. decorated with any Aspect attribute...
								//
								if (methodAttributes.Length > 0)
								{
									foreach (var ma in methodAttributes)
									{
										// .. if attribute is defined in the compiling assembly...
										//
										if (ma.AttributeClass is not null && aspectAttributes.TryGetValue(ma.AttributeClass, out var aspectAttribute))
										{
											attributes.Add(new AttributeInfo(ma, ma.AttributeClass, null, aspectAttribute.Syntax, aspectAttribute.SemanticModel));
										}
										// .. or somewhere else.
										else if (ma.AttributeClass?.GetAttributes().FirstOrDefault(aa => aa is { AttributeClass : { ContainingNamespace.Name : "AspectGenerator", Name : "AspectAttribute" }}) is {} externalAspectAttributeData)
										{
											attributes.Add(new AttributeInfo(ma, ma.AttributeClass!, externalAspectAttributeData, null, null));
										}
									}
								}

								if (interceptedDic.TryGetValue(method.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat), out var mm))
									attributes.AddRange(mm);

								methodDic[method] = attributes.Distinct().ToList();
							}

							if (attributes.Count > 0)
								aspectedMethods.Add(((InvocationExpressionSyntax)node, method, attributes));
						}
					}

					if (spc.CancellationToken.IsCancellationRequested)
						break;
				}

				if (spc.CancellationToken.IsCancellationRequested)
					break;
			}

			if (aspectedMethods.Count == 0 || spc.CancellationToken.IsCancellationRequested)
				return;

			GenerateSource(spc, compilation, options, aspectedMethods);
		}

		static bool? GetBoolProperty(AnalyzerConfigOptions options, string name)
		{
			if (!options.TryGetValue(name, out var value))
				return null;

			return bool.TryParse(value, out var result) ? result : null;
		}

		static Options ResolveOptions(Compilation compilation, Options msBuildOptions)
		{
			var result = new Options
			{
				GenerateApi                   = msBuildOptions.GenerateApi,
				PublicApi                     = msBuildOptions.PublicApi,
				DebuggerStepThrough           = msBuildOptions.DebuggerStepThrough,
				InterceptorsNamespace         = msBuildOptions.InterceptorsNamespace,
				AllowedInterceptorsNamespaces = msBuildOptions.AllowedInterceptorsNamespaces,
			};

			var attr = compilation.Assembly.GetAttributes().FirstOrDefault(a =>
				a.AttributeClass is { ContainingNamespace.Name: "AspectGenerator", Name: "AspectGeneratorOptionsAttribute" });

			if (attr is null)
				return result;

			foreach (var arg in attr.NamedArguments)
			{
				switch (arg.Key)
				{
					case "GenerateApi" when arg.Value.Value is bool generateApi:
						result.GenerateApi = generateApi;
						break;
					case "PublicApi" when arg.Value.Value is bool publicApi:
						result.PublicApi = publicApi;
						break;
					case "DebuggerStepThrough" when arg.Value.Value is bool debuggerStepThrough:
						result.DebuggerStepThrough = debuggerStepThrough;
						break;
					case "InterceptorsNamespace" when arg.Value.Value is string interceptorsNamespace:
						result.InterceptorsNamespace = interceptorsNamespace;
						break;
				}
			}

			return result;
		}

		static void ReportMissingInterceptorsNamespace(SourceProductionContext spc, Options options)
		{
			var interceptorsNamespace = string.IsNullOrWhiteSpace(options.InterceptorsNamespace) ? "AspectGenerator" : options.InterceptorsNamespace!;

			if (string.IsNullOrWhiteSpace(options.AllowedInterceptorsNamespaces))
				return;

			var namespaces = options.AllowedInterceptorsNamespaces!
				.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
				.Select(static n => n.Trim());

			if (namespaces.Contains(interceptorsNamespace, StringComparer.Ordinal))
				return;

			var descriptor = new DiagnosticDescriptor(
				"AG0004",
				"AspectGenerator",
				$"Generated interceptors namespace '{interceptorsNamespace}' is not listed in the InterceptorsNamespaces MSBuild property.",
				"AspectGenerator",
				DiagnosticSeverity.Warning,
				true);

			spc.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeInfo attribute)
		{
			if (attribute.AspectAttributeData is {} aspectAttributeData)
				return GetAspectArguments(aspectAttributeData);

			if (attribute is { AspectAttributeSyntax: {} syntax, AspectSemanticModel: {} semanticModel })
				return GetAspectArguments(syntax, semanticModel);

			return [];
		}

		static void ValidateAspectHooks(SourceProductionContext spc, Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes)
		{
			foreach (var item in aspectAttributes)
			{
				var symbol          = item.Key;
				var aspectAttribute = item.Value;

				if (symbol is not INamedTypeSymbol aspectClass)
					continue;

				foreach (var arg in aspectAttribute.Syntax.ArgumentList?.Arguments ?? default)
				{
					if (arg.NameEquals is null || !IsHookName(arg.NameEquals.Name.Identifier.ValueText))
						continue;

					if (GetAttributeArgumentValue(arg.Expression, aspectAttribute.SemanticModel) is not string hookName || string.IsNullOrWhiteSpace(hookName))
						continue;

					var methods = aspectClass.GetMembers(hookName).OfType<IMethodSymbol>().ToArray();

					if (methods.Length == 0)
					{
						spc.ReportDiagnostic(
							Diagnostic.Create(
								"AG0101",
								"AspectGenerator",
								$"Aspect hook method '{hookName}' was not found on aspect type '{aspectClass.ToDisplayString()}'.",
								DiagnosticSeverity.Error,
								DiagnosticSeverity.Error,
								true,
								0,
								location: arg.Expression.GetLocation()));
					}
					else if (!methods.Any(static m => m.IsStatic))
					{
						spc.ReportDiagnostic(
							Diagnostic.Create(
								"AG0102",
								"AspectGenerator",
								$"Aspect hook method '{hookName}' on aspect type '{aspectClass.ToDisplayString()}' must be static.",
								DiagnosticSeverity.Error,
								DiagnosticSeverity.Error,
								true,
								0,
								location: arg.Expression.GetLocation()));
					}
				}
			}
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeData attribute)
		{
			return attribute.NamedArguments.Select(static arg => (
				arg.Key,
				arg.Value.Kind == TypedConstantKind.Array ? arg.Value.Values.Select(static v => v.Value).ToArray() : arg.Value.Value));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeSyntax attribute, SemanticModel semanticModel)
		{
			foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
				if (arg.NameEquals is not null)
					yield return (arg.NameEquals.Name.Identifier.ValueText, GetAttributeArgumentValue(arg.Expression, semanticModel));
		}

		static object? GetAttributeArgumentValue(ExpressionSyntax expression, SemanticModel semanticModel)
		{
			if (expression is ImplicitArrayCreationExpressionSyntax { Initializer.Expressions: var implicitValues })
				return implicitValues.Select(e => semanticModel.GetConstantValue(e).Value).ToArray();

			if (expression is ArrayCreationExpressionSyntax { Initializer.Expressions: var arrayValues })
				return arrayValues.Select(e => semanticModel.GetConstantValue(e).Value).ToArray();

			if (expression is CollectionExpressionSyntax { Elements: var elements })
				return elements
					.OfType<ExpressionElementSyntax>()
					.Select(e => semanticModel.GetConstantValue(e.Expression).Value)
					.ToArray();

			return semanticModel.GetConstantValue(expression).Value;
		}

		static bool IsAspectAttributeName(string name)
		{
			return name is "Aspect" or "AspectAttribute" or "AspectGenerator.Aspect" or "AspectGenerator.AspectAttribute";
		}

		static bool IsHookName(string name)
		{
			return name is
				"OnInit"            or
				"OnUsing"           or
				"OnUsingAsync"      or
				"OnBeforeCall"      or
				"OnBeforeCallAsync" or
				"OnCall"            or
				"OnAfterCall"       or
				"OnAfterCallAsync"  or
				"OnCatch"           or
				"OnCatchAsync"      or
				"OnFinally"         or
				"OnFinallyAsync";
		}

		static void GenerateSource(SourceProductionContext spc, Compilation compilation, Options options, List<(InvocationExpressionSyntax inv,IMethodSymbol method,List<AttributeInfo> attributes)> aspectedMethods)
		{
			// Generate source. One file for all the interceptors.
			// Interceptors.g.cs
			//
			var sb = new StringBuilder(
				$$"""
				// <auto-generated/>
				#pragma warning disable
				#nullable enable

				using System;

				using SR  = System.Reflection;
				using SLE = System.Linq.Expressions;
				using SCG = System.Collections.Generic;

				namespace System.Runtime.CompilerServices
				{
					[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
					file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
					{
					}
				}

				namespace {{(string.IsNullOrWhiteSpace(options.InterceptorsNamespace) ? "AspectGenerator" : options.InterceptorsNamespace)}}
				{
					using AspectGenerator = AspectGenerator;

					static partial class Interceptors
					{
						static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
						{
							return expr switch
							{
								SLE.MethodCallExpression mc => mc.Method,
								_                           => throw new InvalidOperationException()
							};
						}

						static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
						static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);


				""");

			var nameCounter = 0;
			var nameSet     = new HashSet<string>();

			string GetInterceptorName(string methodName)
			{
				if (nameSet.Contains(methodName))
					return GetInterceptorName($"{methodName}_{++nameCounter}");

				nameSet.Add(methodName);
				return methodName;
			}

			foreach (var m in aspectedMethods.GroupBy(m => m.method, SymbolEqualityComparer.Default).OrderBy(m => m.Key!.Name))
			{
				var method          = (IMethodSymbol)m.Key!;
				var interceptorName = GetInterceptorName($"{method.Name}_Interceptor");
				var methods         = m.ToList();
				var attributes      = methods[0].attributes;

				if (attributes.Any(a => a.AttributeData?.NamedArguments.Any(na => na.Key == "Order") is true))
				{
					attributes =
						(
							from a in attributes
							let o = a.AttributeData?.NamedArguments.Select(na => (KeyValuePair<string,TypedConstant>?)na).FirstOrDefault(na => na!.Value.Key == "Order")
							let n = o is null ? int.MaxValue : o.Value.Value.Value switch
							{
								string s => int.TryParse(s, out var n) ? n : null,
								int    n => (int?)n,
								_        => null
							}
							orderby n
							select a
						)
						.ToList();
				}

				foreach (var p in method.Parameters)
				{
					switch (p.RefKind)
					{
						case RefKind.Ref :
						case RefKind.Out :
						case RefKind.In  :
							sb.AppendLine(
								$$"""
										static {{p.Type, -30}} {{interceptorName}}_Arg_{{p.Name, -13}} = default({{p.Type}});
								""");
							break;
					}
				}

				sb.AppendLine(
					$$"""
							static SR. MemberInfo                 {{interceptorName}}_MemberInfo        = MethodOf{{GetMethodOf(method, interceptorName)}};
					""");

				for (var i = 0; i < attributes.Count; i++)
				{
					var attr = attributes[i];

					sb
						.AppendLine(
							$$"""
									static SCG.Dictionary<string,object?> {{interceptorName}}_AspectArguments_{{i}} = new()
									{
							""")
						;

					if (attr.AttributeData is not null)
						foreach (var arg in attr.AttributeData.NamedArguments)
						{
							string value;

							if (arg.Value.Type is IArrayTypeSymbol arrayType)
							{
								value = arg.Value.Values.Length switch
								{
									0 => $"new {arrayType.ElementType}[0]",
									_ => $"new {arg.Value.Type} {{ {arg.Value.Values.Select(v => PrintValue(v.Value, arrayType.ElementType)).Aggregate((v1, v2) => $"{v1}, {v2}")} }}"
								};
							}
							else
								value = PrintValue(arg.Value.Value, arg.Value.Type);

							sb
								.AppendLine(
									$$"""
												["{{arg.Key}}"] = {{value}},
									""")
								;

						}

					sb
						.AppendLine(
							"""
									};
							""")
						;
				}

				sb.AppendLine(
					$$"""
							//
							/// <summary>
							/// Intercepts {{method}}.
							/// </summary>
							//
					""");

				foreach (var (inv, _, _) in methods)
				{

					sb.AppendLine(
						$"""
								// Intercepts {inv}.
						""");

					void AppendInterceptsLocation(InvocationExpressionSyntax invocation)
					{
						var semantic = compilation.GetSemanticModel(invocation.SyntaxTree);

#pragma warning disable RSEXPERIMENTAL002
						var location = semantic.GetInterceptableLocation(invocation, spc.CancellationToken);
#pragma warning restore RSEXPERIMENTAL002

						if (location is null)
						{
							var descriptor = new DiagnosticDescriptor(
								"AG0003",
								"AspectGenerator",
								$"Invocation '{invocation}' cannot be intercepted by the compiler.",
								"AspectGenerator",
								DiagnosticSeverity.Warning,
								true);

							spc.ReportDiagnostic(
								Diagnostic.Create(descriptor, invocation.GetLocation()));
							return;
						}

#pragma warning disable RSEXPERIMENTAL002
						sb.Append("\t\t").AppendLine(location.GetInterceptsLocationAttributeSyntax());
#pragma warning restore RSEXPERIMENTAL002
					}

					switch (inv.Expression)
					{
						case MemberAccessExpressionSyntax : AppendInterceptsLocation(inv); break;
						case IdentifierNameSyntax         : AppendInterceptsLocation(inv); break;
						default :
							sb.AppendLine(
								$"""
										#error Unknown expression type {inv.Expression.GetType()} for : {inv.Expression}
								""");
							break;
					}

					sb.AppendLine(
						"""
								//
						""");
				}

				sb.AppendLine("\t\t[System.Runtime.CompilerServices.CompilerGenerated]");

				if (options.DebuggerStepThrough is true)
					sb.AppendLine("\t\t[System.Diagnostics.DebuggerStepThrough]");

				sb.Append("\t\tpublic static ");

				var methodModifierPosition = sb.Length;

				sb
					.AppendLine(
						$$"""
						{{PrintType(method.ReturnType)}} {{interceptorName}}({{PrintParameters(method)}})
								{
						""")
					;

				GenerateMethodBody(spc, sb, methods[0].inv, method, interceptorName, attributes, methodModifierPosition);

				sb
					.AppendLine(
						"""
								}
						""")
					.AppendLine();
			}

			TrimEnd(sb);

			sb
				.AppendLine(
					"""
						}
					}
					""");

			spc.AddSource("Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		}

		static void GenerateMethodBody(
			SourceProductionContext    spc,
			StringBuilder              sb,
			InvocationExpressionSyntax invocationExpression,
			IMethodSymbol              method,
			string                     interceptorName,
			List<AttributeInfo>        attributes,
			int                        methodModifierPosition)
		{
			var isReturnsTask = method.ReturnType is { Name: "Task", ContainingNamespace: { Name : "Tasks", ContainingNamespace: { Name : "Threading", ContainingNamespace.Name : "System" }}};
			var taskType      = isReturnsTask && method.ReturnType is INamedTypeSymbol { IsGenericType : true, TypeArguments : [var argType] } ? argType : null;
			var generateAsync = isReturnsTask && attributes.Any(d => GetAspectArguments(d).Any(a => a.Key.EndsWith("Async") && a.Value is not null));
			var generateArgs  = attributes.Any(d => GetAspectArguments(d).Any(a => a is { Key: "PassArguments", Value: true }));

			// Generate arguments.
			//
			if (generateArgs)
			{
				sb.Append("\t\t\tvar __args__ = new object?[] { ");

				if (method.IsStatic == false)
					sb.Append("__this__, ");

				foreach (var p in method.Parameters)
					sb.Append(p.Name).Append(p.RefKind == RefKind.Out ? " = default, " : ", ");

				while (sb[^1] is ' ' or ',')
					sb.Length--;

				sb.Append(" };").AppendLine().AppendLine();
			}

			GenerateAttribute(0, "\t\t\t", false);

			void GenerateAttribute(int idx, string indent, bool isPrevData)
			{
				var attr   = attributes[idx].AttributeClass!;

				// Get aspect attribute parameters.
				//
				object? onInit           = null;
				object? onUsing          = null; object? onUsingAsync      = null;
				object? onBeforeCall     = null; object? onBeforeCallAsync = null;
				object? onCall           = null;
				object? onAfterCall      = null; object? onAfterCallAsync  = null;
				object? onCatch          = null; object? onCatchAsync      = null;
				object? onFinally        = null; object? onFinallyAsync    = null;
				var     useInterceptType = false;
				var     passArguments    = false;
				var     useInterceptData = false;
				var     needInfo         = attributes.Count > 1 || generateAsync;

				foreach (var arg in GetAspectArguments(attributes[idx]))
					switch (arg.Key)
					{
						case "OnInit"            : onInit            = arg.Value; needInfo = true; break;
						case "OnUsing"           : onUsing           = arg.Value; needInfo = true; break;
						case "OnUsingAsync"      : onUsingAsync      = arg.Value; needInfo = true; break;
						case "OnBeforeCall"      : onBeforeCall      = arg.Value; needInfo = true; break;
						case "OnBeforeCallAsync" : onBeforeCallAsync = arg.Value; needInfo = true; break;
						case "OnCall"            : onCall            = arg.Value;                  break;
						case "OnAfterCall"       : onAfterCall       = arg.Value; needInfo = true; break;
						case "OnAfterCallAsync"  : onAfterCallAsync  = arg.Value; needInfo = true; break;
						case "OnCatch"           : onCatch           = arg.Value; needInfo = true; break;
						case "OnCatchAsync"      : onCatchAsync      = arg.Value; needInfo = true; break;
						case "OnFinally"         : onFinally         = arg.Value; needInfo = true; break;
						case "OnFinallyAsync"    : onFinallyAsync    = arg.Value; needInfo = true; break;
						case "UseInterceptType"  : useInterceptType  = arg.Value is true; break;
						case "PassArguments"     : passArguments     = arg.Value is true; break;
						case "UseInterceptData"  : useInterceptData  = arg.Value is true; break;
					}

				if (generateAsync)
					sb.Insert(methodModifierPosition, "async ");

				var returnType = generateAsync ? taskType?.ToString() ?? "AspectGenerator.Void" : method.ReturnsVoid ? "AspectGenerator.Void" : $"{method.ReturnType}";

				// Generate AspectCallInfo.
				//
				if (needInfo)
				{
					sb
						.Append(indent).AppendLine($"// {(object?)attributes[idx].AttributeData ?? attributes[idx].AttributeClass}")
						.Append(indent).AppendLine("//")
						//.Append(indent).Append($"var __attr__{idx} = new {attributes[idx]}").Append(attributes[idx].NamedArguments.Length == 0 ? "()" : "").AppendLine(";")
						.Append(indent).AppendLine($"var __info__{idx} = new AspectGenerator.Intercept{(useInterceptData ? "Data" : "Info")}<{returnType}>")
						.Append(indent).AppendLine("{")
						//.Append(indent).AppendLine($"\tReturnValue     = {(idx > 0 ? $"__info__{idx - 1}.ReturnValue" : $"default({(method.ReturnsVoid ? "Void" : $"{method.ReturnType}")})")},")
						.Append(indent).AppendLine($"\tMemberInfo      = {interceptorName}_MemberInfo,")
						.Append(indent).AppendLine($"\tAspectType      = typeof({attr}),")
						.Append(indent).AppendLine($"\tAspectArguments = {interceptorName}_AspectArguments_{idx},")
						;

					if (passArguments)
						sb
							.Append(indent).AppendLine("\tMethodArguments = __args__,")
							;

					if (idx > 0 && !isPrevData)
						sb.Append(indent).AppendLine($"\tPreviousInfo    = __info__{idx - 1}");

					sb
						.Append(indent).AppendLine("};")
						.AppendLine()
						;
				}

				// Generate OnInit.
				//
				if (onInit is not null)
				{
					GenerateInterceptType("", "OnInit")
						.Append(indent).AppendLine($"__info__{idx} = {attr.ContainingNamespace}.{attr.Name}.{onInit}({PassInfo(idx)});")
						.AppendLine()
						;
				}

				// Generate OnUsing.
				//
				if (onUsing is not null)
				{
					var isAsync = generateAsync && onUsingAsync != null;
					GenerateInterceptType("", "OnUsing")
						.Append(indent).AppendLine($"{(isAsync ? "await " : "")}using ({attr.ContainingNamespace}.{attr.Name}.{(isAsync ? onUsingAsync : onUsing)}({PassInfo(idx)}))")
						.Append(indent).AppendLine("{")
						;
					indent += '\t';
				}

				// If OnCatch or OnFinally is defined, generate try/catch/finally block.
				//
				if (onCatch is not null || onFinally is not null)
				{
					sb.Append(indent).AppendLine("try");
					sb.Append(indent).AppendLine("{");
					indent += '\t';
				}

				// Generate OnBeforeCall.
				//
				if (generateAsync && onBeforeCallAsync is not null || onBeforeCall is not null)
				{
					GenerateInterceptType("", "OnBeforeCall");
					GenerateMethodCall(onBeforeCallAsync, onBeforeCall)
						.AppendLine()
						.Append(indent).AppendLine($"if (__info__{idx}.InterceptResult != AspectGenerator.InterceptResult.Return)")
						.Append(indent).AppendLine("{")
						;

					indent += '\t';
				}

				// Generate next attribute...
				//
				if (idx < attributes.Count - 1)
				{
					if (onCall is not null)
					{
						if (attributes[idx].AttributeData?.ApplicationSyntaxReference is {} asr)
						{
							spc.ReportDiagnostic(
								Diagnostic.Create(
									"AG0001",
									"AspectGenerator",
									$"Aspect '{attr}' specifies 'OnCall' interceptor and has to be the last one in aspect list.",
									DiagnosticSeverity.Error,
									DiagnosticSeverity.Error,
									true,
									0,
									location: Location.Create(asr.SyntaxTree, asr.Span)));
						}
						else
						{
							spc.ReportDiagnostic(
								Diagnostic.Create(
									"AG0002",
									"AspectGenerator",
									$"Method '{method}' is decorated with an aspect that specifies 'OnCall' interceptor. This aspect has to be the last one in aspect list.",
									DiagnosticSeverity.Error,
									DiagnosticSeverity.Error,
									true,
									0,
									location: Location.Create(invocationExpression.SyntaxTree, invocationExpression.Span)));
						}
					}

					sb.Append(indent).AppendLine("{");

					GenerateAttribute(idx + 1, indent + '\t', useInterceptData);

					TrimEnd(sb);

					sb
						.Append(indent).AppendLine("}")
						.AppendLine()
						;
				}
				// .. or call the target method.
				//
				else
				{
					sb
						.Append(indent)
						.Append(
							method.ReturnsVoid || isReturnsTask && method.ReturnType is INamedTypeSymbol { IsGenericType: false }
								? string.Empty
								: $"{(needInfo ? $"__info__{idx}.ReturnValue" : "var __return__")} = {(generateAsync ? "await " : "")}")
						.Append(
							onCall is null
								? method.IsExtensionMethod || method.IsStatic
									? method.OriginalDefinition.ContainingType
									: "__this__"
								: $"{attr.ContainingNamespace}.{attr.Name}")
						.Append('.')
						.Append(onCall ?? method.Name)
						.Append('(')
						;

					if (method.IsExtensionMethod || onCall is not null && method.IsStatic is false)
					{
						sb.Append("__this__");

						if (method.Parameters.Length > 0)
							sb.Append(", ");
					}

					foreach (var p in method.Parameters)
					{
						sb
							.Append(
								p.RefKind switch
								{
									RefKind.Ref => "ref ",
									RefKind.Out => "out ",
									RefKind.In  => "in ",
									_           => ""
								})
							.Append(p.Name)
							.Append(", ");
					}

					if (method.Parameters.Length > 0)
						sb.Length -= 2;

					sb
						.AppendLine(");")
						.AppendLine()
						;
				}

				// Generate OnAfterCall.
				//
				if (generateAsync && onAfterCallAsync is not null || onAfterCall is not null)
				{
					GenerateInterceptType("", "OnAfterCall");
					GenerateMethodCall(onAfterCallAsync, onAfterCall)
						.AppendLine();
				}

				// Generate OnBeforeCall end.
				//
				if (generateAsync && onBeforeCallAsync is not null || onBeforeCall is not null)
				{
					TrimEnd(sb);

					indent = indent[..^1];

					sb
						.Append(indent)
						.AppendLine("}")
						.AppendLine()
						;
				}

				// If OnCatch or OnFinally is defined, generate try/catch/finally block end.
				//
				if (generateAsync && onCatchAsync   is not null || onCatch   is not null ||
					generateAsync && onFinallyAsync is not null || onFinally is not null)
				{
					indent = indent[..^1];

					TrimEnd(sb);

					sb.AppendLine($"{indent}}}");

					// Generate OnCatch.
					//
					sb
						.Append(indent).AppendLine("catch (Exception __ex__)")
						.Append(indent).AppendLine("{")
						.Append(indent).AppendLine($"\t__info__{idx}.Exception{(onCatch is null ? null : "      ")} = __ex__;")
						;

					if (generateAsync && onCatchAsync is not null || onCatch is not null)
					{
						sb.Append(indent).AppendLine($"\t__info__{idx}.InterceptResult = AspectGenerator.InterceptResult.ReThrow;");

						GenerateInterceptType("\t", "OnCatch")
							.AppendLine()
							.Append('\t')
							;

						GenerateMethodCall(onCatchAsync, onCatch)
							.AppendLine()
							.Append(indent).AppendLine($"\tif (__info__{idx}.InterceptResult == AspectGenerator.InterceptResult.ReThrow)")
							.Append(indent).AppendLine("\t\tthrow;")
							;
					}
					else
					{
						sb.Append(indent).AppendLine("\tthrow;");
					}

					sb.Append(indent).AppendLine("}");

					// Generate OnFinally.
					//
					if (generateAsync && onFinallyAsync is not null || onFinally is not null)
					{
						sb
							.Append(indent).AppendLine("finally")
							.Append(indent).AppendLine("{");

						GenerateInterceptType("\t", "OnFinally")
							.Append('\t')
							;

						GenerateMethodCall(onFinallyAsync, onFinally)
							.Append(indent).AppendLine("}")
							;
					}

					sb.AppendLine();
				}

				// Generate OnUsing.
				//
				if (onUsing is not null)
				{
					indent = indent[..^1];

					TrimEnd(sb);

					sb
						.Append(indent)
						.AppendLine("}")
						.AppendLine()
						;
				}

				// Generate return.
				//
				if (idx > 0)
					sb.Append(indent).AppendLine($"__info__{idx - 1}.ReturnValue = __info__{idx}.ReturnValue;");
				else if (!(method.ReturnsVoid || isReturnsTask && method.ReturnType is INamedTypeSymbol { IsGenericType: false }))
					sb.AppendLine($"\t\t\treturn {(needInfo ? $"__info__{idx}.ReturnValue" : "__return__")};");

				TrimEnd(sb);

				string PassInfo(int idx)
				{
					return $"{(useInterceptData ? "ref " : "")}__info__{idx}";
				}

				StringBuilder GenerateMethodCall(object? onAsync, object? call)
				{
					if (generateAsync && onAsync is not null)
						return sb.Append(indent).AppendLine($"await {attr.ContainingNamespace}.{attr.Name}.{onAsync}({PassInfo(idx)});");
					return sb.Append(indent).AppendLine($"{attr.ContainingNamespace}.{attr.Name}.{call}({PassInfo(idx)});");
				}

				StringBuilder GenerateInterceptType(string additionalIndent, string interceptType)
				{
					if (useInterceptType)
					{
						sb
							.Append(additionalIndent)
							.Append(indent)
							.AppendLine($"__info__{idx}.InterceptType = AspectGenerator.InterceptType.{interceptType};");
					}

					return sb;
				}
			}
		}

		static void TrimEnd(StringBuilder sb)
		{
			while (sb[^1] is '\r' or '\n')
				sb.Length--;

			sb.AppendLine();
		}

		static string PrintValue(object? val, ITypeSymbol? type)
		{
			if (val is null)
				return "null";

			if (type?.TypeKind == TypeKind.Enum)
				return $"({type}){PrintValue(val, null)}";

			return val switch
			{
				string           s => SymbolDisplay.FormatLiteral(s, quote: true),
				char             c => SymbolDisplay.FormatLiteral(c, quote: true),
				bool             b => b ? "true" : "false",
				byte             b => b.ToString(CultureInfo.InvariantCulture),
				sbyte            b => b.ToString(CultureInfo.InvariantCulture),
				short            n => n.ToString(CultureInfo.InvariantCulture),
				ushort           n => n.ToString(CultureInfo.InvariantCulture),
				int              n => n.ToString(CultureInfo.InvariantCulture),
				uint             n => n.ToString(CultureInfo.InvariantCulture) + "u",
				long             n => n.ToString(CultureInfo.InvariantCulture) + "L",
				ulong            n => n.ToString(CultureInfo.InvariantCulture) + "uL",
				float            f => PrintSingle(f),
				double           d => PrintDouble(d),
				decimal          d => d.ToString(CultureInfo.InvariantCulture) + "m",
				INamedTypeSymbol s => $"typeof({s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})",
				_                  => Convert.ToString(val, CultureInfo.InvariantCulture) ?? "null"
			};

			static string PrintSingle(float value)
			{
				if (float.IsNaN(value))
					return "float.NaN";
				if (float.IsPositiveInfinity(value))
					return "float.PositiveInfinity";
				if (float.IsNegativeInfinity(value))
					return "float.NegativeInfinity";

				return value.ToString("R", CultureInfo.InvariantCulture) + "f";
			}

			static string PrintDouble(double value)
			{
				if (double.IsNaN(value))
					return "double.NaN";
				if (double.IsPositiveInfinity(value))
					return "double.PositiveInfinity";
				if (double.IsNegativeInfinity(value))
					return "double.NegativeInfinity";

				return value.ToString("R", CultureInfo.InvariantCulture) + "d";
			}
		}

		static string PrintType(ITypeSymbol type)
		{
			return $"{type}";
		}

		static string PrintParameters(IMethodSymbol method)
		{
			var parameters = method.Parameters;
			var sb         = new StringBuilder();

			if (method.IsStatic == false)
				sb.Append($"this {method.ReceiverType} __this__, ");

			foreach (var p in parameters)
				sb
					.Append(p)
					.Append(", ")
					;

			if (parameters.Length != 0 || method.IsStatic == false)
				sb.Length -= 2;

			return sb.ToString();
		}

		static string GetMethodOf(IMethodSymbol method, string interceptorName)
		{
			var sb = new StringBuilder();

			sb.Append("(() => ");

			sb
				.Append(method.IsExtensionMethod || method.IsStatic ? method.OriginalDefinition.ContainingType : $"default({method.ReceiverType})")
				.Append('.')
				.Append(method.Name)
				.Append('(')
				;

			if (method.IsExtensionMethod)
				sb.Append($"default({method.ReceiverType}), ");

			foreach (var p in method.Parameters)
				switch (p.RefKind)
				{
					case RefKind.Ref : sb.Append($"ref {interceptorName}_Arg_{p.Name}, "); break;
					case RefKind.In  : sb.Append($"in {interceptorName}_Arg_{p.Name}, ");  break;
					case RefKind.Out : sb.Append($"out {interceptorName}_Arg_{p.Name}, "); break;
					default          : sb.Append($"default({p.Type}), ");                  break;
				}

			while (sb[^1] is ',' or ' ')
				sb.Length--;

			sb.Append("))");

			return sb.ToString();
		}
	}
}
