using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace AspectGenerator
{
	[Generator(LanguageNames.CSharp)]
	public class AspectSourceGenerator : IIncrementalGenerator
	{
		// Diagnostic IDs
		public static class DiagnosticID
		{
			public const string OnCallNotLastAspect       = "AG0001";
			public const string OnCallNotLastMethod       = "AG0002";
			public const string CannotIntercept           = "AG0003";
			public const string NamespaceNotAllowed       = "AG0004";
			public const string HookMethodNotFound        = "AG0101";
			public const string HookMethodNotStatic       = "AG0102";
			public const string HookInvalidParameters     = "AG0103";
			public const string HookInvalidReturnType     = "AG0104";
			public const string OnCallHookMismatch        = "AG0105";
			public const string HookRequiresInterceptData = "AG0106";
			public const string AsyncHookRequiresTask     = "AG0107";
			public const string InvalidAspectFilterRegex  = "AG0201";
		}

		public static class OptionID
		{
			public const string GenerateApi                   = "GenerateApi";
			public const string GenerateInterceptors          = "GenerateInterceptors";
			public const string PublicApi                     = "PublicApi";
			public const string DebuggerStepThrough           = "DebuggerStepThrough";
			public const string InterceptorsNamespace         = "InterceptorsNamespace";
		}

		const string AspectGeneratorOptionsAttributeText =
			$$"""
			// <auto-generated/>
			#pragma warning disable
			#nullable enable

			using System;

			namespace AspectGenerator
			{
				/// <summary>
				/// Configures AspectGenerator for the current assembly.
				/// </summary>
				[AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
				sealed class AspectGeneratorOptionsAttribute : Attribute
				{
					/// <summary>
					/// Gets or sets whether AspectGenerator emits the shared generated API types for this assembly.
					/// </summary>
					/// <remarks>
					/// Keep this enabled for single-project usage. Set it to <c>false</c> when the API is supplied by an aspect library referenced by this project.
					/// </remarks>
					public bool    {{OptionID.GenerateApi}}                   { get; set; } = true;
					/// <summary>
					/// Gets or sets whether AspectGenerator emits interceptor implementations for this assembly.
					/// </summary>
					/// <remarks>
					/// This can be used to force interceptor generation in projects where generation would otherwise be skipped by build-time defaults.
					/// </remarks>
					public bool    {{OptionID.GenerateInterceptors}}          { get; set; }
					/// <summary>
					/// Gets or sets whether generated API types are emitted as public types.
					/// </summary>
					/// <remarks>
					/// Use this for aspect-library projects that expose aspect definitions and generated API types to other projects.
					/// </remarks>
					public bool    {{OptionID.PublicApi}}                     { get; set; }
					/// <summary>
					/// Gets or sets whether generated interceptor methods are marked with <see cref="System.Diagnostics.DebuggerStepThroughAttribute"/>.
					/// </summary>
					public bool    {{OptionID.DebuggerStepThrough}}           { get; set; }
					/// <summary>
					/// Gets or sets the namespace used for generated interceptor types.
					/// </summary>
					/// <remarks>
					/// The namespace must also be listed in the project <c>InterceptorsNamespaces</c> MSBuild property so Roslyn can use the generated interceptors.
					/// </remarks>
					public string? {{OptionID.InterceptorsNamespace}}         { get; set; }
				}
			}

			""";

		static string GenerateAspectApiText(bool publicApi)
		{
			var visibility = publicApi ? "public " : "";

			return
				$$"""
				// <auto-generated/>
				#pragma warning disable
				#nullable enable

				using System;

				namespace AspectGenerator
				{
				/// <summary>
				/// <para>Defines an aspect.</para>
				/// <para>Create a new attribute decorated with this attribute to define an aspect.</para>
				/// </summary>
				[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
				{{visibility}}sealed class AspectAttribute : Attribute
				{
					/// <summary>
					/// Gets or sets the static hook method name invoked when the aspect invocation state is initialized.
					/// </summary>
					public string?   OnInit            { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked before the target method inside a generated <c>using</c> scope.
					/// </summary>
					/// <remarks>
					/// The returned disposable value is disposed after the intercepted call completes.
					/// </remarks>
					public string?   OnUsing           { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked before an async target method inside a generated async disposal scope.
					/// </summary>
					public string?   OnUsingAsync      { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked before the target method is called.
					/// </summary>
					public string?   OnBeforeCall      { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked before a supported async target method is awaited.
					/// </summary>
					public string?   OnBeforeCallAsync { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name that replaces the target method call.
					/// </summary>
					/// <remarks>
					/// The hook signature must match the intercepted method signature and return type.
					/// </remarks>
					public string?   OnCall            { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked after the target method returns successfully.
					/// </summary>
					public string?   OnAfterCall       { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked after a supported async target method completes successfully.
					/// </summary>
					public string?   OnAfterCallAsync  { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked when the target method throws.
					/// </summary>
					/// <remarks>
					/// Set <see cref="InterceptInfo.InterceptResult"/> or <c>InterceptData&lt;T&gt;.InterceptResult</c> to control whether the exception is rethrown or ignored.
					/// </remarks>
					public string?   OnCatch           { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked when a supported async target method throws.
					/// </summary>
					public string?   OnCatchAsync      { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked in the generated <c>finally</c> block.
					/// </summary>
					public string?   OnFinally         { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked in the generated async cleanup path.
					/// </summary>
					public string?   OnFinallyAsync    { get; set; }
					/// <summary>
					/// Gets or sets whether hook data includes the current lifecycle stage.
					/// </summary>
					public bool      UseInterceptType  { get; set; }
					/// <summary>
					/// Gets or sets whether hook data includes the intercepted method arguments.
					/// </summary>
					/// <remarks>
					/// When enabled, generated code populates <see cref="InterceptInfo.MethodArguments"/> or <c>InterceptData&lt;T&gt;.MethodArguments</c>.
					/// </remarks>
					public bool      PassArguments     { get; set; }
					/// <summary>
					/// Gets or sets whether hooks use the mutable <c>ref InterceptData&lt;T&gt;</c> carrier instead of <c>InterceptInfo&lt;T&gt;</c>.
					/// </summary>
					public bool      UseInterceptData  { get; set; }
				}

				/// <summary>
				/// Identifies the lifecycle stage currently being processed by a hook.
				/// </summary>
				{{visibility}}enum InterceptType
				{
					/// <summary>
					/// Aspect invocation state is being initialized.
					/// </summary>
					OnInit,
					/// <summary>
					/// The generated using-scope hook is being entered.
					/// </summary>
					OnUsing,
					/// <summary>
					/// The target method is about to be called.
					/// </summary>
					OnBeforeCall,
					/// <summary>
					/// The target method returned successfully.
					/// </summary>
					OnAfterCall,
					/// <summary>
					/// The target method threw an exception.
					/// </summary>
					OnCatch,
					/// <summary>
					/// The generated cleanup path is running.
					/// </summary>
					OnFinally
				}

				/// <summary>
				/// Controls how generated interceptor code continues after a hook is executed.
				/// </summary>
				{{visibility}}enum InterceptResult
				{
					/// <summary>
					/// Continue normal generated interceptor flow.
					/// </summary>
					Continue,
					/// <summary>
					/// Return the current value from the interceptor.
					/// </summary>
					Return,
					/// <summary>
					/// Alias for <see cref="Continue"/> used by exception hooks to rethrow the current exception.
					/// </summary>
					ReThrow     = Continue,
					/// <summary>
					/// Alias for <see cref="Return"/> used by exception hooks to ignore the current exception.
					/// </summary>
					IgnoreThrow = Return
				}

				/// <summary>
				/// Represents a void return value in generic hook data.
				/// </summary>
				{{visibility}}struct Void
				{
				}

				/// <summary>
				/// Provides hook data for an intercepted method.
				/// </summary>
				{{visibility}}partial class InterceptInfo
				{
					/// <summary>
					/// Gets or sets user-defined state shared between hooks in the same interception chain.
					/// </summary>
					public object?         Tag;
					/// <summary>
					/// Gets or sets the current lifecycle stage.
					/// </summary>
					public InterceptType   InterceptType;
					/// <summary>
					/// Gets or sets the requested continuation behavior for generated interceptor code.
					/// </summary>
					public InterceptResult InterceptResult;
					/// <summary>
					/// Gets or sets the current exception for catch and finally hooks.
					/// </summary>
					public Exception?      Exception;

					/// <summary>
					/// Gets or sets hook data produced by the previous aspect in the same interception chain.
					/// </summary>
					public InterceptInfo?                                        PreviousInfo;
					/// <summary>
					/// Gets or sets reflection metadata for the intercepted target method.
					/// </summary>
					public System.Reflection.MemberInfo                          MemberInfo;
					/// <summary>
					/// Gets or sets intercepted method arguments when argument capture is enabled.
					/// </summary>
					public object?[]?                                            MethodArguments;
					/// <summary>
					/// Gets or sets the applied aspect attribute type.
					/// </summary>
					public Type                                                  AspectType;
					/// <summary>
					/// Gets or sets named arguments from the applied aspect attribute.
					/// </summary>
					public System.Collections.Generic.Dictionary<string,object?> AspectArguments;
				}

				/// <summary>
				/// Provides hook data for an intercepted method with a return value.
				/// </summary>
				/// <typeparam name="T">The intercepted method return value type.</typeparam>
				{{visibility}}partial class InterceptInfo<T> : InterceptInfo
				{
					/// <summary>
					/// Gets or sets the intercepted method return value.
					/// </summary>
					public T ReturnValue;
				}

				/// <summary>
				/// Provides mutable by-reference hook data for an intercepted method.
				/// </summary>
				/// <typeparam name="T">The intercepted method return value type.</typeparam>
				{{visibility}}partial struct InterceptData<T>
				{
					/// <summary>
					/// Gets or sets user-defined state shared between hooks in the same interception chain.
					/// </summary>
					public object?         Tag;
					/// <summary>
					/// Gets or sets the current lifecycle stage.
					/// </summary>
					public InterceptType   InterceptType;
					/// <summary>
					/// Gets or sets the requested continuation behavior for generated interceptor code.
					/// </summary>
					public InterceptResult InterceptResult;
					/// <summary>
					/// Gets or sets the current exception for catch and finally hooks.
					/// </summary>
					public Exception?      Exception;

					/// <summary>
					/// Gets or sets hook data produced by the previous aspect in the same interception chain.
					/// </summary>
					public InterceptInfo<T>?                                     PreviousInfo;
					/// <summary>
					/// Gets or sets reflection metadata for the intercepted target method.
					/// </summary>
					public System.Reflection.MemberInfo                          MemberInfo;
					/// <summary>
					/// Gets or sets intercepted method arguments when argument capture is enabled.
					/// </summary>
					public object?[]?                                            MethodArguments;
					/// <summary>
					/// Gets or sets the applied aspect attribute type.
					/// </summary>
					public Type                                                  AspectType;
					/// <summary>
					/// Gets or sets named arguments from the applied aspect attribute.
					/// </summary>
					public System.Collections.Generic.Dictionary<string,object?> AspectArguments;

					/// <summary>
					/// Gets or sets the intercepted method return value.
					/// </summary>
					public T ReturnValue;
				}
			}

			""";
		}

		class Options
		{
			public bool?   GenerateApi;
			public bool?   GenerateInterceptors;
			public bool?   DesignTimeBuild;
			public bool?   PublicApi;
			public bool?   DebuggerStepThrough;
			public string? InterceptorsNamespace;
			public string? InterceptorsNamespaces;
		}

		record GeneratorExecutionOptions(
			bool    GenerateApi,
			bool    GenerateInterceptors,
			bool    PublicApi,
			bool    DebuggerStepThrough,
			string? InterceptorsNamespace,
			string? InterceptorsNamespaces);

		record AttributeInfo(
			AttributeData?    AttributeData,
			INamedTypeSymbol  AttributeClass,
			AttributeData?    AspectAttributeData,
			AttributeSyntax?  AspectAttributeSyntax,
			SemanticModel?    AspectSemanticModel)
		{
		}

		record CompiledAspectFilter(
			bool             IsNegative,
			FilterMatcher    Matcher,
			string           Pattern,
			Regex?           Regex);

		enum FilterMatcher
		{
			Pattern,
			Contains,
			Regex
		}

		record AspectFilterSet(
			AttributeInfo                         Attribute,
			ImmutableArray<CompiledAspectFilter> Filters);

		record AnalyzedInvocation(
			InvocationExpressionSyntax Inv,
			IMethodSymbol              Method,
			List<AttributeInfo>        Attributes);

		record DiagnosticInfo(
			string    Id,
			string    Message,
			Location? Location,
			bool      IsError = true);

		record AnalysisResult(
			Compilation                        Compilation,
			GeneratorExecutionOptions         Options,
			ImmutableArray<AnalyzedInvocation> AspectedMethods,
			ImmutableArray<DiagnosticInfo>     Diagnostics);

		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
#if DEBUG && TRUE1
			if (!System.Diagnostics.Debugger.IsAttached)
			{
				System.Diagnostics.Debugger.Launch();
			}
#endif

			context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
				"AspectGeneratorOptionsAttribute.g.cs",
				SourceText.From(AspectGeneratorOptionsAttributeText, Encoding.UTF8)));

			var attributes = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } c && c.AttributeLists
						.SelectMany(static l => l.Attributes)
						.Any(static a => IsAspectAttributeName(a.Name.ToString())),
					transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
				.Collect();

			var invocations = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (node, _) => node is InvocationExpressionSyntax
					{
						Expression: MemberAccessExpressionSyntax or IdentifierNameSyntax
					},
					transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node)
				.Collect();

			var options = context.AnalyzerConfigOptionsProvider.Select((c, _) =>
				new Options
				{
					GenerateApi            = GetBoolProperty(c.GlobalOptions, $"build_property.AspectGenerator{OptionID.GenerateApi}"),
					GenerateInterceptors   = GetBoolProperty(c.GlobalOptions, $"build_property.AspectGenerator{OptionID.GenerateInterceptors}"),
					DesignTimeBuild        = GetBoolProperty(c.GlobalOptions,  "build_property.DesignTimeBuild"),
					PublicApi              = GetBoolProperty(c.GlobalOptions, $"build_property.AspectGenerator{OptionID.PublicApi}"),
					DebuggerStepThrough    = GetBoolProperty(c.GlobalOptions, $"build_property.AspectGenerator{OptionID.DebuggerStepThrough}"),
					InterceptorsNamespace  = c.GlobalOptions.TryGetValue($"build_property.AspectGenerator{OptionID.InterceptorsNamespace}", out var ns) ? ns : null,
					InterceptorsNamespaces = c.GlobalOptions.TryGetValue("build_property.InterceptorsNamespaces", out var namespaces) ? namespaces : null,
				});

			var analysis = context.CompilationProvider
				.Combine(options)
				.Combine(attributes)
				.Combine(invocations)
				.Select(static (data, ct) => Analyze(data, ct));

			context.RegisterSourceOutput(analysis, ReportDiagnostics);
			context.RegisterImplementationSourceOutput(analysis, EmitInterceptors);
		}

		static AnalysisResult Analyze(
			(((Compilation Left, Options Right) Left, ImmutableArray<ClassDeclarationSyntax> Right) Left, ImmutableArray<InvocationExpressionSyntax> Right) data,
			CancellationToken cancellationToken)
		{
			var compilation = data.Left.Left.Left;
			var options     = ResolveOptions(compilation, data.Left.Left.Right);
			var attrs       = data.Left.Right;
			var invocations = data.Right;

			var diagnostics = new List<DiagnosticInfo>();
			var reportedDiagnostics = new HashSet<string>();

			var aspectAttributes = new Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)>(SymbolEqualityComparer.Default);

			foreach (var a in attrs)
			{
				var semanticModel = compilation.GetSemanticModel(a.SyntaxTree);

				if (semanticModel.GetDeclaredSymbol(a, cancellationToken) is not {} symbol)
					continue;

				foreach (var attribute in a.AttributeLists.SelectMany(static l => l.Attributes))
				{
					if (!IsAspectAttributeName(attribute.Name.ToString()))
						continue;

					aspectAttributes[symbol] = (attribute, semanticModel);
					break;
				}
			}

			ValidateAspectHooks(diagnostics, aspectAttributes, reportedDiagnostics);

			var assemblyFilters = BuildAssemblyFilters(compilation, diagnostics, aspectAttributes, reportedDiagnostics);

			var aspectedMethods  = new List<AnalyzedInvocation>();
			var methodDic        = new Dictionary<IMethodSymbol,List<AttributeInfo>>(SymbolEqualityComparer.Default);
			var typeFilterDic    = new Dictionary<INamedTypeSymbol,ImmutableArray<AspectFilterSet>>(SymbolEqualityComparer.Default);

			foreach (var invocation in invocations)
			{
				var semantic = compilation.GetSemanticModel(invocation.SyntaxTree);
				var info     = semantic.GetSymbolInfo(invocation, cancellationToken);

				// Bind only invocation candidates provided by SyntaxProvider.
				//
				if (info.Symbol is IMethodSymbol method)
				{
					if (!methodDic.TryGetValue(method, out var attributes))
					{
						attributes = new();

						var methodAttributes = method.GetAttributes();

						// .. decorated with any Aspect attribute...
						//
						if (methodAttributes.Length > 0)
						{
							foreach (var ma in methodAttributes)
							{
								// .. if attribute is defined in the compiling assembly...
								//
								if (ma.AttributeClass is not null && aspectAttributes.TryGetValue(ma.AttributeClass, out var aspectAttribute))
								{
									attributes.Add(new AttributeInfo(ma, ma.AttributeClass, null, aspectAttribute.Syntax, aspectAttribute.SemanticModel));
								}
								// .. or somewhere else.
								else if (ma.AttributeClass?.GetAttributes().FirstOrDefault(aa => aa is { AttributeClass : { ContainingNamespace.Name : "AspectGenerator", Name : "AspectAttribute" }}) is {} externalAspectAttributeData)
								{
									attributes.Add(new AttributeInfo(ma, ma.AttributeClass!, externalAspectAttributeData, null, null));
								}
							}
						}

						var targetSignature = GetCanonicalMethodFilterSignature(method);

						AddMatchedFilterAttributes(attributes, assemblyFilters, targetSignature);
						AddMatchedFilterAttributes(attributes, GetTypeFilters(compilation, diagnostics, aspectAttributes, typeFilterDic, method.ContainingType, reportedDiagnostics), targetSignature);

						methodDic[method] = attributes.Distinct().ToList();
					}

					if (attributes.Count > 0)
						aspectedMethods.Add(new AnalyzedInvocation(invocation, method, attributes));
				}

				if (cancellationToken.IsCancellationRequested)
					break;
			}

			if (!cancellationToken.IsCancellationRequested)
				foreach (var m in aspectedMethods.GroupBy(static m => m.Method, SymbolEqualityComparer.Default))
					ValidateAspectHooksForMethod(diagnostics, compilation, m.First().Inv, (IMethodSymbol)m.Key!, m.First().Attributes, reportedDiagnostics);

			ReportMissingInterceptorsNamespace(diagnostics, options);

			return new AnalysisResult(compilation, options, aspectedMethods.ToImmutableArray(), diagnostics.ToImmutableArray());
		}

		static void ReportDiagnostics(SourceProductionContext spc, AnalysisResult analysis)
		{
			if (analysis.Options.GenerateApi)
				spc.AddSource("AspectAttribute.g.cs", SourceText.From(GenerateAspectApiText(analysis.Options.PublicApi), Encoding.UTF8));

			foreach (var diagnostic in analysis.Diagnostics)
			{
				spc.ReportDiagnostic(
					Diagnostic.Create(
						diagnostic.Id,
						"AspectGenerator",
						diagnostic.Message,
						diagnostic.IsError ? DiagnosticSeverity.Error : DiagnosticSeverity.Warning,
						diagnostic.IsError ? DiagnosticSeverity.Error : DiagnosticSeverity.Warning,
						true,
						0,
						location: diagnostic.Location));
			}
		}

		static void EmitInterceptors(SourceProductionContext spc, AnalysisResult analysis)
		{
			if (!analysis.Options.GenerateInterceptors ||
				analysis.AspectedMethods.Length == 0 ||
				spc.CancellationToken.IsCancellationRequested)
				return;

			GenerateSource(spc, analysis.Compilation, analysis.Options, analysis.AspectedMethods);
		}

		static bool? GetBoolProperty(AnalyzerConfigOptions options, string name)
		{
			if (!options.TryGetValue(name, out var value))
				return null;

			return bool.TryParse(value, out var result) ? result : null;
		}

		static GeneratorExecutionOptions ResolveOptions(Compilation compilation, Options msBuildOptions)
		{
			var result = new Options
			{
				GenerateApi                   = msBuildOptions.GenerateApi,
				GenerateInterceptors          = msBuildOptions.GenerateInterceptors,
				DesignTimeBuild               = msBuildOptions.DesignTimeBuild,
				PublicApi                     = msBuildOptions.PublicApi,
				DebuggerStepThrough           = msBuildOptions.DebuggerStepThrough,
				InterceptorsNamespace         = msBuildOptions.InterceptorsNamespace,
				InterceptorsNamespaces = msBuildOptions.InterceptorsNamespaces,
			};

			var attr = compilation.Assembly.GetAttributes().FirstOrDefault(a =>
				a.AttributeClass is { ContainingNamespace.Name: "AspectGenerator", Name: "AspectGeneratorOptionsAttribute" });

			if (attr is null)
				return CreateExecutionOptions(result);

			foreach (var arg in attr.NamedArguments)
			{
				switch (arg.Key)
				{
					case OptionID.GenerateApi           when arg.Value.Value is bool   generateApi          : result.GenerateApi           = generateApi;           break;
					case OptionID.GenerateInterceptors  when arg.Value.Value is bool   generateInterceptors : result.GenerateInterceptors  = generateInterceptors;  break;
					case OptionID.PublicApi             when arg.Value.Value is bool   publicApi            : result.PublicApi             = publicApi;             break;
					case OptionID.DebuggerStepThrough   when arg.Value.Value is bool   debuggerStepThrough  : result.DebuggerStepThrough   = debuggerStepThrough;   break;
					case OptionID.InterceptorsNamespace when arg.Value.Value is string interceptorsNamespace: result.InterceptorsNamespace = interceptorsNamespace; break;
				}
			}

			return CreateExecutionOptions(result);

			static GeneratorExecutionOptions CreateExecutionOptions(Options options)
			{
				var generateInterceptors = options.GenerateInterceptors ?? options.DesignTimeBuild is not true;

				return new GeneratorExecutionOptions(
					options.GenerateApi is not false,
					generateInterceptors,
					options.PublicApi is true,
					options.DebuggerStepThrough is true,
					options.InterceptorsNamespace,
					options.InterceptorsNamespaces);
			}
		}

		static string GetInterceptorsNamespace(GeneratorExecutionOptions options)
		{
			return string.IsNullOrWhiteSpace(options.InterceptorsNamespace) ? "AspectGenerator" : options.InterceptorsNamespace!;
		}

		static void ReportMissingInterceptorsNamespace(List<DiagnosticInfo> diagnostics, GeneratorExecutionOptions options)
		{
			var interceptorsNamespace = GetInterceptorsNamespace(options);

			if (string.IsNullOrWhiteSpace(options.InterceptorsNamespaces))
				return;

			var namespaces = options.InterceptorsNamespaces!
				.Split([';'], StringSplitOptions.RemoveEmptyEntries)
				.Select(static n => n.Trim());

			if (namespaces.Contains(interceptorsNamespace, StringComparer.Ordinal))
				return;

			diagnostics.Add(
				new DiagnosticInfo(
				DiagnosticID.NamespaceNotAllowed,
				$"Generated interceptors namespace '{interceptorsNamespace}' is not listed in the InterceptorsNamespaces MSBuild property.",
				Location.None,
				IsError: false));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeInfo attribute)
		{
			if (attribute.AspectAttributeData is {} aspectAttributeData)
				return GetAspectArguments(aspectAttributeData);

			if (attribute is { AspectAttributeSyntax: {} syntax, AspectSemanticModel: {} semanticModel })
				return GetAspectArguments(syntax, semanticModel);

			return [];
		}

		static void ValidateAspectHooks(
			List<DiagnosticInfo>                                                       diagnostics,
			Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes,
			HashSet<string>                                                           reportedDiagnostics)
		{
			foreach (var item in aspectAttributes)
			{
				var symbol          = item.Key;
				var aspectAttribute = item.Value;

				if (symbol is not INamedTypeSymbol aspectClass)
					continue;

				foreach (var arg in aspectAttribute.Syntax.ArgumentList?.Arguments ?? default)
				{
					if (arg.NameEquals is null || !IsHookName(arg.NameEquals.Name.Identifier.ValueText))
						continue;

					if (GetAttributeArgumentValue(arg.Expression, aspectAttribute.SemanticModel) is not string hookName || string.IsNullOrWhiteSpace(hookName))
						continue;

					var methods = aspectClass.GetMembers(hookName).OfType<IMethodSymbol>().ToArray();

					if (methods.Length == 0)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotFound,
							$"Aspect hook method '{hookName}' was not found on aspect type '{aspectClass.ToDisplayString()}'.",
							arg.Expression.GetLocation());
					}
					else if (!methods.Any(static m => m.IsStatic))
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotStatic,
							$"Aspect hook method '{hookName}' on aspect type '{aspectClass.ToDisplayString()}' must be static.",
							arg.Expression.GetLocation());
					}
				}
			}
		}

		static void ReportDiagnostic(List<DiagnosticInfo> diagnostics, HashSet<string> reportedDiagnostics, string id, string message, Location? location)
		{
			var key = $"{id}:{location?.SourceTree?.FilePath}:{location?.SourceSpan.Start}:{message}";

			if (!reportedDiagnostics.Add(key))
				return;

			diagnostics.Add(new DiagnosticInfo(id, message, location));
		}

		static ImmutableArray<AspectFilterSet> BuildAssemblyFilters(
			Compilation                                                             compilation,
			List<DiagnosticInfo>                                                    diagnostics,
			Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes,
			HashSet<string>                                                          reportedDiagnostics)
		{
			var result = ImmutableArray.CreateBuilder<AspectFilterSet>();

			foreach (var filterAttribute in compilation.Assembly.GetAttributes())
			{
				if (!filterAttribute.NamedArguments.Any(static a => a.Key == "TargetFilter"))
					continue;

				if (CreateAppliedAspectFilterSet(
					diagnostics,
					aspectAttributes,
					reportedDiagnostics,
					filterAttribute) is {} filterSet)
					result.Add(filterSet);
			}

			return result.ToImmutable();
		}

		static ImmutableArray<AspectFilterSet> GetTypeFilters(
			Compilation                                                             compilation,
			List<DiagnosticInfo>                                                    diagnostics,
			Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes,
			Dictionary<INamedTypeSymbol,ImmutableArray<AspectFilterSet>>             typeFilterDic,
			INamedTypeSymbol?                                                       type,
			HashSet<string>                                                          reportedDiagnostics)
		{
			if (type is null)
				return [];

			if (typeFilterDic.TryGetValue(type, out var cached))
				return cached;

			var result = ImmutableArray.CreateBuilder<AspectFilterSet>();

			foreach (var syntaxReference in type.DeclaringSyntaxReferences)
			{
				if (syntaxReference.GetSyntax() is not TypeDeclarationSyntax typeDeclaration)
					continue;

				var semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);

				foreach (var filterAttribute in typeDeclaration.AttributeLists.SelectMany(static list => list.Attributes))
				{
					if (!HasNamedArgument(filterAttribute, "TargetFilter"))
						continue;

					if (CreateAppliedAspectFilterSet(
						diagnostics,
						aspectAttributes,
						reportedDiagnostics,
						filterAttribute,
						semanticModel) is {} filterSet)
						result.Add(filterSet);
				}
			}

			var filters = result.ToImmutable();
			typeFilterDic[type] = filters;

			return filters;
		}

		static AspectFilterSet? CreateAppliedAspectFilterSet(
			List<DiagnosticInfo>                                                    diagnostics,
			Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes,
			HashSet<string>                                                          reportedDiagnostics,
			AttributeSyntax                                                         filterAttribute,
			SemanticModel                                                            semanticModel)
		{
			if (semanticModel.GetSymbolInfo(filterAttribute).Symbol is not IMethodSymbol { ContainingType: var aspectClass })
				return null;

			var aspectAttributeData = aspectClass.GetAttributes().FirstOrDefault(aa => aa is { AttributeClass : { ContainingNamespace.Name : "AspectGenerator", Name : "AspectAttribute" }});

			AttributeInfo attributeInfo;

			if (aspectAttributes.TryGetValue(aspectClass, out var aspectAttribute))
				attributeInfo = new AttributeInfo(null, aspectClass, null, aspectAttribute.Syntax, aspectAttribute.SemanticModel);
			else if (aspectAttributeData is not null)
				attributeInfo = new AttributeInfo(null, aspectClass, aspectAttributeData, null, null);
			else
				return null;

			var filterValues = GetNamedStringFilterValue(filterAttribute, semanticModel, "TargetFilter");

			if (filterValues.IsDefaultOrEmpty)
				return null;

			var filters = CompileAspectFilters(diagnostics, reportedDiagnostics, filterValues, filterAttribute.GetLocation());

			return filters.IsDefaultOrEmpty ? null : new AspectFilterSet(attributeInfo, filters);
		}

		static AspectFilterSet? CreateAppliedAspectFilterSet(
			List<DiagnosticInfo>                                                    diagnostics,
			Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes,
			HashSet<string>                                                          reportedDiagnostics,
			AttributeData                                                           filterAttribute)
		{
			if (filterAttribute.AttributeClass is not {} aspectClass)
				return null;

			var aspectAttributeData = aspectClass.GetAttributes().FirstOrDefault(aa => aa is { AttributeClass : { ContainingNamespace.Name : "AspectGenerator", Name : "AspectAttribute" }});

			AttributeInfo attributeInfo;

			if (aspectAttributes.TryGetValue(aspectClass, out var aspectAttribute))
				attributeInfo = new AttributeInfo(null, aspectClass, null, aspectAttribute.Syntax, aspectAttribute.SemanticModel);
			else if (aspectAttributeData is not null)
				attributeInfo = new AttributeInfo(null, aspectClass, aspectAttributeData, null, null);
			else
				return null;

			var filterValues = GetNamedStringFilterValue(filterAttribute, "TargetFilter");

			if (filterValues.IsDefaultOrEmpty)
				return null;

			var location = filterAttribute.ApplicationSyntaxReference is {} syntaxReference
				? Location.Create(syntaxReference.SyntaxTree, syntaxReference.Span)
				: null;
			var filters = CompileAspectFilters(diagnostics, reportedDiagnostics, filterValues, location);

			return filters.IsDefaultOrEmpty ? null : new AspectFilterSet(attributeInfo, filters);
		}

		static ImmutableArray<string> GetNamedStringFilterValue(AttributeSyntax attribute, SemanticModel semanticModel, string name)
		{
			foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
			{
				if (arg.NameEquals?.Name.Identifier.ValueText != name)
					continue;

				var value = GetAttributeArgumentValue(arg.Expression, semanticModel);

				return GetStringFilterValues(value);
			}

			return [];
		}

		static ImmutableArray<string> GetNamedStringFilterValue(AttributeData attribute, string name)
		{
			foreach (var arg in attribute.NamedArguments)
			{
				if (arg.Key != name)
					continue;

				return arg.Value.Kind == TypedConstantKind.Array
					? GetStringFilterValues(arg.Value.Values.Select(static v => v.Value).ToArray())
					: GetStringFilterValues(arg.Value.Value);
			}

			return [];
		}

		static ImmutableArray<string> GetStringFilterValues(object? value)
		{
			var result = ImmutableArray.CreateBuilder<string>();

			if (value is object?[] values)
			{
				foreach (var item in values)
					AddStringFilterValue(result, item as string);
			}
			else
				AddStringFilterValue(result, value as string);

			return result.ToImmutable();
		}

		static void AddStringFilterValue(ImmutableArray<string>.Builder result, string? value)
		{
			if (value is null)
				return;

			foreach (var line in value.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n'))
			{
				var rule = line.Trim();

				if (rule.Length > 0 && !rule.StartsWith("#", StringComparison.Ordinal))
					result.Add(rule);
			}
		}

		static ImmutableArray<CompiledAspectFilter> CompileAspectFilters(
			List<DiagnosticInfo> diagnostics,
			HashSet<string>      reportedDiagnostics,
			ImmutableArray<string> filters,
			Location?            location)
		{
			var result = ImmutableArray.CreateBuilder<CompiledAspectFilter>();

			foreach (var filter in filters)
			{
				if (!TryParseAspectFilterRule(filter, out var isNegative, out var matcher, out var pattern))
					continue;

				if (matcher == FilterMatcher.Pattern)
					continue;

				if (matcher == FilterMatcher.Contains)
				{
					result.Add(
						new CompiledAspectFilter(
							isNegative,
							matcher,
							pattern,
							null));

					continue;
				}

				try
				{
					result.Add(
						new CompiledAspectFilter(
							isNegative,
							matcher,
							pattern,
							new Regex(pattern, RegexOptions.CultureInvariant, TimeSpan.FromMilliseconds(200))));
				}
				catch (ArgumentException ex)
				{
					ReportDiagnostic(
						diagnostics,
						reportedDiagnostics,
						DiagnosticID.InvalidAspectFilterRegex,
						$"Invalid aspect filter regex '{pattern}': {ex.Message}",
						location);
				}
			}

			return result.ToImmutable();
		}

		static bool TryParseAspectFilterRule(string filter, out bool isNegative, out FilterMatcher matcher, out string pattern)
		{
			isNegative = false;
			matcher    = FilterMatcher.Pattern;
			pattern    = "";

			var rule = filter.Trim();

			if (rule.Length == 0 || rule.StartsWith("#", StringComparison.Ordinal))
				return false;

			if (rule[0] == '-')
			{
				isNegative = true;
				rule       = rule[1..].TrimStart();
			}

			if (TryReadMatcherPrefix(rule, "pattern", out var patternBody))
			{
				matcher = FilterMatcher.Pattern;
				pattern = patternBody;
			}
			else if (TryReadMatcherPrefix(rule, "regex", out var regexBody))
			{
				matcher = FilterMatcher.Regex;
				pattern = regexBody;
			}
			else if (TryReadMatcherPrefix(rule, "contains", out var containsBody))
			{
				matcher = FilterMatcher.Contains;
				pattern = containsBody;
			}
			else
				pattern = rule;

			return pattern.Length > 0;
		}

		static bool TryReadMatcherPrefix(string rule, string prefix, out string body)
		{
			body = "";

			if (!rule.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
				return false;

			var index = prefix.Length;

			while (index < rule.Length && char.IsWhiteSpace(rule[index]))
				index++;

			if (index >= rule.Length || rule[index] != ':')
				return false;

			body = rule[(index + 1)..].Trim();
			return true;
		}

		static void AddMatchedFilterAttributes(List<AttributeInfo> attributes, ImmutableArray<AspectFilterSet> filterSets, string targetSignature)
		{
			foreach (var filterSet in filterSets)
			{
				if (!IsMatchedByFilters(filterSet.Filters, targetSignature))
					continue;

				if (attributes.Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, filterSet.Attribute.AttributeClass)))
					continue;

				attributes.Add(filterSet.Attribute);
			}
		}

		static bool IsMatchedByFilters(ImmutableArray<CompiledAspectFilter> filters, string targetSignature)
		{
			var matched = false;

			foreach (var filter in filters)
			{
				var isMatch = filter.Matcher switch
				{
					FilterMatcher.Contains => targetSignature.Contains(filter.Pattern, StringComparison.Ordinal),
					FilterMatcher.Regex    => IsRegexMatch(filter, targetSignature),
					_                      => false
				};

				if (!isMatch)
					continue;

				matched = !filter.IsNegative;
			}

			return matched;
		}

		static bool IsRegexMatch(CompiledAspectFilter filter, string targetSignature)
		{
			try
			{
				return filter.Regex?.IsMatch(targetSignature) == true;
			}
			catch (RegexMatchTimeoutException)
			{
				return false;
			}
		}

		static string GetCanonicalMethodFilterSignature(IMethodSymbol method)
		{
			var sourceMethod = method.ReducedFrom ?? method;
			var parts        = new List<string> { GetAccessibility(sourceMethod.DeclaredAccessibility) };

			if (sourceMethod.IsStatic)                              parts.Add("static");
			if (sourceMethod.IsAbstract)                            parts.Add("abstract");
			if (sourceMethod.IsVirtual && !sourceMethod.IsOverride) parts.Add("virtual");
			if (sourceMethod.IsOverride)                            parts.Add("override");
			if (sourceMethod.IsSealed)                              parts.Add("sealed");
			if (sourceMethod.IsExtern)                              parts.Add("extern");
			if (HasUnsafeModifier(sourceMethod))                    parts.Add("unsafe");

			var sb = new StringBuilder();

			sb
				.Append(string.Join(" ", parts))
				.Append(' ')
				.Append(FormatFilterType(sourceMethod.ReturnType))
				.Append(' ')
				.Append(FormatFilterType(sourceMethod.ContainingType))
				.Append('.')
				.Append(sourceMethod.Name);

			if (sourceMethod.TypeArguments.Length > 0)
				sb.Append('<').Append(string.Join(",", sourceMethod.TypeArguments.Select(FormatFilterType))).Append('>');

			sb.Append('(');

			var parameters = new List<string>();

			var methodParameters = sourceMethod.Parameters.AsEnumerable();

			if (method.ReducedFrom is not null || method.IsExtensionMethod || sourceMethod.IsExtensionMethod)
			{
				var receiverType = method.ReceiverType ?? sourceMethod.Parameters.FirstOrDefault()?.Type;

				if (receiverType is not null)
					parameters.Add($"this {FormatFilterType(receiverType)}");

				if (sourceMethod.Parameters.Length > 0)
					methodParameters = methodParameters.Skip(1);
			}

			foreach (var parameter in methodParameters)
			{
				var parameterText = new StringBuilder();

				if (parameter.IsParams)
					parameterText.Append("params ");

				parameterText.Append(parameter.RefKind switch
				{
					RefKind.Ref => "ref ",
					RefKind.Out => "out ",
					RefKind.In  => "in ",
					_           => ""
				});

				parameterText.Append(FormatFilterType(parameter.Type));
				parameters.Add(parameterText.ToString());
			}

			sb.Append(string.Join(",", parameters));
			sb.Append(')');

			return sb.ToString();
		}

		static bool HasUnsafeModifier(IMethodSymbol method)
		{
			foreach (var syntaxReference in method.DeclaringSyntaxReferences)
				if (syntaxReference.GetSyntax() is MethodDeclarationSyntax methodDeclaration &&
					methodDeclaration.Modifiers.Any(SyntaxKind.UnsafeKeyword))
					return true;

			return false;
		}

		static string GetAccessibility(Accessibility accessibility)
		{
			return accessibility switch
			{
				Accessibility.Public             => "public",
				Accessibility.Protected          => "protected",
				Accessibility.Internal           => "internal",
				Accessibility.Private            => "private",
				Accessibility.ProtectedOrInternal => "protected internal",
				Accessibility.ProtectedAndInternal => "private protected",
				_                                => "private"
			};
		}

		static string FormatFilterType(ITypeSymbol type)
		{
			if (type is IArrayTypeSymbol arrayType)
				return $"{FormatFilterType(arrayType.ElementType)}[]";

			if (type is ITypeParameterSymbol typeParameter)
				return typeParameter.Name;

			if (type is INamedTypeSymbol { IsGenericType: true } namedType)
			{
				var unbound = namedType.OriginalDefinition;
				var name    = unbound.Name;
				var tick    = name.IndexOf('`');

				if (tick >= 0)
					name = name[..tick];

				return $"{unbound.ContainingNamespace.ToDisplayString()}.{name}<{string.Join(",", namedType.TypeArguments.Select(FormatFilterType))}>";
			}

			return type.ToDisplayString(
				new SymbolDisplayFormat(
					typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
					genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
					miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeData attribute)
		{
			return attribute.NamedArguments.Select(static arg => (
				arg.Key,
				arg.Value.Kind == TypedConstantKind.Array ? arg.Value.Values.Select(static v => v.Value).ToArray() : arg.Value.Value));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeSyntax attribute, SemanticModel semanticModel)
		{
			foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
				if (arg.NameEquals is not null)
					yield return (arg.NameEquals.Name.Identifier.ValueText, GetAttributeArgumentValue(arg.Expression, semanticModel));
		}

		static object? GetAttributeArgumentValue(ExpressionSyntax expression, SemanticModel semanticModel)
		{
			if (expression is ImplicitArrayCreationExpressionSyntax { Initializer.Expressions: var implicitValues })
				return implicitValues.Select(e => semanticModel.GetConstantValue(e).Value).ToArray();

			if (expression is ArrayCreationExpressionSyntax { Initializer.Expressions: var arrayValues })
				return arrayValues.Select(e => semanticModel.GetConstantValue(e).Value).ToArray();

			if (expression is CollectionExpressionSyntax { Elements: var elements })
				return elements
					.OfType<ExpressionElementSyntax>()
					.Select(e => semanticModel.GetConstantValue(e.Expression).Value)
					.ToArray();

			return semanticModel.GetConstantValue(expression).Value;
		}

		static bool IsAspectAttributeName(string name)
		{
			return name is "Aspect" or "AspectAttribute" or "AspectGenerator.Aspect" or "AspectGenerator.AspectAttribute";
		}

		static bool IsHookName(string name)
		{
			return name is
				"OnInit"            or
				"OnUsing"           or
				"OnUsingAsync"      or
				"OnBeforeCall"      or
				"OnBeforeCallAsync" or
				"OnCall"            or
				"OnAfterCall"       or
				"OnAfterCallAsync"  or
				"OnCatch"           or
				"OnCatchAsync"      or
				"OnFinally"         or
				"OnFinallyAsync";
		}

		static bool HasNamedArgument(AttributeSyntax attribute, string name)
		{
			return attribute.ArgumentList?.Arguments.Any(a => a.NameEquals?.Name.Identifier.ValueText == name) == true;
		}

		static void GenerateSource(
			SourceProductionContext                         spc,
			Compilation                                     compilation,
			GeneratorExecutionOptions                       options,
			ImmutableArray<AnalyzedInvocation>              aspectedMethods)
		{
			var interceptorsNamespace = GetInterceptorsNamespace(options);

			// Generate source. One file for all the interceptors.
			// Interceptors.g.cs
			//
			var sb = new StringBuilder(
				$$"""
				// <auto-generated/>
				#pragma warning disable
				#nullable enable

				using System;

				using SR  = System.Reflection;
				using SLE = System.Linq.Expressions;
				using SCG = System.Collections.Generic;

				namespace System.Runtime.CompilerServices
				{
					[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
					file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
					{
					}
				}

				namespace {{interceptorsNamespace}}
				{
					using AspectGenerator = AspectGenerator;

					file static class AspectGeneratorInterceptors
					{
						static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
						{
							return expr switch
							{
								SLE.MethodCallExpression mc => mc.Method,
								_                           => throw new InvalidOperationException()
							};
						}

						static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
						static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);


				""");

			var nameCounter = 0;
			var nameSet     = new HashSet<string>();

			string GetInterceptorName(string methodName)
			{
				return nameSet.Add(methodName) ? methodName : GetInterceptorName($"{methodName}_{++nameCounter}");
			}

			foreach (var m in aspectedMethods.GroupBy(m => m.Method, SymbolEqualityComparer.Default).OrderBy(m => m.Key!.Name))
			{
				var method          = (IMethodSymbol)m.Key!;
				var interceptorName = GetInterceptorName($"{method.Name}_Interceptor");
				var methods         = m.ToList();
				var attributes      = methods[0].Attributes;

				if (attributes.Any(a => a.AttributeData?.NamedArguments.Any(na => na.Key == "Order") is true))
				{
					attributes =
						(
							from a in attributes
							let o = a.AttributeData?.NamedArguments.Select(na => (KeyValuePair<string,TypedConstant>?)na).FirstOrDefault(na => na!.Value.Key == "Order")
							let n = o is null ? int.MaxValue : o.Value.Value.Value switch
							{
								string s => int.TryParse(s, out var n) ? n : null,
								int    n => (int?)n,
								_        => null
							}
							orderby n
							select a
						)
						.ToList();
				}

				foreach (var p in method.Parameters)
				{
					switch (p.RefKind)
					{
						case RefKind.Ref :
						case RefKind.Out :
						case RefKind.In  :
							sb.AppendLine(
								$$"""
										static {{p.Type, -30}} {{interceptorName}}_Arg_{{p.Name, -13}} = default({{p.Type}});
								""");
							break;
					}
				}

				sb.AppendLine(
					$$"""
							static SR. MemberInfo                 {{interceptorName}}_MemberInfo        = MethodOf{{GetMethodOf(method, interceptorName)}};
					""");

				for (var i = 0; i < attributes.Count; i++)
				{
					var attr = attributes[i];

					sb
						.AppendLine(
							$$"""
									static SCG.Dictionary<string,object?> {{interceptorName}}_AspectArguments_{{i}} = new()
									{
							""")
						;

					if (attr.AttributeData is not null)
						foreach (var arg in attr.AttributeData.NamedArguments)
						{
							string value;

							if (arg.Value.Type is IArrayTypeSymbol arrayType)
							{
								value = arg.Value.Values.Length switch
								{
									0 => $"new {arrayType.ElementType}[0]",
									_ => $"new {arg.Value.Type} {{ {arg.Value.Values.Select(v => PrintValue(v.Value, arrayType.ElementType)).Aggregate((v1, v2) => $"{v1}, {v2}")} }}"
								};
							}
							else
								value = PrintValue(arg.Value.Value, arg.Value.Type);

							sb
								.AppendLine(
									$$"""
												["{{arg.Key}}"] = {{value}},
									""")
								;

						}

					sb
						.AppendLine(
							"""
									};
							""")
						;
				}

				sb.AppendLine(
					$$"""
							//
							/// <summary>
							/// Intercepts {{method}}.
							/// </summary>
							//
					""");

				foreach (var analyzedInvocation in methods)
				{
					var inv = analyzedInvocation.Inv;

					sb.AppendLine(
						$"""
								// Intercepts {inv}.
						""");

					void AppendInterceptsLocation(InvocationExpressionSyntax invocation)
					{
						var semantic = compilation.GetSemanticModel(invocation.SyntaxTree);

#pragma warning disable RSEXPERIMENTAL002
						var location = semantic.GetInterceptableLocation(invocation, spc.CancellationToken);
#pragma warning restore RSEXPERIMENTAL002

						if (location is null)
						{
							var descriptor = new DiagnosticDescriptor(
								DiagnosticID.CannotIntercept,
								"AspectGenerator",
								$"Invocation '{invocation}' cannot be intercepted by the compiler.",
								"AspectGenerator",
								DiagnosticSeverity.Warning,
								true);

							spc.ReportDiagnostic(
								Diagnostic.Create(descriptor, invocation.GetLocation()));
							return;
						}

						sb.Append("\t\t").AppendLine(location.GetInterceptsLocationAttributeSyntax());
					}

					switch (inv.Expression)
					{
						case MemberAccessExpressionSyntax : AppendInterceptsLocation(inv); break;
						case IdentifierNameSyntax         : AppendInterceptsLocation(inv); break;
						default :
							sb.AppendLine(
								$"""
										#error Unknown expression type {inv.Expression.GetType()} for : {inv.Expression}
								""");
							break;
					}

					sb.AppendLine(
						"""
								//
						""");
				}

				sb.AppendLine("\t\t[System.Runtime.CompilerServices.CompilerGenerated]");

				if (options.DebuggerStepThrough)
					sb.AppendLine("\t\t[System.Diagnostics.DebuggerStepThrough]");

				sb.Append("\t\tpublic static ");

				var methodModifierPosition = sb.Length;

				sb
					.AppendLine(
						$$"""
						{{PrintType(method.ReturnType)}} {{interceptorName}}({{PrintParameters(method)}})
								{
						""")
					;

				GenerateMethodBody(spc, sb, methods[0].Inv, method, interceptorName, attributes, methodModifierPosition);

				sb
					.AppendLine(
						"""
								}
						""")
					.AppendLine();
			}

			TrimEnd(sb);

			sb
				.AppendLine(
					"""
						}
					}
					""");

			spc.AddSource("Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		}

		static void ValidateAspectHooksForMethod(
			List<DiagnosticInfo>    diagnostics,
			Compilation             compilation,
			InvocationExpressionSyntax invocationExpression,
			IMethodSymbol           targetMethod,
			List<AttributeInfo>     attributes,
			HashSet<string>         reportedDiagnostics)
		{
			var targetIsAsync = IsSupportedAsyncReturnType(targetMethod.ReturnType, out var asyncResultType);

			for (var idx = 0; idx < attributes.Count; idx++)
			{
				var attribute       = attributes[idx];
				var aspectArguments = GetAspectArguments(attribute).ToDictionary(static a => a.Key, static a => a.Value);
				var useInterceptData = aspectArguments.TryGetValue("UseInterceptData", out var useData) && useData is true;

				if (idx < attributes.Count - 1 &&
					aspectArguments.TryGetValue("OnCall", out var onCallValue) &&
					onCallValue is string onCall &&
					!string.IsNullOrWhiteSpace(onCall))
				{
					if (attribute.AttributeData?.ApplicationSyntaxReference is {} asr)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.OnCallNotLastAspect,
							$"Aspect '{attribute.AttributeClass}' specifies 'OnCall' interceptor and has to be the last one in aspect list.",
							Location.Create(asr.SyntaxTree, asr.Span));
					}
					else
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.OnCallNotLastMethod,
							$"Method '{targetMethod}' is decorated with an aspect that specifies 'OnCall' interceptor. This aspect has to be the last one in aspect list.",
							Location.Create(invocationExpression.SyntaxTree, invocationExpression.Span));
					}
				}

				foreach (var hook in GetHookContracts())
				{
					if (!aspectArguments.TryGetValue(hook.Name, out var hookNameValue) ||
						hookNameValue is not string hookName ||
						string.IsNullOrWhiteSpace(hookName))
						continue;

					var location = GetHookLocation(attribute, hook.Name, invocationExpression);

					if (hook.IsAsync && !targetIsAsync && !HasSyncFallback(aspectArguments, hook.Name))
					{
						var asyncVoidMessage = targetMethod is { IsAsync: true, ReturnsVoid: true }
							? " Async void target methods are not supported."
							: "";

						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.AsyncHookRequiresTask,
							$"Async hook '{hook.Name}' requires target method '{targetMethod.ToDisplayString()}' to return Task, Task<T>, ValueTask, or ValueTask<T>, or a synchronous fallback hook to be specified.{asyncVoidMessage}",
							location);
					}

					var methods       = attribute.AttributeClass.GetMembers(hookName).OfType<IMethodSymbol>().ToArray();
					var staticMethods = methods.Where(static m => m.IsStatic).ToArray();

					if (methods.Length == 0)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotFound,
							$"Aspect hook method '{hookName}' was not found on aspect type '{attribute.AttributeClass.ToDisplayString()}'.",
							location);
						continue;
					}

					if (staticMethods.Length == 0)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotStatic,
							$"Aspect hook method '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' must be static.",
							location);
						continue;
					}

					if (hook.Name == "OnCall")
					{
						if (!staticMethods.Any(m => IsValidOnCallHook(compilation, m, targetMethod, targetIsAsync, asyncResultType)))
						{
							ReportDiagnostic(
								diagnostics,
								reportedDiagnostics,
								DiagnosticID.OnCallHookMismatch,
								$"OnCall hook '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' must match target method '{targetMethod.ToDisplayString()}'.",
								location);
						}

						continue;
					}

					var methodsWithValidParameters = staticMethods
						.Where(m => IsValidLifecycleHookParameter(m, targetMethod, targetIsAsync, asyncResultType, useInterceptData))
						.ToArray();

					if (methodsWithValidParameters.Length == 0)
					{
						var diagnosticId = useInterceptData ? DiagnosticID.HookRequiresInterceptData : DiagnosticID.HookInvalidParameters;

						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							diagnosticId,
							diagnosticId == DiagnosticID.HookRequiresInterceptData
								? $"UseInterceptData=true requires hook method '{hookName}' to accept ref InterceptData<T> for '{hook.Name}'. Candidates: {string.Join("; ", staticMethods.Select(static m => m.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)))}."
								: $"Hook method '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' has an invalid parameter list for '{hook.Name}'. Candidates: {string.Join("; ", staticMethods.Select(static m => m.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)))}.",
							location);
						continue;
					}

					if (!methodsWithValidParameters.Any(m => IsValidLifecycleHookReturnType(compilation, m, hook, targetMethod, targetIsAsync, asyncResultType, useInterceptData)))
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookInvalidReturnType,
							$"Hook method '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' has an invalid return type for '{hook.Name}'.",
							location);
					}
				}
			}

			static bool HasSyncFallback(Dictionary<string,object?> aspectArguments, string asyncHookName)
			{
				var syncHookName = asyncHookName.EndsWith("Async", StringComparison.Ordinal)
					? asyncHookName[..^5]
					: asyncHookName;

				return syncHookName != asyncHookName &&
					aspectArguments.TryGetValue(syncHookName, out var value) &&
					value is string s &&
					!string.IsNullOrWhiteSpace(s);
			}
		}

		readonly record struct HookContract(string Name, bool IsAsync);

		static IEnumerable<HookContract> GetHookContracts()
		{
			yield return new("OnInit",            false);
			yield return new("OnUsing",           false);
			yield return new("OnUsingAsync",      true);
			yield return new("OnBeforeCall",      false);
			yield return new("OnBeforeCallAsync", true);
			yield return new("OnCall",            false);
			yield return new("OnAfterCall",       false);
			yield return new("OnAfterCallAsync",  true);
			yield return new("OnCatch",           false);
			yield return new("OnCatchAsync",      true);
			yield return new("OnFinally",         false);
			yield return new("OnFinallyAsync",    true);
		}

		static Location GetHookLocation(AttributeInfo attribute, string hookName, InvocationExpressionSyntax invocationExpression)
		{
			if (attribute is { AspectAttributeSyntax: {} syntax, AspectSemanticModel: not null })
			{
				foreach (var arg in syntax.ArgumentList?.Arguments ?? default)
					if (arg.NameEquals?.Name.Identifier.ValueText == hookName)
						return arg.Expression.GetLocation();
			}

			if (attribute.AspectAttributeData?.ApplicationSyntaxReference is {} aspectSyntaxReference)
				return Location.Create(aspectSyntaxReference.SyntaxTree, aspectSyntaxReference.Span);

			if (attribute.AttributeData?.ApplicationSyntaxReference is {} attributeSyntaxReference)
				return Location.Create(attributeSyntaxReference.SyntaxTree, attributeSyntaxReference.Span);

			return invocationExpression.GetLocation();
		}

		static bool IsValidLifecycleHookParameter(
			IMethodSymbol hookMethod,
			IMethodSymbol targetMethod,
			bool          targetIsAsync,
			ITypeSymbol?  asyncResultType,
			bool          useInterceptData)
		{
			if (hookMethod.Parameters.Length != 1)
				return false;

			var parameter = hookMethod.Parameters[0];

			if (useInterceptData)
			{
				if (parameter.RefKind != RefKind.Ref)
					return false;

				return IsInterceptDataType(parameter.Type, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType));
			}

			return parameter.RefKind == RefKind.None &&
				(parameter.Type.TypeKind == TypeKind.Dynamic ||
				IsInterceptInfoType(parameter.Type, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType), allowNonGeneric: true));
		}

		static bool IsValidLifecycleHookReturnType(
			Compilation   compilation,
			IMethodSymbol hookMethod,
			HookContract  hook,
			IMethodSymbol targetMethod,
			bool          targetIsAsync,
			ITypeSymbol?  asyncResultType,
			bool          useInterceptData)
		{
			if (hook.Name == "OnInit")
				return useInterceptData
					? IsInterceptDataType(hookMethod.ReturnType, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType))
					: IsInterceptInfoType(hookMethod.ReturnType, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType), allowNonGeneric: false);

			if (hook.Name == "OnUsing")
				return ImplementsType(hookMethod.ReturnType, "System.IDisposable");

			if (hook.Name == "OnUsingAsync")
				return ImplementsType(hookMethod.ReturnType, "System.IAsyncDisposable");

			if (hook.IsAsync)
				return IsSupportedAsyncReturnType(hookMethod.ReturnType, out _);

			return hookMethod.ReturnsVoid;
		}

		static bool IsValidOnCallHook(
			Compilation   compilation,
			IMethodSymbol hookMethod,
			IMethodSymbol targetMethod,
			bool          targetIsAsync,
			ITypeSymbol?  asyncResultType)
		{
			var expectedParameters = GetOnCallParameters(targetMethod).ToArray();

			if (hookMethod.Parameters.Length != expectedParameters.Length)
				return false;

			for (var i = 0; i < expectedParameters.Length; i++)
			{
				var actual   = hookMethod.Parameters[i];
				var expected = expectedParameters[i];

				if (actual.RefKind != expected.RefKind)
					return false;

				if (!SymbolEqualityComparer.Default.Equals(actual.Type, expected.Type))
					return false;
			}

			if (targetMethod.ReturnsVoid)
				return hookMethod.ReturnsVoid;

			if (targetIsAsync)
				return IsSupportedAsyncReturnType(hookMethod.ReturnType, out var hookAsyncResultType) &&
					(asyncResultType is null && hookAsyncResultType is null ||
					 asyncResultType is not null &&
					 hookAsyncResultType is not null &&
					 SymbolEqualityComparer.Default.Equals(asyncResultType, hookAsyncResultType));

			return compilation.ClassifyConversion(hookMethod.ReturnType, targetMethod.ReturnType).IsImplicit;
		}

		static IEnumerable<(ITypeSymbol Type, RefKind RefKind)> GetOnCallParameters(IMethodSymbol targetMethod)
		{
			if (targetMethod.IsExtensionMethod || !targetMethod.IsStatic)
			{
				var receiverType = targetMethod.ReceiverType ?? targetMethod.ContainingType;

				if (receiverType is not null)
					yield return (receiverType, RefKind.None);
			}

			foreach (var parameter in targetMethod.Parameters)
				yield return (parameter.Type, parameter.RefKind);
		}

		static (ITypeSymbol? Type, bool IsVoid) GetHookReturnValueType(IMethodSymbol targetMethod, bool targetIsAsync, ITypeSymbol? asyncResultType)
		{
			if (targetMethod.ReturnsVoid || targetIsAsync && asyncResultType is null)
				return (null, true);

			return targetIsAsync ? (asyncResultType, false) : (targetMethod.ReturnType, false);
		}

		static bool IsInterceptInfoType(
			ITypeSymbol                    type,
			IMethodSymbol                  hookMethod,
			(ITypeSymbol? Type, bool IsVoid) expectedValueType,
			bool                           allowNonGeneric)
		{
			if (type is not INamedTypeSymbol namedType)
				return false;

			if (!IsAspectGeneratorType(namedType, "InterceptInfo"))
				return IsUnresolvedCarrierType(type, "InterceptInfo", allowNonGeneric);

			if (namedType.Arity == 0)
				return allowNonGeneric;

			return namedType is { Arity: 1, TypeArguments: [var valueType] } &&
				TypeArgumentMatches(valueType, hookMethod, expectedValueType);
		}

		static bool IsInterceptDataType(
			ITypeSymbol                    type,
			IMethodSymbol                  hookMethod,
			(ITypeSymbol? Type, bool IsVoid) expectedValueType)
		{
			if (type is not INamedTypeSymbol namedType)
				return false;

			if (!IsAspectGeneratorType(namedType, "InterceptData"))
				return IsUnresolvedCarrierType(type, "InterceptData", allowNonGeneric: false);

			return namedType is { Arity: 1, TypeArguments: [var valueType] } &&
				TypeArgumentMatches(valueType, hookMethod, expectedValueType);
		}

		static bool IsUnresolvedCarrierType(ITypeSymbol type, string name, bool allowNonGeneric)
		{
			var displayName = type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);

			return allowNonGeneric && displayName == name ||
				displayName.StartsWith(name + "<", StringComparison.Ordinal);
		}

		static bool TypeArgumentMatches(
			ITypeSymbol                    type,
			IMethodSymbol                  hookMethod,
			(ITypeSymbol? Type, bool IsVoid) expectedValueType)
		{
			if (type is ITypeParameterSymbol typeParameter &&
				SymbolEqualityComparer.Default.Equals(typeParameter.ContainingSymbol, hookMethod))
				return true;

			if (expectedValueType.IsVoid)
				return type.SpecialType == SpecialType.System_Void ||
					type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat) == "System.Void" ||
					type is INamedTypeSymbol namedType && IsAspectGeneratorType(namedType, "Void");

			return expectedValueType.Type is not null &&
				SymbolEqualityComparer.Default.Equals(type, expectedValueType.Type);
		}

		static bool IsAspectGeneratorType(INamedTypeSymbol type, string name)
		{
			if (type.Name != name)
				return false;

			var @namespace = type.ContainingNamespace.ToDisplayString();

			return @namespace is "" or "AspectGenerator";
		}

		static bool IsSupportedAsyncReturnType(ITypeSymbol type, out ITypeSymbol? resultType)
		{
			resultType = null;

			if (type is not INamedTypeSymbol namedType ||
				namedType.Name is not ("Task" or "ValueTask") ||
				namedType.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
				return false;

			if (namedType is { IsGenericType: true, TypeArguments: [var asyncResultType] })
				resultType = asyncResultType;

			return true;
		}

		static bool ImplementsType(ITypeSymbol type, string metadataName)
		{
			return IsType(type, metadataName) ||
				type.AllInterfaces.Any(i => IsType(i, metadataName));
		}

		static bool IsType(ITypeSymbol type, string metadataName)
		{
			if (type is not INamedTypeSymbol namedType)
				return false;

			return namedType.ContainingNamespace.ToDisplayString() + "." + namedType.Name == metadataName;
		}

		static void GenerateMethodBody(
			SourceProductionContext    spc,
			StringBuilder              sb,
			InvocationExpressionSyntax invocationExpression,
			IMethodSymbol              method,
			string                     interceptorName,
			List<AttributeInfo>        attributes,
			int                        methodModifierPosition)
		{
			var isReturnsAsyncType = IsSupportedAsyncReturnType(method.ReturnType, out var asyncResultType);
			var generateAsync      = isReturnsAsyncType && attributes.Any(d => GetAspectArguments(d).Any(a => a.Key.EndsWith("Async") && a.Value is not null));
			var generateArgs       = attributes.Any(d => GetAspectArguments(d).Any(a => a is { Key: "PassArguments", Value: true }));

			// Generate arguments.
			//
			if (generateArgs)
			{
				sb.Append("\t\t\tvar __args__ = new object?[] { ");

				if (method.IsStatic == false)
					sb.Append("__this__, ");

				foreach (var p in method.Parameters)
					sb.Append(p.Name).Append(p.RefKind == RefKind.Out ? " = default, " : ", ");

				while (sb[^1] is ' ' or ',')
					sb.Length--;

				sb.Append(" };").AppendLine().AppendLine();
			}

			GenerateAttribute(0, "\t\t\t", false);

			void GenerateAttribute(int idx, string indent, bool isPrevData)
			{
				var attr   = attributes[idx].AttributeClass!;

				// Get aspect attribute parameters.
				//
				object? onInit           = null;
				object? onUsing          = null; object? onUsingAsync      = null;
				object? onBeforeCall     = null; object? onBeforeCallAsync = null;
				object? onCall           = null;
				object? onAfterCall      = null; object? onAfterCallAsync  = null;
				object? onCatch          = null; object? onCatchAsync      = null;
				object? onFinally        = null; object? onFinallyAsync    = null;
				var     useInterceptType = false;
				var     passArguments    = false;
				var     useInterceptData = false;
				var     needInfo         = attributes.Count > 1 || generateAsync;

				foreach (var arg in GetAspectArguments(attributes[idx]))
					switch (arg.Key)
					{
						case "OnInit"            : onInit            = arg.Value; needInfo = true; break;
						case "OnUsing"           : onUsing           = arg.Value; needInfo = true; break;
						case "OnUsingAsync"      : onUsingAsync      = arg.Value; needInfo = true; break;
						case "OnBeforeCall"      : onBeforeCall      = arg.Value; needInfo = true; break;
						case "OnBeforeCallAsync" : onBeforeCallAsync = arg.Value; needInfo = true; break;
						case "OnCall"            : onCall            = arg.Value;                  break;
						case "OnAfterCall"       : onAfterCall       = arg.Value; needInfo = true; break;
						case "OnAfterCallAsync"  : onAfterCallAsync  = arg.Value; needInfo = true; break;
						case "OnCatch"           : onCatch           = arg.Value; needInfo = true; break;
						case "OnCatchAsync"      : onCatchAsync      = arg.Value; needInfo = true; break;
						case "OnFinally"         : onFinally         = arg.Value; needInfo = true; break;
						case "OnFinallyAsync"    : onFinallyAsync    = arg.Value; needInfo = true; break;
						case "UseInterceptType"  : useInterceptType  = arg.Value is true; break;
						case "PassArguments"     : passArguments     = arg.Value is true; break;
						case "UseInterceptData"  : useInterceptData  = arg.Value is true; break;
					}

				if (generateAsync)
					sb.Insert(methodModifierPosition, "async ");

				var returnType = generateAsync ? asyncResultType?.ToString() ?? "AspectGenerator.Void" : method.ReturnsVoid ? "AspectGenerator.Void" : $"{method.ReturnType}";

				// Generate AspectCallInfo.
				//
				if (needInfo)
				{
					sb
						.Append(indent).AppendLine($"// {(object?)attributes[idx].AttributeData ?? attributes[idx].AttributeClass}")
						.Append(indent).AppendLine("//")
						//.Append(indent).Append($"var __attr__{idx} = new {attributes[idx]}").Append(attributes[idx].NamedArguments.Length == 0 ? "()" : "").AppendLine(";")
						.Append(indent).AppendLine($"var __info__{idx} = new AspectGenerator.Intercept{(useInterceptData ? "Data" : "Info")}<{returnType}>")
						.Append(indent).AppendLine("{")
						//.Append(indent).AppendLine($"\tReturnValue     = {(idx > 0 ? $"__info__{idx - 1}.ReturnValue" : $"default({(method.ReturnsVoid ? "Void" : $"{method.ReturnType}")})")},")
						.Append(indent).AppendLine($"\tMemberInfo      = {interceptorName}_MemberInfo,")
						.Append(indent).AppendLine($"\tAspectType      = typeof({attr}),")
						.Append(indent).AppendLine($"\tAspectArguments = {interceptorName}_AspectArguments_{idx},")
						;

					if (passArguments)
						sb
							.Append(indent).AppendLine("\tMethodArguments = __args__,")
							;

					if (idx > 0 && !isPrevData)
						sb.Append(indent).AppendLine($"\tPreviousInfo    = __info__{idx - 1}");

					sb
						.Append(indent).AppendLine("};")
						.AppendLine()
						;
				}

				// Generate OnInit.
				//
				if (onInit is not null)
				{
					GenerateInterceptType("", "OnInit")
						.Append(indent).AppendLine($"__info__{idx} = {attr.ContainingNamespace}.{attr.Name}.{onInit}({PassInfo(idx)});")
						.AppendLine()
						;
				}

				// Generate OnUsing.
				//
				if (generateAsync && onUsingAsync is not null || onUsing is not null)
				{
					var isAsync = generateAsync && onUsingAsync != null;
					GenerateInterceptType("", "OnUsing")
						.Append(indent).AppendLine($"{(isAsync ? "await " : "")}using ({attr.ContainingNamespace}.{attr.Name}.{(isAsync ? onUsingAsync : onUsing)}({PassInfo(idx)}))")
						.Append(indent).AppendLine("{")
						;
					indent += '\t';
				}

				// If OnCatch or OnFinally is defined, generate try/catch/finally block.
				//
				if (generateAsync && onCatchAsync   is not null || onCatch   is not null ||
					generateAsync && onFinallyAsync is not null || onFinally is not null)
				{
					sb.Append(indent).AppendLine("try");
					sb.Append(indent).AppendLine("{");
					indent += '\t';
				}

				// Generate OnBeforeCall.
				//
				if (generateAsync && onBeforeCallAsync is not null || onBeforeCall is not null)
				{
					GenerateInterceptType("", "OnBeforeCall");
					GenerateMethodCall(onBeforeCallAsync, onBeforeCall)
						.AppendLine()
						.Append(indent).AppendLine($"if (__info__{idx}.InterceptResult != AspectGenerator.InterceptResult.Return)")
						.Append(indent).AppendLine("{")
						;

					indent += '\t';
				}

				// Generate next attribute...
				//
				if (idx < attributes.Count - 1)
				{
					sb.Append(indent).AppendLine("{");

					GenerateAttribute(idx + 1, indent + '\t', useInterceptData);

					TrimEnd(sb);

					sb
						.Append(indent).AppendLine("}")
						.AppendLine()
						;
				}
				// .. or call the target method.
				//
				else
				{
					sb
						.Append(indent)
						.Append(
							method.ReturnsVoid || isReturnsAsyncType && asyncResultType is null
								? string.Empty
								: $"{(needInfo ? $"__info__{idx}.ReturnValue" : "var __return__")} = {(generateAsync ? "await " : "")}")
						.Append(
							onCall is null
								? method.IsExtensionMethod || method.IsStatic
									? method.OriginalDefinition.ContainingType
									: "__this__"
								: $"{attr.ContainingNamespace}.{attr.Name}")
						.Append('.')
						.Append(onCall ?? method.Name)
						.Append('(')
						;

					if (method.IsExtensionMethod || onCall is not null && method.IsStatic is false)
					{
						sb.Append("__this__");

						if (method.Parameters.Length > 0)
							sb.Append(", ");
					}

					foreach (var p in method.Parameters)
					{
						sb
							.Append(
								p.RefKind switch
								{
									RefKind.Ref => "ref ",
									RefKind.Out => "out ",
									RefKind.In  => "in ",
									_           => ""
								})
							.Append(p.Name)
							.Append(", ");
					}

					if (method.Parameters.Length > 0)
						sb.Length -= 2;

					sb
						.AppendLine(");")
						.AppendLine()
						;
				}

				// Generate OnAfterCall.
				//
				if (generateAsync && onAfterCallAsync is not null || onAfterCall is not null)
				{
					GenerateInterceptType("", "OnAfterCall");
					GenerateMethodCall(onAfterCallAsync, onAfterCall)
						.AppendLine();
				}

				// Generate OnBeforeCall end.
				//
				if (generateAsync && onBeforeCallAsync is not null || onBeforeCall is not null)
				{
					TrimEnd(sb);

					indent = indent[..^1];

					sb
						.Append(indent)
						.AppendLine("}")
						.AppendLine()
						;
				}

				// If OnCatch or OnFinally is defined, generate try/catch/finally block end.
				//
				if (generateAsync && onCatchAsync   is not null || onCatch   is not null ||
					generateAsync && onFinallyAsync is not null || onFinally is not null)
				{
					indent = indent[..^1];

					TrimEnd(sb);

					sb.AppendLine($"{indent}}}");

					// Generate OnCatch.
					//
					sb
						.Append(indent).AppendLine("catch (Exception __ex__)")
						.Append(indent).AppendLine("{")
						.Append(indent).AppendLine($"\t__info__{idx}.Exception{(onCatch is null ? null : "      ")} = __ex__;")
						;

					if (generateAsync && onCatchAsync is not null || onCatch is not null)
					{
						sb.Append(indent).AppendLine($"\t__info__{idx}.InterceptResult = AspectGenerator.InterceptResult.ReThrow;");

						GenerateInterceptType("\t", "OnCatch")
							.AppendLine()
							.Append('\t')
							;

						GenerateMethodCall(onCatchAsync, onCatch)
							.AppendLine()
							.Append(indent).AppendLine($"\tif (__info__{idx}.InterceptResult == AspectGenerator.InterceptResult.ReThrow)")
							.Append(indent).AppendLine("\t\tthrow;")
							;
					}
					else
					{
						sb.Append(indent).AppendLine("\tthrow;");
					}

					sb.Append(indent).AppendLine("}");

					// Generate OnFinally.
					//
					if (generateAsync && onFinallyAsync is not null || onFinally is not null)
					{
						sb
							.Append(indent).AppendLine("finally")
							.Append(indent).AppendLine("{");

						GenerateInterceptType("\t", "OnFinally")
							.Append('\t')
							;

						GenerateMethodCall(onFinallyAsync, onFinally)
							.Append(indent).AppendLine("}")
							;
					}

					sb.AppendLine();
				}

				// Generate OnUsing.
				//
				if (generateAsync && onUsingAsync is not null || onUsing is not null)
				{
					indent = indent[..^1];

					TrimEnd(sb);

					sb
						.Append(indent)
						.AppendLine("}")
						.AppendLine()
						;
				}

				// Generate return.
				//
				if (idx > 0)
					sb.Append(indent).AppendLine($"__info__{idx - 1}.ReturnValue = __info__{idx}.ReturnValue;");
				else if (!(method.ReturnsVoid || isReturnsAsyncType && asyncResultType is null))
					sb.AppendLine($"\t\t\treturn {(needInfo ? $"__info__{idx}.ReturnValue" : "__return__")};");

				TrimEnd(sb);

				string PassInfo(int idx)
				{
					return $"{(useInterceptData ? "ref " : "")}__info__{idx}";
				}

				StringBuilder GenerateMethodCall(object? onAsync, object? call)
				{
					if (generateAsync && onAsync is not null)
						return sb.Append(indent).AppendLine($"await {attr.ContainingNamespace}.{attr.Name}.{onAsync}({PassInfo(idx)});");
					return sb.Append(indent).AppendLine($"{attr.ContainingNamespace}.{attr.Name}.{call}({PassInfo(idx)});");
				}

				StringBuilder GenerateInterceptType(string additionalIndent, string interceptType)
				{
					if (useInterceptType)
					{
						sb
							.Append(additionalIndent)
							.Append(indent)
							.AppendLine($"__info__{idx}.InterceptType = AspectGenerator.InterceptType.{interceptType};");
					}

					return sb;
				}
			}
		}

		static void TrimEnd(StringBuilder sb)
		{
			while (sb[^1] is '\r' or '\n')
				sb.Length--;

			sb.AppendLine();
		}

		static string PrintValue(object? val, ITypeSymbol? type)
		{
			if (val is null)
				return "null";

			if (type?.TypeKind == TypeKind.Enum)
				return $"({type}){PrintValue(val, null)}";

			return val switch
			{
				string           s => SymbolDisplay.FormatLiteral(s, quote: true),
				char             c => SymbolDisplay.FormatLiteral(c, quote: true),
				bool             b => b ? "true" : "false",
				byte             b => b.ToString(CultureInfo.InvariantCulture),
				sbyte            b => b.ToString(CultureInfo.InvariantCulture),
				short            n => n.ToString(CultureInfo.InvariantCulture),
				ushort           n => n.ToString(CultureInfo.InvariantCulture),
				int              n => n.ToString(CultureInfo.InvariantCulture),
				uint             n => n.ToString(CultureInfo.InvariantCulture) + "u",
				long             n => n.ToString(CultureInfo.InvariantCulture) + "L",
				ulong            n => n.ToString(CultureInfo.InvariantCulture) + "uL",
				float            f => PrintSingle(f),
				double           d => PrintDouble(d),
				decimal          d => d.ToString(CultureInfo.InvariantCulture) + "m",
				INamedTypeSymbol s => $"typeof({s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})",
				_                  => Convert.ToString(val, CultureInfo.InvariantCulture) ?? "null"
			};

			static string PrintSingle(float value)
			{
				if (float.IsNaN(value))
					return "float.NaN";
				if (float.IsPositiveInfinity(value))
					return "float.PositiveInfinity";
				if (float.IsNegativeInfinity(value))
					return "float.NegativeInfinity";

				return value.ToString("R", CultureInfo.InvariantCulture) + "f";
			}

			static string PrintDouble(double value)
			{
				if (double.IsNaN(value))
					return "double.NaN";
				if (double.IsPositiveInfinity(value))
					return "double.PositiveInfinity";
				if (double.IsNegativeInfinity(value))
					return "double.NegativeInfinity";

				return value.ToString("R", CultureInfo.InvariantCulture) + "d";
			}
		}

		static string PrintType(ITypeSymbol type)
		{
			return $"{type}";
		}

		static string PrintParameters(IMethodSymbol method)
		{
			var parameters = method.Parameters;
			var sb         = new StringBuilder();

			if (method.IsStatic == false)
				sb.Append($"this {method.ReceiverType} __this__, ");

			foreach (var p in parameters)
				sb
					.Append(p)
					.Append(", ")
					;

			if (parameters.Length != 0 || method.IsStatic == false)
				sb.Length -= 2;

			return sb.ToString();
		}

		static string GetMethodOf(IMethodSymbol method, string interceptorName)
		{
			var sb = new StringBuilder();

			sb.Append("(() => ");

			sb
				.Append(method.IsExtensionMethod || method.IsStatic ? method.OriginalDefinition.ContainingType : $"default({method.ReceiverType})")
				.Append('.')
				.Append(method.Name)
				.Append('(')
				;

			if (method.IsExtensionMethod)
				sb.Append($"default({method.ReceiverType}), ");

			foreach (var p in method.Parameters)
				switch (p.RefKind)
				{
					case RefKind.Ref : sb.Append($"ref {interceptorName}_Arg_{p.Name}, "); break;
					case RefKind.In  : sb.Append($"in {interceptorName}_Arg_{p.Name}, ");  break;
					case RefKind.Out : sb.Append($"out {interceptorName}_Arg_{p.Name}, "); break;
					default          : sb.Append($"default({p.Type}), ");                  break;
				}

			while (sb[^1] is ',' or ' ')
				sb.Length--;

			sb.Append("))");

			return sb.ToString();
		}
	}
}
