using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace AspectGenerator
{
	[Generator(LanguageNames.CSharp)]
	public class AspectSourceGenerator : IIncrementalGenerator
	{
		// Diagnostic IDs
		public static class DiagnosticID
		{
			public const string OnCallNotLastAspect                 = AspectDiagnostics.Id.OnCallNotLastAspect;
			public const string OnCallNotLastMethod                 = AspectDiagnostics.Id.OnCallNotLastMethod;
			public const string CannotIntercept                     = AspectDiagnostics.Id.CannotIntercept;
			public const string NamespaceNotAllowed                 = AspectDiagnostics.Id.NamespaceNotAllowed;
			public const string HookMethodNotFound                  = AspectDiagnostics.Id.HookMethodNotFound;
			public const string HookMethodNotStatic                 = AspectDiagnostics.Id.HookMethodNotStatic;
			public const string HookInvalidParameters               = AspectDiagnostics.Id.HookInvalidParameters;
			public const string HookInvalidReturnType               = AspectDiagnostics.Id.HookInvalidReturnType;
			public const string OnCallHookMismatch                  = AspectDiagnostics.Id.OnCallHookMismatch;
			public const string HookRequiresInterceptData           = AspectDiagnostics.Id.HookRequiresInterceptData;
			public const string AsyncHookRequiresTask               = AspectDiagnostics.Id.AsyncHookRequiresTask;
			public const string InvalidAspectFilterRegex            = AspectDiagnostics.Id.InvalidAspectFilterRegex;
			public const string InvalidAspectFilterRule             = AspectDiagnostics.Id.InvalidAspectFilterRule;
			public const string UnknownAspectFilterConditionKey     = AspectDiagnostics.Id.UnknownAspectFilterConditionKey;
			public const string InvalidAspectFilterParameterPattern = AspectDiagnostics.Id.InvalidAspectFilterParameterPattern;
			public const string InvalidAspectFilterDottedPattern    = AspectDiagnostics.Id.InvalidAspectFilterDottedPattern;
			public const string MethodLevelTargetFilter             = AspectDiagnostics.Id.MethodLevelTargetFilter;
			public const string InterceptedCallMarker               = AspectDiagnostics.Id.InterceptedCallMarker;
		}

		public static class OptionID
		{
			public const string GenerateApi           = AspectOptionNames.GenerateApi;
			public const string PublicApi             = AspectOptionNames.PublicApi;
			public const string DebuggerStepThrough   = AspectOptionNames.DebuggerStepThrough;
			public const string ReportFile            = AspectOptionNames.ReportFile;
			public const string AspectDiagnosticSeverity = AspectOptionNames.AspectDiagnosticSeverity;
			public const string InterceptorsNamespace = AspectOptionNames.InterceptorsNamespace;
		}

		#region API

		static string GenerateAspectGeneratorOptionsApiText(bool publicApi)
		{
			var visibility = publicApi ? "public " : "";

			return
				$$"""
			// <auto-generated/>
			#pragma warning disable
			#nullable enable

			using System;

			namespace AspectGenerator
			{
				/// <summary>
				/// Specifies how AspectGenerator reports optional diagnostics.
				/// </summary>
				/// <remarks>
				/// Values except <see cref="Off"/> map directly to Microsoft.CodeAnalysis.DiagnosticSeverity.
				/// </remarks>
				{{visibility}}enum AspectDiagnosticSeverity
				{
					/// <summary>
					/// Do not report optional diagnostics.
					/// </summary>
					Off = -1,
					/// <summary>
					/// Something that is an issue, as determined by some authority, but is not surfaced through normal means.
					/// </summary>
					Hidden = 0,
					/// <summary>
					/// Information that does not indicate a problem.
					/// </summary>
					Info = 1,
					/// <summary>
					/// Something suspicious but allowed.
					/// </summary>
					Warning = 2,
					/// <summary>
					/// Something not allowed by the rules of the language or other authority.
					/// </summary>
					Error = 3,
				}

				/// <summary>
				/// Configures AspectGenerator for the current assembly.
				/// </summary>
				[AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
				{{visibility}}sealed class AspectGeneratorOptionsAttribute : Attribute
				{
					/// <summary>
					/// Gets or sets whether AspectGenerator emits the shared generated API types for this assembly.
					/// </summary>
					/// <remarks>
					/// Keep this enabled for single-project usage. Set it to <c>false</c> when the API is supplied by an aspect library referenced by this project.
					/// </remarks>
					public bool    {{OptionID.GenerateApi}}                   { get; set; } = true;
					/// <summary>
					/// Gets or sets whether generated API types are emitted as public types.
					/// </summary>
					/// <remarks>
					/// Use this for aspect-library projects that expose aspect definitions and generated API types to other projects.
					/// </remarks>
					public bool    {{OptionID.PublicApi}}                     { get; set; }
					/// <summary>
					/// Gets or sets whether generated interceptor methods are marked with <see cref="System.Diagnostics.DebuggerStepThroughAttribute"/>.
					/// </summary>
					public bool    {{OptionID.DebuggerStepThrough}}           { get; set; }
					/// <summary>
					/// Gets or sets how AspectGenerator reports optional diagnostics such as intercepted-call markers.
					/// </summary>
					/// <remarks>
					/// Set to <see cref="AspectGenerator.AspectDiagnosticSeverity.Off"/> to disable optional diagnostics.
					/// </remarks>
					public AspectDiagnosticSeverity {{OptionID.AspectDiagnosticSeverity}} { get; set; } = AspectDiagnosticSeverity.Info;
					/// <summary>
					/// Gets or sets the namespace used for generated interceptor types.
					/// </summary>
					/// <remarks>
					/// The package normally appends this namespace to the project <c>InterceptorsNamespaces</c> MSBuild property for direct package consumers.
					/// Custom build setups must ensure this namespace is listed so Roslyn can use the generated interceptors.
					/// </remarks>
					public string? {{OptionID.InterceptorsNamespace}}         { get; set; }
				}
			}

			""";
		}

		static string GenerateAspectApiText(bool publicApi)
		{
			var visibility = publicApi ? "public " : "";

			return
				$$"""
				// <auto-generated/>
				#pragma warning disable
				#nullable enable

				using System;

				namespace AspectGenerator
				{
				/// <summary>
				/// <para>Defines an aspect.</para>
				/// <para>Create a new attribute decorated with this attribute to define an aspect.</para>
				/// </summary>
				[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
				{{visibility}}sealed class AspectAttribute : Attribute
				{
					/// <summary>
					/// Gets or sets the static hook method name invoked when the aspect invocation state is initialized.
					/// </summary>
					public string?   OnInit            { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked before the target method inside a generated <c>using</c> scope.
					/// </summary>
					/// <remarks>
					/// The returned disposable value is disposed after the intercepted call completes.
					/// </remarks>
					public string?   OnUsing           { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked before an async target method inside a generated async disposal scope.
					/// </summary>
					public string?   OnUsingAsync      { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked before the target method is called.
					/// </summary>
					public string?   OnBeforeCall      { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked before a supported async target method is awaited.
					/// </summary>
					public string?   OnBeforeCallAsync { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name that replaces the target method call.
					/// </summary>
					/// <remarks>
					/// The hook signature must match the intercepted method signature and return type.
					/// </remarks>
					public string?   OnCall            { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked after the target method returns successfully.
					/// </summary>
					public string?   OnAfterCall       { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked after a supported async target method completes successfully.
					/// </summary>
					public string?   OnAfterCallAsync  { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked when the target method throws.
					/// </summary>
					/// <remarks>
					/// Set <see cref="InterceptInfo.InterceptResult"/> or <c>InterceptData&lt;T&gt;.InterceptResult</c> to control whether the exception is rethrown or ignored.
					/// </remarks>
					public string?   OnCatch           { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked when a supported async target method throws.
					/// </summary>
					public string?   OnCatchAsync      { get; set; }
					/// <summary>
					/// Gets or sets the static hook method name invoked in the generated <c>finally</c> block.
					/// </summary>
					public string?   OnFinally         { get; set; }
					/// <summary>
					/// Gets or sets the static async hook method name invoked in the generated async cleanup path.
					/// </summary>
					public string?   OnFinallyAsync    { get; set; }
					/// <summary>
					/// Gets or sets whether hook data includes the current lifecycle stage.
					/// </summary>
					public bool      UseInterceptType  { get; set; }
					/// <summary>
					/// Gets or sets whether hook data includes the intercepted method arguments.
					/// </summary>
					/// <remarks>
					/// When enabled, generated code populates <see cref="InterceptInfo.MethodArguments"/> or <c>InterceptData&lt;T&gt;.MethodArguments</c>.
					/// </remarks>
					public bool      PassArguments     { get; set; }
					/// <summary>
					/// Gets or sets whether hooks use the mutable <c>ref InterceptData&lt;T&gt;</c> carrier instead of <c>InterceptInfo&lt;T&gt;</c>.
					/// </summary>
					public bool      UseInterceptData  { get; set; }
				}

				/// <summary>
				/// Identifies the lifecycle stage currently being processed by a hook.
				/// </summary>
				{{visibility}}enum InterceptType
				{
					/// <summary>
					/// Aspect invocation state is being initialized.
					/// </summary>
					OnInit,
					/// <summary>
					/// The generated using-scope hook is being entered.
					/// </summary>
					OnUsing,
					/// <summary>
					/// The target method is about to be called.
					/// </summary>
					OnBeforeCall,
					/// <summary>
					/// The target method returned successfully.
					/// </summary>
					OnAfterCall,
					/// <summary>
					/// The target method threw an exception.
					/// </summary>
					OnCatch,
					/// <summary>
					/// The generated cleanup path is running.
					/// </summary>
					OnFinally
				}

				/// <summary>
				/// Controls how generated interceptor code continues after a hook is executed.
				/// </summary>
				{{visibility}}enum InterceptResult
				{
					/// <summary>
					/// Continue normal generated interceptor flow.
					/// </summary>
					Continue,
					/// <summary>
					/// Return the current value from the interceptor.
					/// </summary>
					Return,
					/// <summary>
					/// Alias for <see cref="Continue"/> used by exception hooks to rethrow the current exception.
					/// </summary>
					ReThrow     = Continue,
					/// <summary>
					/// Alias for <see cref="Return"/> used by exception hooks to ignore the current exception.
					/// </summary>
					IgnoreThrow = Return
				}

				/// <summary>
				/// Represents a void return value in generic hook data.
				/// </summary>
				{{visibility}}struct Void
				{
				}

				/// <summary>
				/// Provides hook data for an intercepted method.
				/// </summary>
				{{visibility}}partial class InterceptInfo
				{
					/// <summary>
					/// Gets or sets user-defined state shared between hooks in the same interception chain.
					/// </summary>
					public object?         Tag;
					/// <summary>
					/// Gets or sets the current lifecycle stage.
					/// </summary>
					public InterceptType   InterceptType;
					/// <summary>
					/// Gets or sets the requested continuation behavior for generated interceptor code.
					/// </summary>
					public InterceptResult InterceptResult;
					/// <summary>
					/// Gets or sets the current exception for catch and finally hooks.
					/// </summary>
					public Exception?      Exception;

					/// <summary>
					/// Gets or sets hook data produced by the previous aspect in the same interception chain.
					/// </summary>
					public InterceptInfo?                                        PreviousInfo;
					/// <summary>
					/// Gets or sets reflection metadata for the intercepted target method.
					/// </summary>
					public System.Reflection.MemberInfo                          MemberInfo;
					/// <summary>
					/// Gets or sets intercepted method arguments when argument capture is enabled.
					/// </summary>
					public object?[]?                                            MethodArguments;
					/// <summary>
					/// Gets or sets the applied aspect attribute type.
					/// </summary>
					public Type                                                  AspectType;
					/// <summary>
					/// Gets or sets named arguments from the applied aspect attribute.
					/// </summary>
					public System.Collections.Generic.Dictionary<string,object?> AspectArguments;
				}

				/// <summary>
				/// Provides hook data for an intercepted method with a return value.
				/// </summary>
				/// <typeparam name="T">The intercepted method return value type.</typeparam>
				{{visibility}}partial class InterceptInfo<T> : InterceptInfo
				{
					/// <summary>
					/// Gets or sets the intercepted method return value.
					/// </summary>
					public T ReturnValue;
				}

				/// <summary>
				/// Provides mutable by-reference hook data for an intercepted method.
				/// </summary>
				/// <typeparam name="T">The intercepted method return value type.</typeparam>
				{{visibility}}partial struct InterceptData<T>
				{
					/// <summary>
					/// Gets or sets user-defined state shared between hooks in the same interception chain.
					/// </summary>
					public object?         Tag;
					/// <summary>
					/// Gets or sets the current lifecycle stage.
					/// </summary>
					public InterceptType   InterceptType;
					/// <summary>
					/// Gets or sets the requested continuation behavior for generated interceptor code.
					/// </summary>
					public InterceptResult InterceptResult;
					/// <summary>
					/// Gets or sets the current exception for catch and finally hooks.
					/// </summary>
					public Exception?      Exception;

					/// <summary>
					/// Gets or sets hook data produced by the previous aspect in the same interception chain.
					/// </summary>
					public InterceptInfo<T>?                                     PreviousInfo;
					/// <summary>
					/// Gets or sets reflection metadata for the intercepted target method.
					/// </summary>
					public System.Reflection.MemberInfo                          MemberInfo;
					/// <summary>
					/// Gets or sets intercepted method arguments when argument capture is enabled.
					/// </summary>
					public object?[]?                                            MethodArguments;
					/// <summary>
					/// Gets or sets the applied aspect attribute type.
					/// </summary>
					public Type                                                  AspectType;
					/// <summary>
					/// Gets or sets named arguments from the applied aspect attribute.
					/// </summary>
					public System.Collections.Generic.Dictionary<string,object?> AspectArguments;

					/// <summary>
					/// Gets or sets the intercepted method return value.
					/// </summary>
					public T ReturnValue;
				}
			}

			""";
		}

		#endregion

		record InterceptorInfo(
			IMethodSymbol             Method,
			List<AnalyzedInvocation>  Invocations,
			string                    Name,
			List<AttributeInfo>       Attributes);

		record AnalysisResult(
			Compilation                        Compilation,
			GeneratorExecutionOptions         Options,
			ImmutableArray<AnalyzedInvocation> AspectedMethods,
			ImmutableArray<DiagnosticInfo>     Diagnostics);

		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
#if DEBUG && TRUE1
			if (!System.Diagnostics.Debugger.IsAttached)
			{
				System.Diagnostics.Debugger.Launch();
			}
#endif

			var attributes = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } c && c.AttributeLists
						.SelectMany(static l => l.Attributes)
						.Any(static a => AspectSymbols.IsAspectAttributeName(a.Name.ToString())),
					transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
				.Collect();

			var invocations = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (node, _) => node is InvocationExpressionSyntax
					{
						Expression: MemberAccessExpressionSyntax or IdentifierNameSyntax
					},
					transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node)
				.Collect();

			var options = context.AnalyzerConfigOptionsProvider.Select(static (c, _) =>
				AspectOptionsResolver.GetMSBuildOptions(c));

			var analysis = context.CompilationProvider
				.Combine(options)
				.Combine(attributes)
				.Combine(invocations)
				.Select(static (data, ct) => Analyze(data, ct));

			context.RegisterSourceOutput(analysis, ReportDiagnostics);
			context.RegisterImplementationSourceOutput(analysis, EmitInterceptors);
		}

		static AnalysisResult Analyze(
			(((Compilation Left, Options Right) Left, ImmutableArray<ClassDeclarationSyntax> Right) Left, ImmutableArray<InvocationExpressionSyntax> Right) data,
			CancellationToken cancellationToken)
		{
			var compilation = data.Left.Left.Left;
			var options     = AspectOptionsResolver.Resolve(compilation, data.Left.Left.Right);
			var attrs       = data.Left.Right;
			var invocations = data.Right;

			var diagnosticSink = new GeneratorDiagnosticSink();
			var diagnostics = diagnosticSink.Diagnostics;
			var reportedDiagnostics = new HashSet<string>();

			var registry = AspectDefinitionRegistry.Create(
				compilation,
				attrs,
				diagnosticSink,
				cancellationToken);

			ValidateAspectHooks(diagnostics, registry.AspectAttributes, reportedDiagnostics);

			var selection = new AspectSelectionService(
				compilation,
				options,
				registry,
				diagnosticSink);
			var aspectedMethods = selection.AnalyzeInvocations(invocations, cancellationToken);

			if (!cancellationToken.IsCancellationRequested)
				foreach (var m in aspectedMethods.GroupBy(static m => m.Method, SymbolEqualityComparer.Default))
					ValidateAspectHooksForMethod(diagnostics, compilation, m.First().Inv, (IMethodSymbol)m.Key!, m.First().Attributes, reportedDiagnostics);

			ReportMissingInterceptorsNamespace(diagnostics, options);

			return new AnalysisResult(compilation, options, aspectedMethods, diagnostics.ToImmutableArray());
		}

		static void ReportDiagnostics(SourceProductionContext spc, AnalysisResult analysis)
		{
			spc.AddSource("AspectGeneratorOptionsAttribute.g.cs", SourceText.From(GenerateAspectGeneratorOptionsApiText(analysis.Options.PublicApi), Encoding.UTF8));

			if (analysis.Options.GenerateApi)
				spc.AddSource("AspectAttribute.g.cs", SourceText.From(GenerateAspectApiText(analysis.Options.PublicApi), Encoding.UTF8));

			foreach (var diagnostic in analysis.Diagnostics)
			{
				spc.ReportDiagnostic(
					Diagnostic.Create(
						diagnostic.Id,
						"AspectGenerator",
						diagnostic.Message,
						diagnostic.Severity,
						diagnostic.Severity,
						true,
						diagnostic.Severity == DiagnosticSeverity.Error ? 0 : 1,
						location: diagnostic.Location));
			}

			WriteBuildReport(analysis);
		}

		#pragma warning disable RS1035 // Build reports are an explicit source-generator output channel for this package.
		static void WriteBuildReport(AnalysisResult analysis)
		{
			if (analysis.Options.DesignTimeBuild ||
				string.IsNullOrWhiteSpace(analysis.Options.ReportFile))
				return;

			try
			{
				var reportFile = GetReportFilePath(analysis.Options);
				var directory  = Path.GetDirectoryName(reportFile);

				if (!string.IsNullOrWhiteSpace(directory))
					Directory.CreateDirectory(directory);

				File.WriteAllText(reportFile, FormatBuildReport(analysis), Encoding.UTF8);
			}
			catch
			{
				// Build reports are informational and must not affect compilation.
			}
		}
		#pragma warning restore RS1035

		static string GetReportFilePath(GeneratorExecutionOptions options)
		{
			var reportFile = options.ReportFile!;

			if (Path.IsPathRooted(reportFile) ||
				string.IsNullOrWhiteSpace(options.ProjectDirectory))
				return reportFile;

			return Path.GetFullPath(Path.Combine(options.ProjectDirectory!, reportFile));
		}

		static string FormatBuildReport(AnalysisResult analysis)
		{
			var selectedCallSiteCount = analysis.AspectedMethods.Length;
			var targetMethodCount     = analysis.AspectedMethods.Select(static m => m.Method).Distinct(SymbolEqualityComparer.Default).Count();
			var interceptorState      = analysis.Options.EmitInterceptors ? "enabled" : "disabled";
			var generatedApiState     = analysis.Options.GenerateApi ? "enabled" : "disabled";
			var interceptorsNamespace = GetInterceptorsNamespace(analysis.Options);
			var interceptors          = GetInterceptorInfos(analysis.AspectedMethods);
			var sb                    = new StringBuilder();

			sb.AppendLine("# AspectGenerator Build Report");
			sb.AppendLine();
			sb.AppendLine("## Summary");
			sb.AppendLine();
			sb.AppendLine("| Item | Value |");
			sb.AppendLine("| --- | --- |");
			AppendTableRow(sb, "Project", analysis.Compilation.AssemblyName ?? analysis.Compilation.Assembly.Identity.Name);
			AppendTableRow(sb, analysis.Options.EmitInterceptors ? "Generated call sites" : "Selected call sites", selectedCallSiteCount.ToString(CultureInfo.InvariantCulture));
			AppendTableRow(sb, "Target methods", targetMethodCount.ToString(CultureInfo.InvariantCulture));
			AppendTableRow(sb, "Interceptor generation", interceptorState);
			AppendTableRow(sb, "Generated API", generatedApiState);
			AppendTableRow(sb, "Interceptors namespace", $"`{interceptorsNamespace}`");

			if (!analysis.Options.EmitInterceptors)
			{
				sb.AppendLine();
				sb.AppendLine("> No interceptor source was emitted.");
			}

			sb.AppendLine();
			sb.AppendLine("## Generated Sources");
			sb.AppendLine();
			sb.AppendLine("| Source | Details |");
			sb.AppendLine("| --- | --- |");
			AppendGeneratedSourceRow(sb, analysis.Options, "AspectGeneratorOptionsAttribute.g.cs", "Generated options API.");

			if (analysis.Options.GenerateApi)
				AppendGeneratedSourceRow(sb, analysis.Options, "AspectAttribute.g.cs", "Generated aspect authoring and runtime API.");

			if (analysis.Options.EmitInterceptors && analysis.AspectedMethods.Length > 0)
				AppendGeneratedSourceRow(sb, analysis.Options, "Interceptors.g.cs", "Generated interceptor methods for selected call sites.");

			sb.AppendLine();
			sb.AppendLine("## Target Methods");
			sb.AppendLine();

			if (interceptors.Count == 0)
			{
				sb.AppendLine("No target methods were selected.");
			}
			else
			{
				sb.AppendLine("| Target method | Generated interceptor | Aspect(s) | Call sites |");
				sb.AppendLine("| --- | --- | --- | ---: |");

				foreach (var interceptor in interceptors)
				{
					AppendTableRow(
						sb,
						$"`{FormatMarkdownCode(interceptor.Method.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat))}`",
						$"`{interceptor.Name}`",
						FormatAspectList(interceptor.Attributes),
						interceptor.Invocations.Count.ToString(CultureInfo.InvariantCulture));
				}
			}

			sb.AppendLine();
			sb.AppendLine("## Intercepted Call Sites");
			sb.AppendLine();

			if (interceptors.Count == 0)
			{
				sb.AppendLine("No call sites were selected.");
			}
			else
			{
				sb.AppendLine("| # | Source | Replaced call | Target method | Aspect(s) | Generated interceptor |");
				sb.AppendLine("| ---: | --- | --- | --- | --- | --- |");

				var index = 0;

				foreach (var interceptor in interceptors)
				{
					foreach (var invocation in interceptor.Invocations.OrderBy(static i => GetLocationSortKey(i.Inv.GetLocation()), StringComparer.Ordinal))
					{
						AppendTableRow(
							sb,
							(++index).ToString(CultureInfo.InvariantCulture),
							FormatMarkdownLocation(invocation.Inv.GetLocation()),
							$"`{FormatMarkdownCode(invocation.Inv.ToString())}`",
							$"`{FormatMarkdownCode(invocation.Method.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat))}`",
							FormatAspectList(invocation.Attributes),
							$"`{interceptor.Name}`");
					}
				}
			}

			return sb.ToString();
		}

		static void AppendGeneratedSourceRow(StringBuilder sb, GeneratorExecutionOptions options, string hintName, string details)
		{
			var source = GetGeneratedSourcePath(options, hintName) is {} path
				? FormatMarkdownLink(hintName, path)
				: $"`{hintName}`";

			AppendTableRow(sb, source, details);
		}

		static string? GetGeneratedSourcePath(GeneratorExecutionOptions options, string hintName)
		{
			if (string.IsNullOrWhiteSpace(options.CompilerGeneratedFilesOutputPath))
				return null;

			var path = options.CompilerGeneratedFilesOutputPath!;

			if (!Path.IsPathRooted(path) &&
				!string.IsNullOrWhiteSpace(options.ProjectDirectory))
				path = Path.Combine(options.ProjectDirectory!, path);

			return Path.GetFullPath(Path.Combine(path, "AspectGenerator", "AspectGenerator.AspectSourceGenerator", hintName));
		}

		static void AppendTableRow(StringBuilder sb, params string?[] values)
		{
			sb.Append("| ");
			sb.Append(string.Join(" | ", values.Select(static value => EscapeMarkdownTable(value ?? ""))));
			sb.AppendLine(" |");
		}

		static string EscapeMarkdownTable(string value)
		{
			return value
				.Replace("\\", "\\\\")
				.Replace("|", "\\|")
				.Replace("\r", "")
				.Replace("\n", "<br />");
		}

		static string FormatAspectList(IEnumerable<AttributeInfo> attributes)
		{
			return string.Join("<br />", attributes.Select(static attribute =>
				$"`{FormatMarkdownCode(attribute.AttributeClass.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat))}`"));
		}

		static string FormatMarkdownCode(string value)
		{
			return value.Replace("`", "\\`");
		}

		static string FormatMarkdownLocation(Location location)
		{
			var span = location.GetLineSpan();

			if (!span.IsValid)
				return "`unknown`";

			var path   = span.Path;
			var line   = span.StartLinePosition.Line + 1;
			var column = span.StartLinePosition.Character + 1;
			var label  = $"{Path.GetFileName(path)}:{line.ToString(CultureInfo.InvariantCulture)}:{column.ToString(CultureInfo.InvariantCulture)}";

			return FormatMarkdownLink(label, path);
		}

		static string FormatMarkdownLink(string label, string path)
		{
			return $"[{EscapeMarkdownLinkText(label)}]({new Uri(Path.GetFullPath(path)).AbsoluteUri})";
		}

		static string EscapeMarkdownLinkText(string text)
		{
			return text.Replace("[", "\\[").Replace("]", "\\]");
		}

		static string GetLocationSortKey(Location location)
		{
			var span = location.GetLineSpan();

			if (!span.IsValid)
				return "";

			return string.Concat(
				span.Path,
				":",
				span.StartLinePosition.Line.ToString("D10", CultureInfo.InvariantCulture),
				":",
				span.StartLinePosition.Character.ToString("D10", CultureInfo.InvariantCulture));
		}

		static void EmitInterceptors(SourceProductionContext spc, AnalysisResult analysis)
		{
			if (!analysis.Options.EmitInterceptors ||
				analysis.AspectedMethods.Length == 0 ||
				spc.CancellationToken.IsCancellationRequested)
				return;

			GenerateSource(spc, analysis.Compilation, analysis.Options, analysis.AspectedMethods);
		}

		static string GetInterceptorsNamespace(GeneratorExecutionOptions options)
		{
			return string.IsNullOrWhiteSpace(options.InterceptorsNamespace) ? "AspectGenerator" : options.InterceptorsNamespace!;
		}

		static void ReportMissingInterceptorsNamespace(List<DiagnosticInfo> diagnostics, GeneratorExecutionOptions options)
		{
			var interceptorsNamespace = GetInterceptorsNamespace(options);

			if (string.IsNullOrWhiteSpace(options.InterceptorsNamespaces))
			{
				diagnostics.Add(
					new DiagnosticInfo(
					DiagnosticID.NamespaceNotAllowed,
					$"InterceptorsNamespaces MSBuild property is empty. Generated interceptors namespace '{interceptorsNamespace}' must be listed there.",
					Location.None,
					DiagnosticSeverity.Warning));

				return;
			}

			var namespaces = options.InterceptorsNamespaces!
				.Split([';'], StringSplitOptions.RemoveEmptyEntries)
				.Select(static n => n.Trim());

			if (namespaces.Contains(interceptorsNamespace, StringComparer.Ordinal))
				return;

			diagnostics.Add(
				new DiagnosticInfo(
				DiagnosticID.NamespaceNotAllowed,
				$"Generated interceptors namespace '{interceptorsNamespace}' is not listed in the InterceptorsNamespaces MSBuild property.",
				Location.None,
				DiagnosticSeverity.Warning));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeInfo attribute)
		{
			if (attribute.AspectDefinitionData is {} aspectAttributeData)
				return GetAspectArguments(aspectAttributeData);

			if (attribute is { AspectDefinitionSyntax: {} syntax, AspectDefinitionSemanticModel: {} semanticModel })
				return GetAspectArguments(syntax, semanticModel);

			return [];
		}

		static void ValidateAspectHooks(
			List<DiagnosticInfo>                                                       diagnostics,
			Dictionary<ISymbol,(AttributeSyntax Syntax,SemanticModel SemanticModel)> aspectAttributes,
			HashSet<string>                                                           reportedDiagnostics)
		{
			foreach (var item in aspectAttributes)
			{
				var symbol          = item.Key;
				var aspectAttribute = item.Value;

				if (symbol is not INamedTypeSymbol aspectClass)
					continue;

				foreach (var arg in aspectAttribute.Syntax.ArgumentList?.Arguments ?? default)
				{
					if (arg.NameEquals is null || !IsHookName(arg.NameEquals.Name.Identifier.ValueText))
						continue;

					if (AspectSymbols.GetAttributeArgumentValue(arg.Expression, aspectAttribute.SemanticModel) is not string hookName || string.IsNullOrWhiteSpace(hookName))
						continue;

					var methods = aspectClass.GetMembers(hookName).OfType<IMethodSymbol>().ToArray();

					if (methods.Length == 0)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotFound,
							$"Aspect hook method '{hookName}' was not found on aspect type '{aspectClass.ToDisplayString()}'.",
							arg.Expression.GetLocation());
					}
					else if (!methods.Any(static m => m.IsStatic))
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotStatic,
							$"Aspect hook method '{hookName}' on aspect type '{aspectClass.ToDisplayString()}' must be static.",
							arg.Expression.GetLocation());
					}
				}
			}
		}

		static void ReportDiagnostic(List<DiagnosticInfo> diagnostics, HashSet<string> reportedDiagnostics, string id, string message, Location? location)
		{
			var key = $"{id}:{location?.SourceTree?.FilePath}:{location?.SourceSpan.Start}:{message}";

			if (!reportedDiagnostics.Add(key))
				return;

			diagnostics.Add(new DiagnosticInfo(id, message, location));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeData attribute)
		{
			return attribute.NamedArguments.Select(static arg => (
				arg.Key,
				arg.Value.Kind == TypedConstantKind.Array ? arg.Value.Values.Select(static v => v.Value).ToArray() : arg.Value.Value));
		}

		static IEnumerable<(string Key, object? Value)> GetAspectArguments(AttributeSyntax attribute, SemanticModel semanticModel)
		{
			foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
				if (arg.NameEquals is not null)
					yield return (arg.NameEquals.Name.Identifier.ValueText, AspectSymbols.GetAttributeArgumentValue(arg.Expression, semanticModel));
		}

		static IEnumerable<(string Key, string Value)> GetAppliedAspectArguments(AttributeInfo attribute)
		{
			if (attribute.AppliedAttributeData is not null)
			{
				foreach (var arg in attribute.AppliedAttributeData.NamedArguments)
				{
					if (arg.Key == "TargetFilter")
						continue;

					yield return (arg.Key, PrintTypedConstant(arg.Value));
				}
			}

			if (attribute is not { AppliedAttributeSyntax: {} syntax, AppliedSemanticModel: {} semanticModel })
				yield break;

			foreach (var arg in syntax.ArgumentList?.Arguments ?? default)
			{
				if (arg.NameEquals is null)
					continue;

				var name = arg.NameEquals.Name.Identifier.ValueText;

				if (name == "TargetFilter")
					continue;

				var value = AspectSymbols.GetAttributeArgumentValue(arg.Expression, semanticModel);
				var type  = semanticModel.GetTypeInfo(arg.Expression).ConvertedType ?? semanticModel.GetTypeInfo(arg.Expression).Type;

				yield return (name, PrintAttributeValue(value, type));
			}
		}

		static string PrintTypedConstant(TypedConstant value)
		{
			if (value.Type is IArrayTypeSymbol arrayType)
				return value.Values.Length switch
				{
					0 => $"new {arrayType.ElementType}[0]",
					_ => $"new {value.Type} {{ {value.Values.Select(v => PrintValue(v.Value, arrayType.ElementType)).Aggregate((v1, v2) => $"{v1}, {v2}")} }}"
				};

			return PrintValue(value.Value, value.Type);
		}

		static string PrintAttributeValue(object? value, ITypeSymbol? type)
		{
			if (type is IArrayTypeSymbol arrayType && value is object?[] values)
				return values.Length switch
				{
					0 => $"new {arrayType.ElementType}[0]",
					_ => $"new {type} {{ {values.Select(v => PrintValue(v, arrayType.ElementType)).Aggregate((v1, v2) => $"{v1}, {v2}")} }}"
				};

			return PrintValue(value, type);
		}

		static bool IsHookName(string name)
		{
			return name is
				"OnInit"            or
				"OnUsing"           or
				"OnUsingAsync"      or
				"OnBeforeCall"      or
				"OnBeforeCallAsync" or
				"OnCall"            or
				"OnAfterCall"       or
				"OnAfterCallAsync"  or
				"OnCatch"           or
				"OnCatchAsync"      or
				"OnFinally"         or
				"OnFinallyAsync";
		}

		static void GenerateSource(
			SourceProductionContext                         spc,
			Compilation                                     compilation,
			GeneratorExecutionOptions                       options,
			ImmutableArray<AnalyzedInvocation>              aspectedMethods)
		{
			var interceptorsNamespace = GetInterceptorsNamespace(options);

			// Generate source. One file for all the interceptors.
			// Interceptors.g.cs
			//
			var sb = new StringBuilder(
				$$"""
				// <auto-generated/>
				#pragma warning disable
				#nullable enable

				using System;

				using SR  = System.Reflection;
				using SLE = System.Linq.Expressions;
				using SCG = System.Collections.Generic;

				namespace System.Runtime.CompilerServices
				{
					[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
					file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
					{
					}
				}

				namespace {{interceptorsNamespace}}
				{
					using AspectGenerator = AspectGenerator;

					file static class AspectGeneratorInterceptors
					{
						static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
						{
							return expr switch
							{
								SLE.MethodCallExpression mc => mc.Method,
								_                           => throw new InvalidOperationException()
							};
						}

						static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
						static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);


				""");

			foreach (var interceptor in GetInterceptorInfos(aspectedMethods))
			{
				var method          = interceptor.Method;
				var interceptorName = interceptor.Name;
				var methods         = interceptor.Invocations;
				var attributes      = interceptor.Attributes;

				foreach (var p in method.Parameters)
				{
					switch (p.RefKind)
					{
						case RefKind.Ref :
						case RefKind.Out :
						case RefKind.In  :
							sb.AppendLine(
								$$"""
										static {{p.Type, -30}} {{interceptorName}}_Arg_{{p.Name, -13}} = default({{p.Type}});
								""");
							break;
					}
				}

				sb.AppendLine(
					$$"""
							static SR. MemberInfo                 {{interceptorName}}_MemberInfo        = MethodOf{{GetMethodOf(method, interceptorName)}};
					""");

				for (var i = 0; i < attributes.Count; i++)
				{
					var attr = attributes[i];

					sb
						.AppendLine(
							$$"""
									static SCG.Dictionary<string,object?> {{interceptorName}}_AspectArguments_{{i}} = new()
									{
							""")
						;

					foreach (var arg in GetAppliedAspectArguments(attr))
					{
							sb
								.AppendLine(
									$$"""
												["{{arg.Key}}"] = {{arg.Value}},
									""")
								;
					}

					sb
						.AppendLine(
							"""
									};
							""")
						;
				}

				sb.AppendLine(
					$$"""
							//
							/// <summary>
							/// Intercepts {{method}}.
							/// </summary>
							//
					""");

				foreach (var analyzedInvocation in methods)
				{
					var inv = analyzedInvocation.Inv;

					sb.AppendLine(
						$"""
								// Intercepts {inv}.
						""");

					void AppendInterceptsLocation(InvocationExpressionSyntax invocation)
					{
						var semantic = compilation.GetSemanticModel(invocation.SyntaxTree);

						var location = semantic.GetInterceptableLocation(invocation, spc.CancellationToken);

						if (location is null)
						{
							var descriptor = new DiagnosticDescriptor(
								DiagnosticID.CannotIntercept,
								"AspectGenerator",
								$"Invocation '{invocation}' cannot be intercepted by the compiler.",
								"AspectGenerator",
								DiagnosticSeverity.Warning,
								true);

							spc.ReportDiagnostic(
								Diagnostic.Create(descriptor, invocation.GetLocation()));
							return;
						}

						sb.Append("\t\t").AppendLine(location.GetInterceptsLocationAttributeSyntax());
					}

					switch (inv.Expression)
					{
						case MemberAccessExpressionSyntax : AppendInterceptsLocation(inv); break;
						case IdentifierNameSyntax         : AppendInterceptsLocation(inv); break;
						default :
							sb.AppendLine(
								$"""
										#error Unknown expression type {inv.Expression.GetType()} for : {inv.Expression}
								""");
							break;
					}

					sb.AppendLine(
						"""
								//
						""");
				}

				sb.AppendLine("\t\t[System.Runtime.CompilerServices.CompilerGenerated]");

				if (options.DebuggerStepThrough)
					sb.AppendLine("\t\t[System.Diagnostics.DebuggerStepThrough]");

				sb.Append("\t\tpublic static ");

				var methodModifierPosition = sb.Length;

				sb
					.AppendLine(
						$$"""
						{{PrintType(method.ReturnType)}} {{interceptorName}}({{PrintParameters(method)}})
								{
						""")
					;

				GenerateMethodBody(spc, sb, methods[0].Inv, method, interceptorName, attributes, methodModifierPosition);

				sb
					.AppendLine(
						"""
								}
						""")
					.AppendLine();
			}

			TrimEnd(sb);

			sb
				.AppendLine(
					"""
						}
					}
					""");

			spc.AddSource("Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		}

		static List<InterceptorInfo> GetInterceptorInfos(ImmutableArray<AnalyzedInvocation> aspectedMethods)
		{
			var nameCounter = 0;
			var nameSet     = new HashSet<string>();
			var result      = new List<InterceptorInfo>();

			string GetInterceptorName(string methodName)
			{
				return nameSet.Add(methodName) ? methodName : GetInterceptorName($"{methodName}_{++nameCounter}");
			}

			foreach (var group in aspectedMethods.GroupBy(static m => m.Method, SymbolEqualityComparer.Default).OrderBy(static m => m.Key!.Name))
			{
				var method     = (IMethodSymbol)group.Key!;
				var invocations = group.ToList();

				result.Add(new InterceptorInfo(
					method,
					invocations,
					GetInterceptorName($"{method.Name}_Interceptor"),
					GetOrderedAttributes(invocations[0].Attributes)));
			}

			return result;
		}

		static List<AttributeInfo> GetOrderedAttributes(List<AttributeInfo> attributes)
		{
			if (!attributes.Any(static a => a.AppliedAttributeData?.NamedArguments.Any(static na => na.Key == "Order") is true))
				return attributes;

			return
			(
				from a in attributes
				let o = a.AppliedAttributeData?.NamedArguments.Select(static na => (KeyValuePair<string,TypedConstant>?)na).FirstOrDefault(static na => na!.Value.Key == "Order")
				let n = o is null ? int.MaxValue : o.Value.Value.Value switch
				{
					string s => int.TryParse(s, out var n) ? n : null,
					int    n => (int?)n,
					_        => null
				}
				orderby n
				select a
			).ToList();
		}

		static void ValidateAspectHooksForMethod(
			List<DiagnosticInfo>    diagnostics,
			Compilation             compilation,
			InvocationExpressionSyntax invocationExpression,
			IMethodSymbol           targetMethod,
			List<AttributeInfo>     attributes,
			HashSet<string>         reportedDiagnostics)
		{
			var targetIsAsync = IsSupportedAsyncReturnType(targetMethod.ReturnType, out var asyncResultType);

			for (var idx = 0; idx < attributes.Count; idx++)
			{
				var attribute       = attributes[idx];
				var aspectArguments = GetAspectArguments(attribute).ToDictionary(static a => a.Key, static a => a.Value);
				var useInterceptData = aspectArguments.TryGetValue("UseInterceptData", out var useData) && useData is true;

				if (idx < attributes.Count - 1 &&
					aspectArguments.TryGetValue("OnCall", out var onCallValue) &&
					onCallValue is string onCall &&
					!string.IsNullOrWhiteSpace(onCall))
				{
					if (attribute.AppliedAttributeData?.ApplicationSyntaxReference is {} asr)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.OnCallNotLastAspect,
							$"Aspect '{attribute.AttributeClass}' specifies 'OnCall' interceptor and has to be the last one in aspect list.",
							Location.Create(asr.SyntaxTree, asr.Span));
					}
					else
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.OnCallNotLastMethod,
							$"Method '{targetMethod}' is decorated with an aspect that specifies 'OnCall' interceptor. This aspect has to be the last one in aspect list.",
							Location.Create(invocationExpression.SyntaxTree, invocationExpression.Span));
					}
				}

				foreach (var hook in GetHookContracts())
				{
					if (!aspectArguments.TryGetValue(hook.Name, out var hookNameValue) ||
						hookNameValue is not string hookName ||
						string.IsNullOrWhiteSpace(hookName))
						continue;

					var location = GetHookLocation(attribute, hook.Name, invocationExpression);

					if (hook.IsAsync && !targetIsAsync && !HasSyncFallback(aspectArguments, hook.Name))
					{
						var asyncVoidMessage = targetMethod is { IsAsync: true, ReturnsVoid: true }
							? " Async void target methods are not supported."
							: "";

						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.AsyncHookRequiresTask,
							$"Async hook '{hook.Name}' requires target method '{targetMethod.ToDisplayString()}' to return Task, Task<T>, ValueTask, or ValueTask<T>, or a synchronous fallback hook to be specified.{asyncVoidMessage}",
							location);
					}

					var methods       = attribute.AttributeClass.GetMembers(hookName).OfType<IMethodSymbol>().ToArray();
					var staticMethods = methods.Where(static m => m.IsStatic).ToArray();

					if (methods.Length == 0)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotFound,
							$"Aspect hook method '{hookName}' was not found on aspect type '{attribute.AttributeClass.ToDisplayString()}'.",
							location);
						continue;
					}

					if (staticMethods.Length == 0)
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookMethodNotStatic,
							$"Aspect hook method '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' must be static.",
							location);
						continue;
					}

					if (hook.Name == "OnCall")
					{
						if (!staticMethods.Any(m => IsValidOnCallHook(compilation, m, targetMethod, targetIsAsync, asyncResultType)))
						{
							ReportDiagnostic(
								diagnostics,
								reportedDiagnostics,
								DiagnosticID.OnCallHookMismatch,
								$"OnCall hook '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' must match target method '{targetMethod.ToDisplayString()}'.",
								location);
						}

						continue;
					}

					var methodsWithValidParameters = staticMethods
						.Where(m => IsValidLifecycleHookParameter(m, targetMethod, targetIsAsync, asyncResultType, useInterceptData))
						.ToArray();

					if (methodsWithValidParameters.Length == 0)
					{
						var diagnosticId = useInterceptData ? DiagnosticID.HookRequiresInterceptData : DiagnosticID.HookInvalidParameters;

						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							diagnosticId,
							diagnosticId == DiagnosticID.HookRequiresInterceptData
								? $"UseInterceptData=true requires hook method '{hookName}' to accept ref InterceptData<T> for '{hook.Name}'. Candidates: {string.Join("; ", staticMethods.Select(static m => m.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)))}."
								: $"Hook method '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' has an invalid parameter list for '{hook.Name}'. Candidates: {string.Join("; ", staticMethods.Select(static m => m.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)))}.",
							location);
						continue;
					}

					if (!methodsWithValidParameters.Any(m => IsValidLifecycleHookReturnType(compilation, m, hook, targetMethod, targetIsAsync, asyncResultType, useInterceptData)))
					{
						ReportDiagnostic(
							diagnostics,
							reportedDiagnostics,
							DiagnosticID.HookInvalidReturnType,
							$"Hook method '{hookName}' on aspect type '{attribute.AttributeClass.ToDisplayString()}' has an invalid return type for '{hook.Name}'.",
							location);
					}
				}
			}

			static bool HasSyncFallback(Dictionary<string,object?> aspectArguments, string asyncHookName)
			{
				var syncHookName = asyncHookName.EndsWith("Async", StringComparison.Ordinal)
					? asyncHookName[..^5]
					: asyncHookName;

				return syncHookName != asyncHookName &&
					aspectArguments.TryGetValue(syncHookName, out var value) &&
					value is string s &&
					!string.IsNullOrWhiteSpace(s);
			}
		}

		readonly record struct HookContract(string Name, bool IsAsync);

		static IEnumerable<HookContract> GetHookContracts()
		{
			yield return new("OnInit",            false);
			yield return new("OnUsing",           false);
			yield return new("OnUsingAsync",      true);
			yield return new("OnBeforeCall",      false);
			yield return new("OnBeforeCallAsync", true);
			yield return new("OnCall",            false);
			yield return new("OnAfterCall",       false);
			yield return new("OnAfterCallAsync",  true);
			yield return new("OnCatch",           false);
			yield return new("OnCatchAsync",      true);
			yield return new("OnFinally",         false);
			yield return new("OnFinallyAsync",    true);
		}

		static Location GetHookLocation(AttributeInfo attribute, string hookName, InvocationExpressionSyntax invocationExpression)
		{
			if (attribute is { AspectDefinitionSyntax: {} syntax, AspectDefinitionSemanticModel: not null })
			{
				foreach (var arg in syntax.ArgumentList?.Arguments ?? default)
					if (arg.NameEquals?.Name.Identifier.ValueText == hookName)
						return arg.Expression.GetLocation();
			}

			if (attribute.AspectDefinitionData?.ApplicationSyntaxReference is {} aspectSyntaxReference)
				return Location.Create(aspectSyntaxReference.SyntaxTree, aspectSyntaxReference.Span);

			if (attribute.AppliedAttributeData?.ApplicationSyntaxReference is {} attributeSyntaxReference)
				return Location.Create(attributeSyntaxReference.SyntaxTree, attributeSyntaxReference.Span);

			return invocationExpression.GetLocation();
		}

		static bool IsValidLifecycleHookParameter(
			IMethodSymbol hookMethod,
			IMethodSymbol targetMethod,
			bool          targetIsAsync,
			ITypeSymbol?  asyncResultType,
			bool          useInterceptData)
		{
			if (hookMethod.Parameters.Length != 1)
				return false;

			var parameter = hookMethod.Parameters[0];

			if (useInterceptData)
			{
				if (parameter.RefKind != RefKind.Ref)
					return false;

				return IsInterceptDataType(parameter.Type, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType));
			}

			return parameter.RefKind == RefKind.None &&
				(parameter.Type.TypeKind == TypeKind.Dynamic ||
				IsInterceptInfoType(parameter.Type, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType), allowNonGeneric: true));
		}

		static bool IsValidLifecycleHookReturnType(
			Compilation   compilation,
			IMethodSymbol hookMethod,
			HookContract  hook,
			IMethodSymbol targetMethod,
			bool          targetIsAsync,
			ITypeSymbol?  asyncResultType,
			bool          useInterceptData)
		{
			if (hook.Name == "OnInit")
				return useInterceptData
					? IsInterceptDataType(hookMethod.ReturnType, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType))
					: IsInterceptInfoType(hookMethod.ReturnType, hookMethod, GetHookReturnValueType(targetMethod, targetIsAsync, asyncResultType), allowNonGeneric: false);

			if (hook.Name == "OnUsing")
				return ImplementsType(hookMethod.ReturnType, "System.IDisposable");

			if (hook.Name == "OnUsingAsync")
				return ImplementsType(hookMethod.ReturnType, "System.IAsyncDisposable");

			if (hook.IsAsync)
				return IsSupportedAsyncReturnType(hookMethod.ReturnType, out _);

			return hookMethod.ReturnsVoid;
		}

		static bool IsValidOnCallHook(
			Compilation   compilation,
			IMethodSymbol hookMethod,
			IMethodSymbol targetMethod,
			bool          targetIsAsync,
			ITypeSymbol?  asyncResultType)
		{
			var expectedParameters = GetOnCallParameters(targetMethod).ToArray();

			if (hookMethod.Parameters.Length != expectedParameters.Length)
				return false;

			for (var i = 0; i < expectedParameters.Length; i++)
			{
				var actual   = hookMethod.Parameters[i];
				var expected = expectedParameters[i];

				if (actual.RefKind != expected.RefKind)
					return false;

				if (!SymbolEqualityComparer.Default.Equals(actual.Type, expected.Type))
					return false;
			}

			if (targetMethod.ReturnsVoid)
				return hookMethod.ReturnsVoid;

			if (targetIsAsync)
				return IsSupportedAsyncReturnType(hookMethod.ReturnType, out var hookAsyncResultType) &&
					(asyncResultType is null && hookAsyncResultType is null ||
					 asyncResultType is not null &&
					 hookAsyncResultType is not null &&
					 SymbolEqualityComparer.Default.Equals(asyncResultType, hookAsyncResultType));

			return compilation.ClassifyConversion(hookMethod.ReturnType, targetMethod.ReturnType).IsImplicit;
		}

		static IEnumerable<(ITypeSymbol Type, RefKind RefKind)> GetOnCallParameters(IMethodSymbol targetMethod)
		{
			if (targetMethod.IsExtensionMethod || !targetMethod.IsStatic)
			{
				var receiverType = targetMethod.ReceiverType ?? targetMethod.ContainingType;

				if (receiverType is not null)
					yield return (receiverType, RefKind.None);
			}

			foreach (var parameter in targetMethod.Parameters)
				yield return (parameter.Type, parameter.RefKind);
		}

		static (ITypeSymbol? Type, bool IsVoid) GetHookReturnValueType(IMethodSymbol targetMethod, bool targetIsAsync, ITypeSymbol? asyncResultType)
		{
			if (targetMethod.ReturnsVoid || targetIsAsync && asyncResultType is null)
				return (null, true);

			return targetIsAsync ? (asyncResultType, false) : (targetMethod.ReturnType, false);
		}

		static bool IsInterceptInfoType(
			ITypeSymbol                    type,
			IMethodSymbol                  hookMethod,
			(ITypeSymbol? Type, bool IsVoid) expectedValueType,
			bool                           allowNonGeneric)
		{
			if (type is not INamedTypeSymbol namedType)
				return false;

			if (!IsAspectGeneratorType(namedType, "InterceptInfo"))
				return IsUnresolvedCarrierType(type, "InterceptInfo", allowNonGeneric);

			if (namedType.Arity == 0)
				return allowNonGeneric;

			return namedType is { Arity: 1, TypeArguments: [var valueType] } &&
				TypeArgumentMatches(valueType, hookMethod, expectedValueType);
		}

		static bool IsInterceptDataType(
			ITypeSymbol                    type,
			IMethodSymbol                  hookMethod,
			(ITypeSymbol? Type, bool IsVoid) expectedValueType)
		{
			if (type is not INamedTypeSymbol namedType)
				return false;

			if (!IsAspectGeneratorType(namedType, "InterceptData"))
				return IsUnresolvedCarrierType(type, "InterceptData", allowNonGeneric: false);

			return namedType is { Arity: 1, TypeArguments: [var valueType] } &&
				TypeArgumentMatches(valueType, hookMethod, expectedValueType);
		}

		static bool IsUnresolvedCarrierType(ITypeSymbol type, string name, bool allowNonGeneric)
		{
			var displayName = type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);

			return allowNonGeneric && displayName == name ||
				displayName.StartsWith(name + "<", StringComparison.Ordinal);
		}

		static bool TypeArgumentMatches(
			ITypeSymbol                    type,
			IMethodSymbol                  hookMethod,
			(ITypeSymbol? Type, bool IsVoid) expectedValueType)
		{
			if (type is ITypeParameterSymbol typeParameter &&
				SymbolEqualityComparer.Default.Equals(typeParameter.ContainingSymbol, hookMethod))
				return true;

			if (expectedValueType.IsVoid)
				return type.SpecialType == SpecialType.System_Void ||
					type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat) == "System.Void" ||
					type is INamedTypeSymbol namedType && IsAspectGeneratorType(namedType, "Void");

			return expectedValueType.Type is not null &&
				SymbolEqualityComparer.Default.Equals(type, expectedValueType.Type);
		}

		static bool IsAspectGeneratorType(INamedTypeSymbol type, string name)
		{
			if (type.Name != name)
				return false;

			var @namespace = type.ContainingNamespace.ToDisplayString();

			return @namespace is "" or "AspectGenerator";
		}

		static bool IsSupportedAsyncReturnType(ITypeSymbol type, out ITypeSymbol? resultType)
		{
			resultType = null;

			if (type is not INamedTypeSymbol namedType ||
				namedType.Name is not ("Task" or "ValueTask") ||
				namedType.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
				return false;

			if (namedType is { IsGenericType: true, TypeArguments: [var asyncResultType] })
				resultType = asyncResultType;

			return true;
		}

		static bool ImplementsType(ITypeSymbol type, string metadataName)
		{
			return IsType(type, metadataName) ||
				type.AllInterfaces.Any(i => IsType(i, metadataName));
		}

		static bool IsType(ITypeSymbol type, string metadataName)
		{
			if (type is not INamedTypeSymbol namedType)
				return false;

			return namedType.ContainingNamespace.ToDisplayString() + "." + namedType.Name == metadataName;
		}

		static void GenerateMethodBody(
			SourceProductionContext    spc,
			StringBuilder              sb,
			InvocationExpressionSyntax invocationExpression,
			IMethodSymbol              method,
			string                     interceptorName,
			List<AttributeInfo>        attributes,
			int                        methodModifierPosition)
		{
			var isReturnsAsyncType = IsSupportedAsyncReturnType(method.ReturnType, out var asyncResultType);
			var generateAsync      = isReturnsAsyncType && attributes.Any(d => GetAspectArguments(d).Any(a => a.Key.EndsWith("Async") && a.Value is not null));
			var generateArgs       = attributes.Any(d => GetAspectArguments(d).Any(a => a is { Key: "PassArguments", Value: true }));

			// Generate arguments.
			//
			if (generateArgs)
			{
				sb.Append("\t\t\tvar __args__ = new object?[] { ");

				if (method.IsStatic == false)
					sb.Append("__this__, ");

				foreach (var p in method.Parameters)
					sb.Append(p.Name).Append(p.RefKind == RefKind.Out ? " = default, " : ", ");

				while (sb[^1] is ' ' or ',')
					sb.Length--;

				sb.Append(" };").AppendLine().AppendLine();
			}

			GenerateAttribute(0, "\t\t\t", false);

			void GenerateAttribute(int idx, string indent, bool isPrevData)
			{
				var attr   = attributes[idx].AttributeClass!;

				// Get aspect attribute parameters.
				//
				object? onInit           = null;
				object? onUsing          = null; object? onUsingAsync      = null;
				object? onBeforeCall     = null; object? onBeforeCallAsync = null;
				object? onCall           = null;
				object? onAfterCall      = null; object? onAfterCallAsync  = null;
				object? onCatch          = null; object? onCatchAsync      = null;
				object? onFinally        = null; object? onFinallyAsync    = null;
				var     useInterceptType = false;
				var     passArguments    = false;
				var     useInterceptData = false;
				var     needInfo         = attributes.Count > 1 || generateAsync;

				foreach (var arg in GetAspectArguments(attributes[idx]))
					switch (arg.Key)
					{
						case "OnInit"            : onInit            = arg.Value; needInfo = true; break;
						case "OnUsing"           : onUsing           = arg.Value; needInfo = true; break;
						case "OnUsingAsync"      : onUsingAsync      = arg.Value; needInfo = true; break;
						case "OnBeforeCall"      : onBeforeCall      = arg.Value; needInfo = true; break;
						case "OnBeforeCallAsync" : onBeforeCallAsync = arg.Value; needInfo = true; break;
						case "OnCall"            : onCall            = arg.Value;                  break;
						case "OnAfterCall"       : onAfterCall       = arg.Value; needInfo = true; break;
						case "OnAfterCallAsync"  : onAfterCallAsync  = arg.Value; needInfo = true; break;
						case "OnCatch"           : onCatch           = arg.Value; needInfo = true; break;
						case "OnCatchAsync"      : onCatchAsync      = arg.Value; needInfo = true; break;
						case "OnFinally"         : onFinally         = arg.Value; needInfo = true; break;
						case "OnFinallyAsync"    : onFinallyAsync    = arg.Value; needInfo = true; break;
						case "UseInterceptType"  : useInterceptType  = arg.Value is true; break;
						case "PassArguments"     : passArguments     = arg.Value is true; break;
						case "UseInterceptData"  : useInterceptData  = arg.Value is true; break;
					}

				if (generateAsync)
					sb.Insert(methodModifierPosition, "async ");

				var returnType = generateAsync ? asyncResultType?.ToString() ?? "AspectGenerator.Void" : method.ReturnsVoid ? "AspectGenerator.Void" : $"{method.ReturnType}";

				// Generate AspectCallInfo.
				//
				if (needInfo)
				{
					sb
						.Append(indent).AppendLine($"// {(object?)attributes[idx].AppliedAttributeData ?? attributes[idx].AttributeClass}")
						.Append(indent).AppendLine("//")
						//.Append(indent).Append($"var __attr__{idx} = new {attributes[idx]}").Append(attributes[idx].NamedArguments.Length == 0 ? "()" : "").AppendLine(";")
						.Append(indent).AppendLine($"var __info__{idx} = new AspectGenerator.Intercept{(useInterceptData ? "Data" : "Info")}<{returnType}>")
						.Append(indent).AppendLine("{")
						//.Append(indent).AppendLine($"\tReturnValue     = {(idx > 0 ? $"__info__{idx - 1}.ReturnValue" : $"default({(method.ReturnsVoid ? "Void" : $"{method.ReturnType}")})")},")
						.Append(indent).AppendLine($"\tMemberInfo      = {interceptorName}_MemberInfo,")
						.Append(indent).AppendLine($"\tAspectType      = typeof({attr}),")
						.Append(indent).AppendLine($"\tAspectArguments = {interceptorName}_AspectArguments_{idx},")
						;

					if (passArguments)
						sb
							.Append(indent).AppendLine("\tMethodArguments = __args__,")
							;

					if (idx > 0 && !isPrevData)
						sb.Append(indent).AppendLine($"\tPreviousInfo    = __info__{idx - 1}");

					sb
						.Append(indent).AppendLine("};")
						.AppendLine()
						;
				}

				// Generate OnInit.
				//
				if (onInit is not null)
				{
					GenerateInterceptType("", "OnInit")
						.Append(indent).AppendLine($"__info__{idx} = {attr.ContainingNamespace}.{attr.Name}.{onInit}({PassInfo(idx)});")
						.AppendLine()
						;
				}

				// Generate OnUsing.
				//
				if (generateAsync && onUsingAsync is not null || onUsing is not null)
				{
					var isAsync = generateAsync && onUsingAsync != null;
					GenerateInterceptType("", "OnUsing")
						.Append(indent).AppendLine($"{(isAsync ? "await " : "")}using ({attr.ContainingNamespace}.{attr.Name}.{(isAsync ? onUsingAsync : onUsing)}({PassInfo(idx)}))")
						.Append(indent).AppendLine("{")
						;
					indent += '\t';
				}

				// If OnCatch or OnFinally is defined, generate try/catch/finally block.
				//
				if (generateAsync && onCatchAsync   is not null || onCatch   is not null ||
					generateAsync && onFinallyAsync is not null || onFinally is not null)
				{
					sb.Append(indent).AppendLine("try");
					sb.Append(indent).AppendLine("{");
					indent += '\t';
				}

				// Generate OnBeforeCall.
				//
				if (generateAsync && onBeforeCallAsync is not null || onBeforeCall is not null)
				{
					GenerateInterceptType("", "OnBeforeCall");
					GenerateMethodCall(onBeforeCallAsync, onBeforeCall)
						.AppendLine()
						.Append(indent).AppendLine($"if (__info__{idx}.InterceptResult != AspectGenerator.InterceptResult.Return)")
						.Append(indent).AppendLine("{")
						;

					indent += '\t';
				}

				// Generate next attribute...
				//
				if (idx < attributes.Count - 1)
				{
					sb.Append(indent).AppendLine("{");

					GenerateAttribute(idx + 1, indent + '\t', useInterceptData);

					TrimEnd(sb);

					sb
						.Append(indent).AppendLine("}")
						.AppendLine()
						;
				}
				// .. or call the target method.
				//
				else
				{
					sb
						.Append(indent)
						.Append(
							method.ReturnsVoid || isReturnsAsyncType && asyncResultType is null
								? string.Empty
								: $"{(needInfo ? $"__info__{idx}.ReturnValue" : "var __return__")} = {(generateAsync ? "await " : "")}")
						.Append(
							onCall is null
								? method.IsExtensionMethod || method.IsStatic
									? method.OriginalDefinition.ContainingType
									: "__this__"
								: $"{attr.ContainingNamespace}.{attr.Name}")
						.Append('.')
						.Append(onCall ?? method.Name)
						.Append('(')
						;

					if (method.IsExtensionMethod || onCall is not null && method.IsStatic is false)
					{
						sb.Append("__this__");

						if (method.Parameters.Length > 0)
							sb.Append(", ");
					}

					foreach (var p in method.Parameters)
					{
						sb
							.Append(
								p.RefKind switch
								{
									RefKind.Ref => "ref ",
									RefKind.Out => "out ",
									RefKind.In  => "in ",
									_           => ""
								})
							.Append(p.Name)
							.Append(", ");
					}

					if (method.Parameters.Length > 0)
						sb.Length -= 2;

					sb
						.AppendLine(");")
						.AppendLine()
						;
				}

				// Generate OnAfterCall.
				//
				if (generateAsync && onAfterCallAsync is not null || onAfterCall is not null)
				{
					GenerateInterceptType("", "OnAfterCall");
					GenerateMethodCall(onAfterCallAsync, onAfterCall)
						.AppendLine();
				}

				// Generate OnBeforeCall end.
				//
				if (generateAsync && onBeforeCallAsync is not null || onBeforeCall is not null)
				{
					TrimEnd(sb);

					indent = indent[..^1];

					sb
						.Append(indent)
						.AppendLine("}")
						.AppendLine()
						;
				}

				// If OnCatch or OnFinally is defined, generate try/catch/finally block end.
				//
				if (generateAsync && onCatchAsync   is not null || onCatch   is not null ||
					generateAsync && onFinallyAsync is not null || onFinally is not null)
				{
					indent = indent[..^1];

					TrimEnd(sb);

					sb.AppendLine($"{indent}}}");

					// Generate OnCatch.
					//
					sb
						.Append(indent).AppendLine("catch (Exception __ex__)")
						.Append(indent).AppendLine("{")
						.Append(indent).AppendLine($"\t__info__{idx}.Exception{(onCatch is null ? null : "      ")} = __ex__;")
						;

					if (generateAsync && onCatchAsync is not null || onCatch is not null)
					{
						sb.Append(indent).AppendLine($"\t__info__{idx}.InterceptResult = AspectGenerator.InterceptResult.ReThrow;");

						GenerateInterceptType("\t", "OnCatch")
							.AppendLine()
							.Append('\t')
							;

						GenerateMethodCall(onCatchAsync, onCatch)
							.AppendLine()
							.Append(indent).AppendLine($"\tif (__info__{idx}.InterceptResult == AspectGenerator.InterceptResult.ReThrow)")
							.Append(indent).AppendLine("\t\tthrow;")
							;
					}
					else
					{
						sb.Append(indent).AppendLine("\tthrow;");
					}

					sb.Append(indent).AppendLine("}");

					// Generate OnFinally.
					//
					if (generateAsync && onFinallyAsync is not null || onFinally is not null)
					{
						sb
							.Append(indent).AppendLine("finally")
							.Append(indent).AppendLine("{");

						GenerateInterceptType("\t", "OnFinally")
							.Append('\t')
							;

						GenerateMethodCall(onFinallyAsync, onFinally)
							.Append(indent).AppendLine("}")
							;
					}

					sb.AppendLine();
				}

				// Generate OnUsing.
				//
				if (generateAsync && onUsingAsync is not null || onUsing is not null)
				{
					indent = indent[..^1];

					TrimEnd(sb);

					sb
						.Append(indent)
						.AppendLine("}")
						.AppendLine()
						;
				}

				// Generate return.
				//
				if (idx > 0)
					sb.Append(indent).AppendLine($"__info__{idx - 1}.ReturnValue = __info__{idx}.ReturnValue;");
				else if (!(method.ReturnsVoid || isReturnsAsyncType && asyncResultType is null))
					sb.AppendLine($"\t\t\treturn {(needInfo ? $"__info__{idx}.ReturnValue" : "__return__")};");

				TrimEnd(sb);

				string PassInfo(int idx)
				{
					return $"{(useInterceptData ? "ref " : "")}__info__{idx}";
				}

				StringBuilder GenerateMethodCall(object? onAsync, object? call)
				{
					if (generateAsync && onAsync is not null)
						return sb.Append(indent).AppendLine($"await {attr.ContainingNamespace}.{attr.Name}.{onAsync}({PassInfo(idx)});");
					return sb.Append(indent).AppendLine($"{attr.ContainingNamespace}.{attr.Name}.{call}({PassInfo(idx)});");
				}

				StringBuilder GenerateInterceptType(string additionalIndent, string interceptType)
				{
					if (useInterceptType)
					{
						sb
							.Append(additionalIndent)
							.Append(indent)
							.AppendLine($"__info__{idx}.InterceptType = AspectGenerator.InterceptType.{interceptType};");
					}

					return sb;
				}
			}
		}

		static void TrimEnd(StringBuilder sb)
		{
			while (sb[^1] is '\r' or '\n')
				sb.Length--;

			sb.AppendLine();
		}

		static string PrintValue(object? val, ITypeSymbol? type)
		{
			if (val is null)
				return "null";

			if (type?.TypeKind == TypeKind.Enum)
				return $"({type}){PrintValue(val, null)}";

			return val switch
			{
				string           s => SymbolDisplay.FormatLiteral(s, quote: true),
				char             c => SymbolDisplay.FormatLiteral(c, quote: true),
				bool             b => b ? "true" : "false",
				byte             b => b.ToString(CultureInfo.InvariantCulture),
				sbyte            b => b.ToString(CultureInfo.InvariantCulture),
				short            n => n.ToString(CultureInfo.InvariantCulture),
				ushort           n => n.ToString(CultureInfo.InvariantCulture),
				int              n => n.ToString(CultureInfo.InvariantCulture),
				uint             n => n.ToString(CultureInfo.InvariantCulture) + "u",
				long             n => n.ToString(CultureInfo.InvariantCulture) + "L",
				ulong            n => n.ToString(CultureInfo.InvariantCulture) + "uL",
				float            f => PrintSingle(f),
				double           d => PrintDouble(d),
				decimal          d => d.ToString(CultureInfo.InvariantCulture) + "m",
				INamedTypeSymbol s => $"typeof({s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})",
				_                  => Convert.ToString(val, CultureInfo.InvariantCulture) ?? "null"
			};

			static string PrintSingle(float value)
			{
				if (float.IsNaN(value))
					return "float.NaN";
				if (float.IsPositiveInfinity(value))
					return "float.PositiveInfinity";
				if (float.IsNegativeInfinity(value))
					return "float.NegativeInfinity";

				return value.ToString("R", CultureInfo.InvariantCulture) + "f";
			}

			static string PrintDouble(double value)
			{
				if (double.IsNaN(value))
					return "double.NaN";
				if (double.IsPositiveInfinity(value))
					return "double.PositiveInfinity";
				if (double.IsNegativeInfinity(value))
					return "double.NegativeInfinity";

				return value.ToString("R", CultureInfo.InvariantCulture) + "d";
			}
		}

		static string PrintType(ITypeSymbol type)
		{
			return $"{type}";
		}

		static string PrintParameters(IMethodSymbol method)
		{
			var parameters = method.Parameters;
			var sb         = new StringBuilder();

			if (method.IsStatic == false)
				sb.Append($"this {method.ReceiverType} __this__, ");

			foreach (var p in parameters)
				sb
					.Append(p)
					.Append(", ")
					;

			if (parameters.Length != 0 || method.IsStatic == false)
				sb.Length -= 2;

			return sb.ToString();
		}

		static string GetMethodOf(IMethodSymbol method, string interceptorName)
		{
			var sb = new StringBuilder();

			sb.Append("(() => ");

			sb
				.Append(method.IsExtensionMethod || method.IsStatic ? method.OriginalDefinition.ContainingType : $"default({method.ReceiverType})")
				.Append('.')
				.Append(method.Name)
				.Append('(')
				;

			if (method.IsExtensionMethod)
				sb.Append($"default({method.ReceiverType}), ");

			foreach (var p in method.Parameters)
				switch (p.RefKind)
				{
					case RefKind.Ref : sb.Append($"ref {interceptorName}_Arg_{p.Name}, "); break;
					case RefKind.In  : sb.Append($"in {interceptorName}_Arg_{p.Name}, ");  break;
					case RefKind.Out : sb.Append($"out {interceptorName}_Arg_{p.Name}, "); break;
					default          : sb.Append($"default({p.Type}), ");                  break;
				}

			while (sb[^1] is ',' or ' ')
				sb.Length--;

			sb.Append("))");

			return sb.ToString();
		}
	}
}
