// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		private static class TestMethod_Interceptor_State
		{
			internal static readonly global::System.Reflection.MemberInfo TargetMethod = MethodOf(() => AspectGenerator.ClassLibrary.TestClass.TestMethod(default(string)));

			internal static readonly global::Aspects.CrossProjectAttribute Aspect0 = new global::Aspects.CrossProjectAttribute();

			static TestMethod_Interceptor_State()
			{
			}
		}
		//
		/// <summary>
		/// Intercepts AspectGenerator.ClassLibrary.TestClass.TestMethod(string).
		/// </summary>
		//
		// Intercepts TestMethod(str + " MainMethod").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "aJ+70nNHAWZ4fneAjRgLSqkAAABUZXN0Q2xhc3MuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static string TestMethod_Interceptor(string str)
		{
			// Aspects.CrossProjectAttribute
			//
			var __targetMethod__ = TestMethod_Interceptor_State.TargetMethod;

			var __aspect__0 = TestMethod_Interceptor_State.Aspect0;
			var __info__0   = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo = __targetMethod__,
				Aspect     = __aspect__0,
			};

			__info__0.ReturnValue = AspectGenerator.ClassLibrary.TestClass.TestMethod(str);

			Aspects.CrossProjectAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}
	}
}
