// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;
using SCG = System.Collections.Generic;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	file static class AspectGeneratorInterceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		static SR. MemberInfo                 TestMethod_Interceptor_MemberInfo        = MethodOf(() => AspectGenerator.ClassLibrary.TestClass.TestMethod(default(string)));
		static SCG.Dictionary<string,object?> TestMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts AspectGenerator.ClassLibrary.TestClass.TestMethod(string).
		/// </summary>
		//
		// Intercepts TestMethod(str + " MainMethod").
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "aJ+70nNHAWZ4fneAjRgLSqkAAABUZXN0Q2xhc3MuY3M=")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static string TestMethod_Interceptor(string str)
		{
			// Aspects.CrossProjectAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<string>
			{
				MemberInfo      = TestMethod_Interceptor_MemberInfo,
				AspectType      = typeof(Aspects.CrossProjectAttribute),
				AspectArguments = TestMethod_Interceptor_AspectArguments_0,
			};

			__info__0.ReturnValue = AspectGenerator.ClassLibrary.TestClass.TestMethod(str);

			Aspects.CrossProjectAttribute.OnAfterCall(__info__0);

			return __info__0.ReturnValue;
		}
	}
}
