// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace AspectGenerator
{
	/// <summary>
	/// Controls AspectGenerator compile-time report verbosity.
	/// </summary>
	public enum AspectReportVerbosity
	{
		/// <summary>No compile-time report diagnostics are emitted.</summary>
		Off = 0,
		/// <summary>Only the compact summary report is emitted.</summary>
		Quiet = 1,
		/// <summary>Summary and interceptor call-site reports are emitted.</summary>
		Minimal = 2,
		/// <summary>Minimal reports plus target method selection reports are emitted.</summary>
		Normal = 3,
		/// <summary>Normal reports plus TargetFilter final decision reports are emitted.</summary>
		Detailed = 4,
		/// <summary>Detailed reports plus TargetFilter rule/group match reports are emitted.</summary>
		Diagnostic = 5
	}

	/// <summary>
	/// Configures AspectGenerator for the current assembly.
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
	sealed class AspectGeneratorOptionsAttribute : Attribute
	{
		/// <summary>
		/// Gets or sets whether AspectGenerator emits the shared generated API types for this assembly.
		/// </summary>
		/// <remarks>
		/// Keep this enabled for single-project usage. Set it to <c>false</c> when the API is supplied by an aspect library referenced by this project.
		/// </remarks>
		public bool    GenerateApi                   { get; set; } = true;
		/// <summary>
		/// Gets or sets whether AspectGenerator emits interceptor implementations for this assembly.
		/// </summary>
		/// <remarks>
		/// This can be used to force interceptor generation in projects where generation would otherwise be skipped by build-time defaults.
		/// </remarks>
		public bool    GenerateInterceptors          { get; set; }
		/// <summary>
		/// Gets or sets whether generated API types are emitted as public types.
		/// </summary>
		/// <remarks>
		/// Use this for aspect-library projects that expose aspect definitions and generated API types to other projects.
		/// </remarks>
		public bool    PublicApi                     { get; set; }
		/// <summary>
		/// Gets or sets whether generated interceptor methods are marked with <see cref="System.Diagnostics.DebuggerStepThroughAttribute"/>.
		/// </summary>
		public bool    DebuggerStepThrough           { get; set; }
		/// <summary>
		/// Gets or sets the minimal report verbosity required to emit summary report diagnostics.
		/// </summary>
		public AspectReportVerbosity SummaryVerbosity      { get; set; } = AspectReportVerbosity.Quiet;
		/// <summary>
		/// Gets or sets the minimal report verbosity required to emit interceptor call-site report diagnostics.
		/// </summary>
		public AspectReportVerbosity InterceptorsVerbosity { get; set; } = AspectReportVerbosity.Minimal;
		/// <summary>
		/// Gets or sets the minimal report verbosity required to emit target method report diagnostics.
		/// </summary>
		public AspectReportVerbosity TargetsVerbosity      { get; set; } = AspectReportVerbosity.Normal;
		/// <summary>
		/// Gets or sets the minimal report verbosity required to emit target-filter report diagnostics.
		/// </summary>
		public AspectReportVerbosity FiltersVerbosity      { get; set; } = AspectReportVerbosity.Diagnostic;
		/// <summary>
		/// Gets or sets the namespace used for generated interceptor types.
		/// </summary>
		/// <remarks>
		/// The namespace must also be listed in the project <c>InterceptorsNamespaces</c> MSBuild property so Roslyn can use the generated interceptors.
		/// </remarks>
		public string? InterceptorsNamespace         { get; set; }
	}
}
