// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace AspectGenerator
{
	/// <summary>
	/// Specifies how AspectGenerator reports optional diagnostics.
	/// </summary>
	/// <remarks>
	/// Values except <see cref="Off"/> map directly to Microsoft.CodeAnalysis.DiagnosticSeverity.
	/// </remarks>
	enum AspectDiagnosticSeverity
	{
		/// <summary>
		/// Do not report optional diagnostics.
		/// </summary>
		Off = -1,
		/// <summary>
		/// Something that is an issue, as determined by some authority, but is not surfaced through normal means.
		/// </summary>
		Hidden = 0,
		/// <summary>
		/// Information that does not indicate a problem.
		/// </summary>
		Info = 1,
		/// <summary>
		/// Something suspicious but allowed.
		/// </summary>
		Warning = 2,
		/// <summary>
		/// Something not allowed by the rules of the language or other authority.
		/// </summary>
		Error = 3,
	}

	/// <summary>
	/// Configures AspectGenerator for the current assembly.
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
	sealed class AspectGeneratorOptionsAttribute : Attribute
	{
		/// <summary>
		/// Gets or sets whether AspectGenerator emits the shared generated API types for this assembly.
		/// </summary>
		/// <remarks>
		/// Keep this enabled for single-project usage. Set it to <c>false</c> when the API is supplied by an aspect library referenced by this project.
		/// </remarks>
		public bool    GenerateApi           { get; set; } = true;
		/// <summary>
		/// Gets or sets whether generated API types are emitted as public types.
		/// </summary>
		/// <remarks>
		/// Use this for aspect-library projects that expose aspect definitions and generated API types to other projects.
		/// </remarks>
		public bool    PublicApi             { get; set; }
		/// <summary>
		/// Gets or sets whether generated interceptor methods are marked with <see cref="System.Diagnostics.DebuggerStepThroughAttribute"/>.
		/// </summary>
		public bool    DebuggerStepThrough   { get; set; }
		/// <summary>
		/// Gets or sets the namespace used for generated interceptor types.
		/// </summary>
		/// <remarks>
		/// The package normally appends this namespace to the project <c>InterceptorsNamespaces</c> MSBuild property for direct package consumers.
		/// Custom build setups must ensure this namespace is listed so Roslyn can use the generated interceptors.
		/// </remarks>
		public string? InterceptorsNamespace { get; set; }
		/// <summary>
		/// Gets or sets how AspectGenerator reports optional diagnostics such as intercepted-call markers.
		/// </summary>
		/// <remarks>
		/// Set to <see cref="AspectGenerator.AspectDiagnosticSeverity.Off"/> to disable optional diagnostics.
		/// </remarks>
		public AspectDiagnosticSeverity AspectDiagnosticSeverity { get; set; } = AspectDiagnosticSeverity.Info;
	}
}
