// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

using SR  = System.Reflection;
using SLE = System.Linq.Expressions;
using SCG = System.Collections.Generic;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
	{
	}
}

namespace AspectGenerator
{
	using AspectGenerator = AspectGenerator;

	static partial class Interceptors
	{
		static SR.MethodInfo GetMethodInfo(SLE.Expression expr)
		{
			return expr switch
			{
				SLE.MethodCallExpression mc => mc.Method,
				_                           => throw new InvalidOperationException()
			};
		}

		static SR.MethodInfo MethodOf<T>(SLE.Expression<Func<T>> func) => GetMethodInfo(func.Body);
		static SR.MethodInfo MethodOf   (SLE.Expression<Action>  func) => GetMethodInfo(func.Body);

		static SR. MemberInfo                 InstanceMethod_Interceptor_MemberInfo        = MethodOf(() => default(ClassLibrary.Class1).InstanceMethod());
		static SCG.Dictionary<string,object?> InstanceMethod_Interceptor_AspectArguments_0 = new()
		{
		};
		//
		/// <summary>
		/// Intercepts ClassLibrary.Class1.InstanceMethod().
		/// </summary>
		//
		// Intercepts new Class1().InstanceMethod().
		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "rlSSwFZlhuPl4h38tO3yfpYAAABQcm9ncmFtLmNz")]
		//
		[System.Runtime.CompilerServices.CompilerGenerated]
		public static void InstanceMethod_Interceptor(this ClassLibrary.Class1 __this__)
		{
			// AspectLibrary.ConsoleLogAttribute
			//
			var __info__0 = new AspectGenerator.InterceptInfo<AspectGenerator.Void>
			{
				MemberInfo      = InstanceMethod_Interceptor_MemberInfo,
				AspectType      = typeof(AspectLibrary.ConsoleLogAttribute),
				AspectArguments = InstanceMethod_Interceptor_AspectArguments_0,
			};

			AspectLibrary.ConsoleLogAttribute.OnBeforeCall(__info__0);

			if (__info__0.InterceptResult != AspectGenerator.InterceptResult.Return)
			{
				__this__.InstanceMethod();

				AspectLibrary.ConsoleLogAttribute.OnAfterCall(__info__0);
			}
		}
	}
}
